### ISSUE TITLE
Feature Request - Export/Import  Active Effects from Compendiums

### ISSUE THREAD

**Issue by p4535992** [DFreds/dfreds-convenient-effects#10]
**Is your feature request related to a problem? Please describe.**

I have some player with customized effect or some effect not yet present on the module.s
I want to every "smart" player give the opportunity to prepare the active effects for their characters
I want to manage some mechanism for create a custom  collection of effects for every player, like a specific collection of effects

**Describe the solution you'd like**

What mechanism can we use for create with foundry some active effects ? 

We can create Items with precompiled  active effects and then with some code extarct the effects from the items!

How can i connect these items to the players ? 

We can use Folders with the same name of the player or some compendium or use permissions filter on the item. 

It's better to use compendium because is more stable between world.

Other advantage of use the compendiums is the possibility to use already prepared spells on external module like "Active Token Lighting" and "Dynamic-Effects-SRD" or any other module with a particolar compendium.

**Describe alternatives you've considered**

**Additional context**

I can help with the code if you like the idea.

Here some piece of code for accomplis this and give a better idea:

```javascript

 export const retrieveEffectFromCompendium  = async (compendiumPackName,effectName) => {
  if(!game.settings.get(Settings.PACKAGE_NAME, Settings.SEARCH_ON_COMPENDIUM)){
     return null; // Compendium is not activate use the standard code
  } 
  if(!compendiumPackName || !effectName){
    return null;
  }
  const pack = game.packs.get(compendiumPackName);
  if(pack){
      try{
          await pack.getIndex();
      }catch(e){
          console.error(e);
      }
      //const effectId = pack.index.find(e => e.name === effectName)._id;
      const packItem = pack.index.find(e => e.name === effectName);
      if(packItem){
          const packItemId = packItem._id;
          const packItemImg = packItem.img;
          //let packItemEntry = await pack.getEntry(packItemId);
          let effect = await pack.getEntry(packItemId).then(effect => {
              if(!effect.name){
                  effect.name = effectName;
              }
              // if(!effect.description){
              //     effect.description = effectName;
              // }
              if(!effect.icon){
                  effect.icon = packItemImg;
              }
              return effect;
          });
          //const actor = game.user.character;
          //await pack.getEntry(effectId).then(effect => actor.createOwnedItem(effect) );
          //return packItemEntry.effects[0];
          return effect;
      }else{
          console.error("Can't find effect '"+effectName+"' on compendium '"+compendiumPackName+"");
          //DEFAULT VALUE
          return null;
      }
  }else{
      console.error("Can't find compendium with name '"+compendiumPackName+"'");
      //DEFAULT VALUE
      return null;
  }
}

export const importEffectToCompendium = async function(compendiumPackName,effect){
  // Reference a Compendium pack by it's collection ID
  const pack = game.packs.find(p => p.collection === compendiumPackName);

  // Load an external JSON data file which contains data for import
  // const response = await fetch("worlds/myworld/data/import.json");
  // const content = await response.json();
  const content = effect;
  // Create temporary Actor entities which impose structure on the imported data
  const activeEffect = await Item.create(content, {temporary: true});

  // Save each temporary Actor into the Compendium pack
  await pack.importEntity(activeEffect);
  console.log(`Imported Effect ${activeEffect.data.name} into Compendium pack ${compendiumPackName}`);
  return effect;
}

```

**Comment by DFreds** [comment]
Yeah, this feature is coming (see [FUTURE.md](https://github.com/DFreds/dfreds-convenient-effects/blob/main/FUTURE.md)), but I'm not quite sure I want to do it this way. While this method has the convenience of maintaining your effects via a compendium, it seems a little counterintuitive otherwise. But I am not totally writing this method off yet either. I have to experiment on various methods for accomplishing it.

Thanks for the suggestion though!
