### ISSUE TITLE
Allow drag and drop from the effect list to actor sheets

### ISSUE THREAD

**Issue by akrigline** [DFreds/dfreds-convenient-effects#100]
**Is your feature request related to a problem? Please describe.**
Instead of always requiring a token selection, it would be neat to be able to drag and drop effects onto actor sheets. This would also allow the module to be used when the canvas is off (kind of, the window would still need to be opened somehow).

By implementing a dragStart handler which constructs drag data in the same format the core uses to drag and drop effects, a de-facto standard for these drag and droppable effects can be used by other modules to enable further drag and drop functionality.

**Describe the solution you'd like**
Core has a drop handler for ActiveEffects built into ActorSheet (`ActorSheet._onDropActiveEffect`), it expects the parsed dropData to look like this:
```
const dropData = {
  type: "ActiveEffect",
  data: activeEffectDocumentData
}
```

Where `activeEffectDocumentData` is the `data` attribute of the effect being dropped, such that it can be fed to `ActiveEffect.create`.

There's no harm in having additional information, so I think your current data would not need to be changed, only added to.

**Describe alternatives you've considered**
Implementing something custom which interprets your current custom dropData correctly for my own modules, though this does not allow dropping onto an Actor Sheet.

**Additional context**
I am in the process of creating a few tiny modules to power up the effect creation workflow (drag and drop effects onto items, owned items), and would love to be able to drag from the Convenient Effects application the same way as I can drag from Actor Sheets.

**Comment by DFreds** [comment]
Interesting. Thanks for the details. I think this is possible... I'll investigate further.

**Comment by DFreds** [comment]
Added in v1.16.0
