### ISSUE TITLE
Allow for custom TMFX

### ISSUE THREAD

**Issue by robnmeyer** [DFreds/dfreds-convenient-effects#101]
Right now there is a large list of TMFX affects that can be used.  I am unclear where exactly these come from, but some of them don't work at all (such Spider Web or Ripples) and a lot of them seem to be the samples that TMFX published for illustration purposes.

It would be nice if 
a)  TMFX entries that don't work  be culled
b)  Custom TMFX macros (via macro name identifier) could added to the list allow for creating simple little effects outside of DFCE that match a DM's vision of a spell's effect (for example a light blue twinkly glow for Guiding Bolt).

**Comment by DFreds** [comment]
It's pretty easy to add/remove token magic effects. Here is an example in the core definitions: https://github.com/DFreds/dfreds-convenient-effects/blob/main/scripts/effects/effect-definitions.js#L845

I'm open to suggestions for any effects you think should have one. Feel free to give me the name of the token magic effect you like for a given effect, and it might make it into the core. 

Also, what ones did you see aren't working?

**Comment by robnmeyer** [comment]
For me (running 0.8.0) I couldn't get any of the Spider Web (any) or the Ripples to work.  But maybe I am just unaware of what they are suppose to be doing.

I see w/r to token magic.  Just change the attribute.key to 'macro.execute' and use a specific named TMFX.  That works great.  Thanks.

**Comment by robnmeyer** [comment]
Any way to add a hook to call a macro when the effect expires?  I can call directly a TMFX macro but it won't be removed unless I manually call another macro.  Maybe I am misunderstanding what you are suggesting.

**Comment by DFreds** [comment]
This seems like issues you should bring up to the token magic team, and potentially DAE as it is the one providing the macro.tokenMagic which adds/removes the token magic effects in an active effect. Convenient Effects just provides pre-defined effects where some include token magic. If they aren't working because I defined something incorrectly, then it is an issue here. Otherwise, it is an issue with one of those other modules.

**Comment by robnmeyer** [comment]
Yeah - I just realized you don't control that drop down.  Sorry for bothering you.  Cheers.
