### ISSUE TITLE
core .241 break current ATL settings

### ISSUE THREAD

**Issue by Tupsi** [DFreds/dfreds-convenient-effects#103]
**Describe the bug**
Upgrading to core .240 breaks the current ATL settings you use for items (torch, lamp, etc). Already made an issue over at ATL and just wanted to point out that you might have to change your presets as well. 
See https://github.com/kandashi/Active-Token-Lighting/issues/82

So to make it clear, this is not a bug in CE, but might need adjusting of your ATL values you use for lights.

**To Reproduce**
1. upgrade core to 0.9.241
2. Use on of the Equipment CE with ATL.

**Expected behavior**
Let there be light.

**Additional context**

**Comment by DFreds** [comment]
Thanks for the heads up. I'll track the ATE issue

**Comment by Tupsi** [comment]
just redid the upgrade and can no longer reproduce this error, so I am closing this. Might have been a layer 8 problem in the first place, who knows? ;-)
