### ISSUE TITLE
Right-clicking a Condition does not display Large Icon on Token

### ISSUE THREAD

**Issue by gabrieljtaylor** [DFreds/dfreds-convenient-effects#104]
**Describe the bug**
Right-clicking a condition does not apply the big condition image but just the effect with the little condition icon.

**To Reproduce**
1. Right-click a token and click the button to open the conditions menu
2. Right-click a condition (instead of left-clicking)

**Expected behavior**
The condition's icon should appear large atop the token, as it does in base Foundry with no modules.

**Screenshots**
n/a

**Additional context**
Foundry version 9, build 242
D&D 5E system version 1.5.6

I used Find the Culprit and it identified Dfreds Convenient Effects as the culprit.

No errors are generated in the console.

I checked through the module settings and couldn't find any settings that would impact this, nor could I find anything in the module's readme or wiki. I could not find any keyboard shortcuts that would enable the normal behavior. I'm not sure if this is intended or unintended behavior, but I would like to have some way to apply the large condition icons, and currently there doesn't seem to be a way to do so.

**Comment by DFreds** [comment]
I will be added this soon. Thanks for bringing it up!

**Comment by DFreds** [comment]
Released in v2.0.0
