### ISSUE TITLE
Conflict or bug with another module with light spell

### ISSUE THREAD

**Issue by Fridan99** [DFreds/dfreds-convenient-effects#105]
**when you activate the light spell, you cannot deactivate it afterwards**

**To Reproduce**
Foundry V 9.240
Dnd 1.5.6
DF Convenient Effects 1.16.0

**Without** any modules, only it dependecies and recomended

libWrapper 
socketlib
Times Up 
DAE
Midi-QOL
Active Token Lighting
Token Magic FX

**The module works like a charm.......**

The BUG

go to DFreds menu, and try to apply light spell on an actor...... ant then try to deactivate

Bug
When you try to disable, then you notice that you can't disable... and in the token is already emiting light. The only way to deactivate is go to the token vision, and set to 0 in light manually. 

Probable problem.... Probably a conflict with another module. I try to isolate which module is creating the conflict....

**Expected behavior**
Activate/deactivate light spell must work as normally

**Screenshots**
Console screenshot
![2](https://user-images.githubusercontent.com/86131373/149430710-1cad0d0c-a8f1-4a58-80b9-eeee06ca539f.jpg)

**Additional context**
Video

https://user-images.githubusercontent.com/86131373/149431602-50ae1c5b-3458-4591-b969-cfa0742213a6.mp4

**I will try to locate the module that is creating the conflict .....** 

it is true that this problem happened to me even in 0.8.9

**Comment by DFreds** [comment]
What version of Convenient Effects do you have installed?

**Comment by Fridan99** [comment]
I just isolated the problem, apparently it only happens with certain actors. When upgrading to v9, I think the DAE deprecated codes must be doing some kind of conflict. There is no other explanation, as with some actors that don't have any of the DAE it seems to work correctly. I will do more tests to try to track down to verify if it is that specific problem or not.

**Comment by thatlonelybugbear** [comment]
Can you export one actor that has the problem?

**Comment by Fridan99** [comment]
> Can you export one actor that has the problem?
> […](#)

Sure, let me 1h…..

**Comment by Fridan99** [comment]
https://easyupload.io/cl59ba

I just sent you via cloud link 3 actors (Since apparently here does not allow me). 2 of them you can not remove the effect of light, but subsequently entering the configuration of the token and doing it manually. The other token works perfectly. I have no idea what could be creating the bug. 

Frantz Fanon (Works well)

Jürgen (bug)

Leda (Lyssa) (bug)

**Comment by DFreds** [comment]
This is a bug with ATL. I think the fix is this:

`token.actor.unsetFlag("ATL", "originals")`

You can run this by creating a macro:

```js
const token = canvas.tokens.controlled[0];
token.actor.unsetFlag("ATL", "originals");
```

Then just select each broken individually and run it. If that doesn't fix it, I'd recommend opening an issue with ATL.

**Comment by Fridan99** [comment]
> ```js
> const token = canvas.tokens.controlled[0];
> token.actor.unsetFlag("ATL", "originals");
> ```
![3](https://user-images.githubusercontent.com/86131373/149565706-83d08292-ed09-4827-a4de-31c9268efc32.jpg)

When i try to execute the macro

**Comment by thatlonelybugbear** [comment]
No need to define token again in the macro.
`token.actor.unsetFlag("ATL", "originals");` would be enough for the token you control at the time.

Or if you open the console and you have a token selected you can type in there:
`_token.actor.unsetFlag("ATL", "originals");` to the same effect

**Comment by DFreds** [comment]
Huh, that is super weird. Sorry about that. This should work:

`canvas.tokens.controlled[0].actor.unsetFlag('ATL', 'originals');`

**Comment by DFreds** [comment]
> No need to define token again in the macro. `token.actor.unsetFlag("ATL", "originals");` would be enough for the token you control at the time.
> 
> Or if you open the console and you have a token selected you can type in there: `_token.actor.unsetFlag("ATL", "originals");` to the same effect

I did not know that got set automatically. 🤷

**Comment by Fridan99** [comment]
Or if you open the console and you have a token selected you can type in there:
_token.actor.unsetFlag("ATL", "originals"); to the same effect

That works for the Lyssa (Leda) actor.... but nor for Jürgen actor

**Comment by DFreds** [comment]
> Or if you open the console and you have a token selected you can type in there: _token.actor.unsetFlag("ATL", "originals"); to the same effect
> 
> That works for the Lyssa (Leda) actor.... but nor for Jürgen actor (it is strange but that actor still has the problem)

Hm... unfortunately, that exhausts my knowledge of the bug in ATL. I'd recommend opening an issue in ATL and providing that actor data in the issue.

**Comment by thatlonelybugbear** [comment]
@Fridan99 your Jurgen actor has some other issues. Have you cloned that one or something?

`foundry.js:316 RangeError: Maximum call stack size exceeded`

I will hit you up in Foundry discord
