### ISSUE TITLE
Clicking core status icons removes highlighting

### ISSUE THREAD

**Issue by kgruszcz** [DFreds/dfreds-convenient-effects#106]
**Describe the bug**
Left or right clicking a core status from the token hud status menu causes all other effects to become unlighted in the menu.

**To Reproduce**
With DFreds Convenient Effects enabled and the 'Modified Status Effects' in the 'Add' or 'None' option to allow for core status icons. Left or right clicking a core status (non-convenient effects) from the token hud status menu causes all other effects to become unhighlighted. 

Applying status via number key as with Status Icon Counter module or applying a status added by Convenient Effects refreshes the lost highlights to their correct state.  No error's appeared in the console. 

**Additional context**
Foundry 9.242
DnD5e 1.5.6
DFreds Convenient Effects 2.0.1

**Comment by DFreds** [comment]
Interesting. Something must have changed with v9. I'll investigate

**Comment by DFreds** [comment]
Forgot to close this, but it was fixed in v2.0.3
