### ISSUE TITLE
Custom Folders

### ISSUE THREAD

**Issue by Vestium-R** [DFreds/dfreds-convenient-effects#107]
It would be great to have a custom folders option to be able to organize custom effects.

I currently have about 35 effects and it would be nice to be able to organize them into separate folders (IE: adding lighting effects into a "Lights" folder. This would be especially handy when I can't remember what I named the effect I'm looking for but know it's a "light" effect

**Comment by DFreds** [comment]
Of course, good idea! Don't forget about the search functionality in the meantime

**Comment by DFreds** [comment]
Related to #73
