### ISSUE TITLE
Export to Compendia Option

### ISSUE THREAD

**Issue by JeffreyRijkse** [DFreds/dfreds-convenient-effects#108]
I use a shared module between games that I write data to: IE: If I create an NPC in world 1, I send it to the compendium and then can use it in world 2, 3, etc.

It would be great if there was a way to add support to export to compendias with CE.

I currently have different custom effects between games and sometimes add them on the fly and would be nice at the end of my game to send them to my compendium to keep them all "in sync"

**Comment by DFreds** [comment]
I can probably come up with some first party support for this. Stay tuned and use the export/import functionality for now

**Comment by DFreds** [comment]
Using a standard item compendium to store the item in addition to this module should cover any needs that the standard import/export don't: https://github.com/ElfFriend-DnD/foundryvtt-drop-effects-on-items
