### ISSUE TITLE
Darkvision doesn't change actual token vision

### ISSUE THREAD

**Issue by gravagehulk** [DFreds/dfreds-convenient-effects#11]
**Describe the bug**
When selecting "Darkvision" from spells, it applies the effect and the effect shows in active effects, but it appears to have no effect on the token's actual vision in the scene. It also doesn't change the token value for Darkvision.

**To Reproduce**
1. Select Token
2. Click on "Add convenient Effects"
3. Select Darkvision
4. Vision distance in darkness does not change.

**Expected behavior**
Maybe it's a limitation of the system, but I would expect the radius of the darkvision to change for the token, at least for the duration of the spell.

**Screenshots**
I could post before and after screenshots, but all they would show was the exact same radius of darkvision and the effect icon clearly applied to the token, as well as the effect under "temporary effects" in the "effects" tab.

**Additional context**
Is this expected behavior? Do I still need to manually adjust the token's darkvision setting for this to work? If so, other than a status icon, I'm not sure why this spell exists in the list.

Thank you!

**Comment by DFreds** [comment]
It does not actually change it, and that is a limitation of Foundry. Although I think this could be done if I added an effect supported by [ATL](https://github.com/kandashi/Active-Token-Lighting), which this module already does in other places. As it stands, this isn't really a bug, and more of a feature enhancement. I'll likely add this, but as I said, you'd need to include also use ATL.

**Comment by gravagehulk** [comment]
Thanks for confirming. I noticed that the Tim Posney's "Darkvision" spell does do this when cast on a token. It references some macro from an "embedded collection" that's not visible to the end user. I was trying to manually code CUB to do this for a special darkvision-granting ability and I can't find the right macro to call. I'm not sure what he's using, but it does work.

Appreciate all of your hard work on this module.

**Comment by DFreds** [comment]
Added the ATL integration with darkvision in v1.5.2. To use it, install ATL and check the "Integrate with ATL" setting included in this module.

**Comment by gravagehulk** [comment]
It works! Thank you! It's super helpful.
