### ISSUE TITLE
[Feature Request] Add a utility function to add custom effects without the constraint of the custom item

### ISSUE THREAD

**Issue by p4535992** [DFreds/dfreds-convenient-effects#110]
**Is your feature request related to a problem? Please describe.**

The use case in my opinion is generic, but to understand the problem I highlight a specific use case.
I have developed a module [Variant Encumbrance](https://github.com/VanirDev/VariantEncumbrance) to add and remove movement active effects (the classic encumbrance of dnd5e), everything works, plus for synchronization with your module I used the same names for the active effects of the encumbrance  `Encumbered, Heavily Encumbered` [like on your code](https://github.com/DFreds/dfreds-convenient-effects/blob/94db8987df02b24f63d5a73db27fff060495dded/scripts/effects/dynamic-effects-adder.js#L13) and the same [Effect object structure of your module](https://github.com/VanirDev/VariantEncumbrance/blob/master/src/module/effects/effect.ts) .

So what happens? for the two active effects `Encumbered, Heavily Encumbered` I have the chat messages and the other features of your module for the other two active effects `Unencumbered,Overburdened`  which are absent from the arrays of effect of your module no.

The purpose of all this is to directly add the Effect object to the custom effects array, so that i can recover with the function [`findEffectByName('Overburdened')`](https://github.com/DFreds/dfreds-convenient-effects/blob/94db8987df02b24f63d5a73db27fff060495dded/scripts/effects/effect-handler.js#L25) a result and take advantage of what you have already done.

**Describe the solution you'd like**

_The actual solution:_

The solution would be to create / update the custom effects item at runtime and then import them from the ready-made utility of your module, in the case of integrating modules / macros into your system it is **"not really easy"**.

_The wanted solution:_

Add a hook, or utility function, with the scope to add and perhaps even customize the effect arrays built by your module.

So if i wanted i can add a new variant of torch, or override the default one if i wanted.

**NOTE:** For me is just enough to be able to add the a `Effect object` to the array of custom effects i retreive with the code `game.dfreds.effects.all` or `game.dfreds.effects.customEffects`. For instance:

```
const myEffect = new Effect({...});
game.dfreds.effects.customEffects.push(myEffect);
```

**Describe alternatives you've considered**

create / update the custom effects item at runtime and then import them from the ready-made utility of your module

**Additional context**

Use case project: [Variant Encumbrance](https://github.com/VanirDev/VariantEncumbrance)

**Comment by p4535992** [comment]
uuuuh i will try this weekend ty very much!

**Comment by DFreds** [comment]
I added something specific for this... Let me know if this will work.

```js
  Hooks.on('dfreds-convenient-effects.ready', () => {
    game.dfreds.effectInterface.createNewCustomEffectWith({
      activeEffects: [
        { label: 'Test1', icon: 'icons/svg/aura.svg' },
        { label: 'Test2', icon: 'icons/svg/skull.svg' },
      ],
    });
  });
```

The data that is passed in are standard ActiveEffectData... i.e. from `canvas.tokens.controlled[0].actor.effects.get('some key').data.toObject()`

```json
{
    "_id": "0h52xkrbqrsi8yhn",
    "changes": [
        {
            "key": "data.attributes.ac.value",
            "mode": 4,
            "value": "16",
            "priority": 5
        }
    ],
    "disabled": false,
    "duration": {
        "startTime": 63733596794,
        "seconds": 3600
    },
    "icon": "systems/dnd5e/icons/spells/protect-orange-2.jpg",
    "label": "Barkskin",
    "tint": null,
    "transfer": false,
    "flags": {
        "core": {
            "statusId": "Convenient Effect: Barkskin"
        },
        "isConvenient": true,
        "convenientDescription": "Upgrade AC to 16 for 1 hour",
        "dae": {
            "transfer": false
        }
    }
}
```

**Comment by DFreds** [comment]
I think I will also have to add a method to check if a custom effect by the same name already exists...

**Comment by DFreds** [comment]
I also added this for specifically checking for custom effects. It will return undefined if it doesn't exist:

```js
game.dfreds.effectInterface.findCustomEffectByName('My custom effect')
```
