### ISSUE TITLE
Ray of Frost adding negative values to movement types with base speed of 0.

### ISSUE THREAD

**Issue by thatlonelybugbear** [DFreds/dfreds-convenient-effects#112]
Generally, the `data.attributes.movement.all` `Custom` DAE effect in the case of increasing or reducing speed by adding or subtracting values will apply to all movement types, even ones that are `0` by default.

So this happens.
![image](https://user-images.githubusercontent.com/7237090/150270713-66986455-55d0-4f7d-be2b-04deacbb9229.png)

That is working as intended only when multiplying or dividing and the base value is 0.

Edit: Don't know if this https://discord.com/channels/170995199584108546/699750150674972743/933526838490329179 helps at all. Trying to figure out if some such expression might be a viable workaround, as math functions are doable in effect values, eg `1+ ((@abilities.str.mod > 13) +0)`

**Comment by DFreds** [comment]
Fixed in #114
