### ISSUE TITLE
Little bug on effect-handler

### ISSUE THREAD

**Issue by p4535992** [DFreds/dfreds-convenient-effects#116]
**Describe the bug**

The line of code: https://github.com/DFreds/dfreds-convenient-effects/blob/fa0acd369dd9484f7707e8b83ead06e1029828db/scripts/effects/effect-handler.js#L78
use for the third parameter 'overlay', but it' seems the actual addEffect method: https://github.com/DFreds/dfreds-convenient-effects/blob/fa0acd369dd9484f7707e8b83ead06e1029828db/scripts/effects/effect-handler.js#L134
use the 'origin'

a solution can be something like this ?

```
const origin = `Actor.${uuid}`;
await this.addEffect({ effectName, uuid, origin, overlay }); 
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by DFreds** [comment]
I'm not sure I understand. The origin doesn't have to be defined, so it isn't there

**Comment by p4535992** [comment]
My ide tells me that it is an error that the function expects 4 arguments not 3, the variable 'origin' can also be undefined for the current use case. Am I wrong?

```
const origin = undefined;
await this.addEffect({ effectName, uuid, origin, overlay }); 
```

**Comment by DFreds** [comment]
Since this is object params, you can just not pass in that key. I don't know why your IDE would be telling you that?

This
```js
const origin = undefined;
await this.addEffect({ effectName, uuid, origin, overlay }); 
```

Is the same as this:
```js
await this.addEffect({ effectName, uuid, origin: undefined, overlay }); 
```

Which is the same as this:

```js
await this.addEffect({ effectName, uuid, overlay }); 
```

**Comment by p4535992** [comment]
kk is just some eslint rule than.
