### ISSUE TITLE
Integrate with the Changelog module

### ISSUE THREAD

**Issue by Maravedis** [DFreds/dfreds-convenient-effects#118]
**Is your feature request related to a problem? Please describe.**
This is not really a problem, more of a convenience thing. I really like being able to track changes in my modules and I think the module [Changelog](https://github.com/theripper93/libChangelogs) does a nice job of it. 

**Describe the solution you'd like**
I would like to see this module integrated in Changelogs.

**Additional context**
I'm ready to actually do the work to integrate the module , I just wanted to open an issue to 1) check that you were actually ok with it and 2) have an issue to link to if I were to do it.

**Comment by DFreds** [comment]
Hmm... So I read through the documentation, and it seems like it is a manual step I'd have to do on every release. I tend to avoid manual step things for releases as much as possible, hence the CI steps for creating them.

If there was a way for changelogs to pull directly from the release page of Github, I'd consider it. But as of now, I don't think I want to adds this dependency and more work for myself. If I'm wrong, let me know.
