### ISSUE TITLE
Disabling/editing Specific Effects

### ISSUE THREAD

**Issue by diannetea** [DFreds/dfreds-convenient-effects#12]
Our game uses homebrew rules for flanking, so having flanking automatically apply currently means we cannot use your mod.  If I could individually disable (or even edit) the effects it would be great, because I'd love to have flanking just work and use the effect (currently +1 to attack roll instead of advantage) that we use.

**Comment by DFreds** [comment]
Custom effects are on the roadmap, but the implementation will take some time. In the meantime, you could dive into the effect-defiintions.js file to figure out how it works and add your own. Just be aware that any updates to the module will override your changes, so you may want to lock the module from updating if you go that route.

**Comment by MSAbaddon** [comment]
Any update for the custom effects? I'm running Foundry on The Forge which makes it impossible to manually add custom effects in the definitions.js unfortunately.

**Comment by MSAbaddon** [comment]
Thanks for the reply.
I'll add a new issue with the effects. You're right, all of those effects could be rolled separately. I prefer adding them all together though, in case of critical hits and for easy hp adjustment of the targeted npc. One of my players actually uses hunter's mark, sneak attack and colossus slayer all at once, it's much easier to have all damage combines in one big number ;-)

**Comment by DFreds** [comment]
Custom effects are out in v1.9.0. Note that you cannot (currently) create custom effects with the same name as already defined effects

**Comment by MSAbaddon** [comment]
That's great news, I'll definately try it this weekend :-)
