### ISSUE TITLE
Add feature to stack duplicate flags 

### ISSUE THREAD

**Issue by SR5060** [DFreds/dfreds-convenient-effects#120]
I noticed your recent change log enables flag merging for duplicate flags. It would be great if this feature could also stack the effect (or add a function to allow stacking) either using the token stack module or something similar. This would be very helpful for effects like bleeding where the effect (and dae effects) could stack on top of itself over time

**Comment by DFreds** [comment]
That was actually referring to a different kind of flag merging. But I get your idea. I think that kind of falls outside the scope of this module... Could make a good separate module though
