### ISSUE TITLE
Darkvision not aplpying changes.

### ISSUE THREAD

**Issue by Nedrapter** [DFreds/dfreds-convenient-effects#123]
**Describe the bug**
Dark vision does not apply changes to token's vision. The following errors appear in the console.

![image](https://user-images.githubusercontent.com/74311190/152662937-77fb3458-37c6-4232-a628-fc1cb761a5f2.png)

**To Reproduce**
1. Select token.
2. Apply darkvision.

**Expected behavior**
Dim vision to change to 60.

**Comment by DFreds** [comment]
ATL issue, please see that repo
