### ISSUE TITLE
Hide names of token in chat when GM applies the effects.

### ISSUE THREAD

**Issue by Nedrapter** [DFreds/dfreds-convenient-effects#124]
**Is your feature request related to a problem? Please describe.**
When the GM is applying effects, the chat messages should not reveal the tokens' names.

**Describe the solution you'd like**
Substitute names with "Unknown"

**Comment by Oshcakes** [comment]
I was just coming here to suggest this as well.

**Comment by DFreds** [comment]
This isn't so easy, as the chat message is created by the GM and "broadcasted" to the players. To do the replacement requires some silly type of hacking. Is there a reason you couldn't simply disable chat effects for players? 

Alternatively, I could add a setting so that chat messages for effects on PCs/NPCs have different permission levels.

**Comment by Nedrapter** [comment]
It was convenient for players to see the changed in chat both because sometimes they don't remember all the icons and as reminders when they scroll up. But if it can't be easily changed I suppose I have to turn them off.

**Comment by DFreds** [comment]
So currently, there is the Chat Message Permission setting which lets you control which roles get the messages. I could separate it into Chat Message Permission (NPCs) and Chat Message Permission (PCs) if this is heavily desired

**Comment by Nedrapter** [comment]
No that is not needed (at least for me). I was hoping for the messages to be as they are with only the names actors that no player has access to, to be "Unknown", or maybe for Neutral tokens (cause I think players are considered Friendly? not sure)

**Comment by DFreds** [comment]
Yeah, that isn't something I'm interested in handling because it'll be hacky and brittle. Thanks for the suggestion though... If I come up with a better way to do it, I'll implement it
