### ISSUE TITLE
Feature Request: supress explanation text on removal

### ISSUE THREAD

**Issue by pesky-wobbit** [DFreds/dfreds-convenient-effects#125]
My players love seeing the explanation of effects as they are applied. But when they are removed, the text is redundant and clutter-y.

We would like a setting to disable the explanation text on removal. Perhaps another setting to disable the removal message entirely.

Thanks!

**Comment by DFreds** [comment]
Good idea!

**Comment by DFreds** [comment]
Added in v2.3.0
