### ISSUE TITLE
Hooded Lantern Nested Effects

### ISSUE THREAD

**Issue by cilise** [DFreds/dfreds-convenient-effects#130]
Could it be possible to add nested effects for the two ways the Hooded Lantern could be used, fully opened or partially opened?  

This module has been a game changer for myself and my players!

**Comment by DFreds** [comment]
Sure thing, I'll add it

**Comment by DFreds** [comment]
So thinking about this more, I don't know that it makes sense. An unhooded lantern is just a regular lantern, and there is already an effect for that.
