### ISSUE TITLE
None of the lights are working

### ISSUE THREAD

**Issue by arcanjl** [DFreds/dfreds-convenient-effects#131]
I am sure it is me. 

I have token.
I add any of the light effects to it.
Nothing happens. I mean it adds it to the token, and the character sheet but the lighting does not change.

I can go in the token settings and change it there and it works, but not by adding the convenient effect.

Thoughts?

**Comment by DFreds** [comment]
There is a setting to enable it in Convenient Effects. Is that enabled?

**Comment by arcanjl** [comment]
That sounds like something I would do... where is it?
<img width="1029" alt="Untitled" src="https://user-images.githubusercontent.com/29612539/155763351-9f3443c5-51fb-4b21-9a93-8f094c8900fb.png">

**Comment by DFreds** [comment]
Okay, looks like it. This might be related to an issue with ATE. What version of Foundry are you on?

**Comment by arcanjl** [comment]
It is the most up-to-date. I am out of town until Sunday. But I can make you a quick video to show you it, in case I am missing something stupid. I can post it on Sunday.

**Comment by arcanjl** [comment]
9.249

**Comment by arcanjl** [comment]
I couldn't do a video here (not at home), but I did a snap shot.
![Capture](https://user-images.githubusercontent.com/29612539/155817543-01ff6e66-2247-4d1f-bafe-3ba2eaaeefc1.PNG)

**Comment by DFreds** [comment]
Okay. I think this is an issue related to ATE. You can follow this thread https://github.com/DFreds/dfreds-convenient-effects/issues/105 or checkout the ATE github if it doesn't resolve it: https://github.com/kandashi/Active-Token-Lighting
