### ISSUE TITLE
[Minor BUG] Cannot import the description field when using the method 'createNewCustomEffectsWith' and  the chat handler show undefined description

### ISSUE THREAD

**Issue by p4535992** [DFreds/dfreds-convenient-effects#133]
**Describe the bug**
Cannot import the description field of the chat handler when using the method 'createNewCustomEffectsWith'.

**To Reproduce**

Just put the code because is a very easy fixing:

```
       const effects = <MY ARRAY OF EFFECTS>
        const activeEffectsData: any[] = [];
        for (const effect of effects) {
          // I also added this for specifically checking for custom effects.
          // It will return undefined if it doesn't exist:
          const effectFounded = game.dfreds.effectInterface.findCustomEffectByName(effect.name);
          if (!effectFounded) {
            const origin = undefined;
            const overlay = false;
            activeEffectsData.push(effect.convertToActiveEffectData({ origin, overlay }));
          }
        }
        //The data that is passed in are standard ActiveEffectData... i.e. from
        game.dfreds.effectInterface.createNewCustomEffectsWith({
          activeEffects: activeEffectsData,
        });
```
now on the chat handler class this line: https://github.com/DFreds/dfreds-convenient-effects/blob/3917056ee198f08ca28b456dd99f50ab01eead96/scripts/chat-handler.js#L65 has the description always undefined, this is because the ActiveEffectData doen't have a 'description' field (https://foundryvtt.com/api/data.ActiveEffectData.html)

A very simple solution for this is just to add a check ad then go to search for the convinient description.

so just replace this:

```
message += `<p>${effect.description}</p>`;
```

with this:

```
message += `<p>${effect.description ? effect.description : effect.flags.convenientDescription}</p>`;
```

or any solution you find more useful for this use case.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by DFreds** [comment]
First of all, thanks for using the issue template. Secondly, thanks for the details info and fix suggestion. I appreciate it :D 

Fixed in v2.4.4
