### ISSUE TITLE
Convenient Effects adding concentration condition to non-concentration spells

### ISSUE THREAD

**Issue by huzzy123** [DFreds/dfreds-convenient-effects#134]
I'm using MidiQoL along with Convenient Effects, but recently when I have been casting spells that use spell templates, it has been giving the Concentration condition to the token, even though the spell hasn't been marked as concentration (e.g. Thunderwave, Burning hands, etc). 

![image](https://user-images.githubusercontent.com/100808964/156463168-08b18e0b-af7b-41b4-ada8-6a9bee1f5770.png)

![image](https://user-images.githubusercontent.com/100808964/156463218-f1690aad-228e-4ca6-8143-9412aa175ecf.png)

This only seems to happen when the token isn't concentrating on a spell currently (including ones they shouldn't be concentrating on, e.g. thunderwave). Sometimes, when the token is already concentrating on a spell and I toggle another spell that requires concentration, it keeps the source the same rather than changing it to the new concentration spell.

**Comment by thatlonelybugbear** [comment]
That is an issue of MidiQOL and it will be fixed in MidiQOL 0.9.27 version afaik ;)

**Comment by DFreds** [comment]
Answered by @thatlonelybugbear
