### ISSUE TITLE
Nested Hooded Lantern

### ISSUE THREAD

**Issue by ctbritt** [DFreds/dfreds-convenient-effects#135]
Do you think you could create a nested effect for the hooded lantern? I'm trying to do something right now in an ItemMacro calling Lantern and Hooded Lantern and it's just not working well. 

Thanks!

**Comment by DFreds** [comment]
https://github.com/DFreds/dfreds-convenient-effects/issues/130

Not something I think makes a ton of sense... since lantern already exists. You should be able to use the API to do whatever you need though
