### ISSUE TITLE
Export and import single effects

### ISSUE THREAD

**Issue by jbowensii** [DFreds/dfreds-convenient-effects#136]
I would like a feature where I can export and import single custom effects so that I can share between friends/games the items they create without manually editing the .json file.  This would allow us to post a repository on github to share and people could pick and choose what they want.  Please...

**Comment by DFreds** [comment]
Great idea!

**Comment by DFreds** [comment]
Easiest way to do this in v7 is to create a new folder, add the effect to it, and export it. The other person would then create a new folder and import it.
