### ISSUE TITLE
[BUG] All custom passive effect are imported as temporary when i use the method 'createNewCustomEffectsWith'

### ISSUE THREAD

**Issue by p4535992** [DFreds/dfreds-convenient-effects#137]
**Describe the bug**
All custom passive effect are imported as temporary when i use the method 'createNewCustomEffectsWith'

**To Reproduce**
1. Prepare a custom effect and convert to active effect data for the method

```
       const effects = <MY ARRAY OF EFFECTS>
        const activeEffectsData: any[] = [];
        for (const effect of effects) {
          // I also added this for specifically checking for custom effects.
          // It will return undefined if it doesn't exist:
          const effectFounded = game.dfreds.effectInterface.findCustomEffectByName(effect.name);
          if (!effectFounded) {
            const origin = undefined;
            const overlay = false;
            activeEffectsData.push(effect.convertToActiveEffectData({ origin, overlay }));
          }
        }
        //The data that is passed in are standard ActiveEffectData... i.e. from
        game.dfreds.effectInterface.createNewCustomEffectsWith({
          activeEffects: activeEffectsData,
        });
```

where `activeEffectsData` is a single element array with this active effect data

```
{
    "id": "Convenient Effect: Darkvision",
    "name": "Darkvision",
    "label": "Darkvision",
    "description": "",
    "icon": "evil-eye-red-1.jpg",
    "tint": "",
    "flags": {
        "core": {
            "statusId": undefined, // don't understand but i need this to be undefined for set like a "passive" effect?
            "overlay": false
        },
        "dae": {}
    },
	
    "origin": "Scene.zj2YZXuRUdiw5x5v.Token.2pcyKBCcmWowqjOU",
    "transfer": true,
    "changes": [
        {
            "key": "data.attributes.senses.darkvision",
            "mode": 4,
            "value": "data.attributes.senses.darkvision",
            "priority": 5
        },
        {
            "key": "ATL.light.dim",
            "mode": 4,
            "value": "0",
            "priority": 5
        }
    ]
}
```
2. All my custom effect are imported :

![a](https://github.com/p4535992/conditional-visibility-new/raw/main/wiki/images/feature_dfred_conv_effects_1.png)

3. Click to apply th active effect, but is always apply has temporary instead of passive

4. After a while i found it's all depened from the `flags.core.statusId` . not sure why but if is not undefined the effect is always apply as temporary, if is undefined is setted as passive.

5. A possible solution can be to change this line : https://github.com/DFreds/dfreds-convenient-effects/blob/a4a50b4792db6228dfaf66004902c0364e47ae74/scripts/effects/effect.js#L59

into to this:

`statusId: !isTemporary ? undefined : this._id,` where `isTemporary` is some value i put whit some oher code.

but i'm not very sure about this... maybe i made some error somewhere...

**Expected behavior**

When i apply the effect i expected to be a passive one instead a temporary one.

**Screenshots**

**Additional context**

**Comment by DFreds** [comment]
Convenient Effect are designed to be temporary effects when they are applied. Passive effects should be tied explicitly to an item or character and not a CE... so I'm not sure this is really a bug.
