### ISSUE TITLE
Incapacitated condition wording is wrong.

### ISSUE THREAD

**Issue by Oshcakes** [DFreds/dfreds-convenient-effects#14]
It says "No movement" but the condition is "An incapacitated creature can’t take actions or reactions."

**Comment by DFreds** [comment]
Great call, thought Incapacitated always meant down, but certain spells can cause you to be incapacitated and still be up. The more you know! I'll fix this in the next patch release

**Comment by DFreds** [comment]
Fixed in v1.5.2
