### ISSUE TITLE
Fix Aid

### ISSUE THREAD

**Issue by GhostwheelX** [DFreds/dfreds-convenient-effects#140]
Aid currently doesn't scale with spell level, could it be changed to have the hp gained be `5 * (max(item level - 1, 2))` or something similar? That way it would still work even if applied as a generic effect, or if a creature casts it.

**Comment by DFreds** [comment]
Yes, this is coming in the integration with midi-qol. However, there isn't a good way to do this when not using midi-qol without prompting for the spell level with a dialog each time, which I'm not sure if I want to do.

**Comment by Bogus73** [comment]
The prompt for choosing spell level would be ok as it alreeady does that for spells that can be upcast. So go for it. Right now it is cumbersome to do and I turned Aid off for now as my players get confused.

**Comment by benbarbour** [comment]
I also vote for a level select prompt (not that this is a democracy ;)). Upcasting is common, and you already have pop-ups for nested effects. In fact, I could probably make a bunch of "Aid <lvl>" custom nested effects, right?

**Comment by DFreds** [comment]
Support for changing HP/temp HP/max HP etc. is being removed from the module. It's too flaky and isn't handled well by active effects
