### ISSUE TITLE
Removing Convenient Effects doesn't remove all Token Magic Effects

### ISSUE THREAD

**Issue by strongpauly** [DFreds/dfreds-convenient-effects#141]
**Describe the bug**
When removing multiple effects with Magic Effects it doesn't remove all the animations.

**To Reproduce**
With ATL, DAE, MidiQol and Token Magic Effects installed:
1. Click on a token
2. Add Fire Shield (Cold Resistance)
3. Add Globe of Invulnerability
4. Click Remove Effects button and remove both effects at once.
5. See error: Only the Globe animation is removed and the fire animation remains.

**Expected behavior**
Both the fire animation and the globe animation should be removed from the token.  

If more than two animations are applied, only one will be removed.  Re-dding the effects and deleting them one by one will fix the issue.

**Comment by DFreds** [comment]
What versions of the mentioned modules do you have?

**Comment by strongpauly** [comment]
These are all my active modules:
<img width="669" alt="Screenshot 2022-03-31 at 10 19 54" src="https://user-images.githubusercontent.com/853954/161010412-ea955179-5cc1-4ed2-9cf7-e27cd67dcd75.png">

**Comment by strongpauly** [comment]
Updating Convenient Effects to v2.5.0 doesn't fix the issue.

**Comment by DFreds** [comment]
Sure, I meant all the modules.

In any case, this isn't a CE issue. It's actually a token magic issue, but tposney (of DAE and midi) was likely able to fix this in dae 0.10.04. Try that

**Comment by strongpauly** [comment]
Can confirm this is fixed in DAE 0.10.04
