### ISSUE TITLE
Conflict between DFreds Convenient effects, and custom condition mapping in Combat Utility Belt

### ISSUE THREAD

**Issue by rtschaefer** [DFreds/dfreds-convenient-effects#142]
Describe the bug
Every time I log back into Foundry VTT, all of my enhanced conditions from Combat Utility Best (CUB) disappear.  I have isolated the module conflict as one of my other top 5 favorite modules... DFreds CE.   I have no idea which module needs to change, but just wanted to communicate this. 

To Reproduce
Log out of the game, then log back in. None of the Custom Condition Mappings are Saved, if/when DFreds CE is loaded.  This does not happen when the game is launched with DFreds CE turned off.

Expected behavior
Saved mapping does what it is supposed to do, and save my customized enhanced conditions.

Environment Info (please complete the following information):

Foundry Version: 9
Game System / Version: dnd5e (I assume the latest version?)
CUB Version 1.8.4
DFreds Version 2.51
Browser: Chrome
OS: Windows 11
Additional context

**Comment by DFreds** [comment]
CUB's enhanced conditions and DFreds CE's modify status effects are not compatible. You choose one or the other: https://github.com/DFreds/dfreds-convenient-effects/wiki/User-Guide#modify-status-effects

**Comment by rtschaefer** [comment]
Thank you! I am incredibly happy to have this resolved. I rely on your module for so many things these days, it is really terrific.  I am not sure how I managed to miss (or forgot?) these details in the user guide, but I learned a lot reading through them now.  Much appreciated sir!
