### ISSUE TITLE
Rage applying too many damage resitances

### ISSUE THREAD

**Issue by BrooksUltra** [DFreds/dfreds-convenient-effects#145]
I have a Path of the Totem Warrior Barbarian in my game who has chosen the Eagle totem for his character.  However, when I apply the Rage condition to his character it adds in all of the Bear totem resistances when he should only have the standard resistance to Bludgeoning, Slashing, and Piercing.

**Comment by DFreds** [comment]
Hm, okay. I am only checking for path of the totem warrior and not bear totem specifically. I'll figure out a solution for that

**Comment by DFreds** [comment]
I'm actually not sure of a good way to do this. Since it isn't part of the core SRD and doesn't have an officially supported method, anything I add might not work in all cases. I'm open for suggestions

**Comment by BrooksUltra** [comment]
Thanks for looking into this.  

Not being super technical I'm not sure what suggestions I could have.  

I'm unsure of what options are available to trigger the condition.  Would it be possible to trigger off a specific named "Active Ability" in the character sheet?  Totem Spirit: Bear ex.  Players could add in a custom active ability if their sheet does not have one to trigger the additional resistances?

Since the additional resistances only apply to a single subset of a single subclass it seems like that is the outlier.  Therefore it might be better to revert the rage resistance back to the standard B/S/P and perhaps add a separate "Path of the Bear Totem" condition that would apply the additional resistances for that subclass?  Or alternatively, a condition to automatically remove the extra resistances to non-Bear paths?

**Comment by DFreds** [comment]
Fixed in v2.7.0. It specifically looks for a feature named "Totem Spirit: Bear". If found, it adds the extra resistances.
