### ISSUE TITLE
Default Token for Players

### ISSUE THREAD

**Issue by NoxDied** [DFreds/dfreds-convenient-effects#146]
It would be nice to allow players to set a default character for effects to apply to. That way if they are trying to add for example, guidance, to their sheet while not on a combat map they could still just click the guidance button and then be able to roll as per normal.

**Comment by DFreds** [comment]
You can actually click and drag any effects straight to the character sheet to have them apply. Not sure if you knew that, but it should fix that issue. I'll consider defaulting to whoever is set as their character though.

**Comment by DFreds** [comment]
Added in v2.6.2
