### ISSUE TITLE
Speed not chaning

### ISSUE THREAD

**Issue by gairiquemero6** [DFreds/dfreds-convenient-effects#147]
When you add an effect that changes speed, it doesn't change.

For example, you add longstrider to a character, and the character still has the base speed. If you add an effect that has multiple stuffs (like Haste), the AC is added but the speed keeps being the same

**Comment by DFreds** [comment]
I can't reproduce this.

Before: 
![image](https://user-images.githubusercontent.com/11878569/169082980-6f5b3edb-69fd-493e-ae1a-1ae8f142f420.png)

After:
![image](https://user-images.githubusercontent.com/11878569/169083060-032cdbe3-41d3-40b2-8501-22c051955476.png)

**Comment by gairiquemero6** [comment]
It happens to me both with monsters or PCs, using the default sheet or a different one.
Before:
![image](https://user-images.githubusercontent.com/105773352/169092070-954f9de5-fa15-4982-a6f4-c76d73db2ce6.png)
After:
![image](https://user-images.githubusercontent.com/105773352/169092144-08ba0ce2-9edc-4b36-b0a0-42cd3edfb498.png)

**Comment by DFreds** [comment]
Can you double check the config sheet for movement? It's possible it's configured wrong due to the actors being old. You can get to the config sheet by hovering over where it says movement.
