### ISSUE TITLE
Adv/Dis on Saving throws or checks

### ISSUE THREAD

**Issue by gairiquemero6** [DFreds/dfreds-convenient-effects#148]
I don't know if it's intended, but if you gain advantage or disadvantage on checks or saving throws, the roll doesn't change. For example, if you use enhance ability and choose Bear's endurance, the token gains the temp hp, but rolls aren't afected

**Comment by thatlonelybugbear** [comment]
DFreds will be the final judge, but I think that it is working as intended. Enhance Ability affects ability checks and not saving throws 🤷

**Comment by thatlonelybugbear** [comment]
Enhance ability should be working only on Abilitiy checks, not saving throws.

Are you using MidiQOL to fastForward rolls? If not, then you should try with the setting on for `Fast Forward Ability Rolls`
![image](https://user-images.githubusercontent.com/7237090/169043593-a2b9f19b-762e-49fa-90e8-ee03e79c5558.png)

And if yes, do you also use Better Rolls? Maybe try without.

Just some input until DFreds picks this up ;)

**Comment by DFreds** [comment]
@thatlonelybugbear correct. You need midi for advantage and disadvantage to actually work, and enhance ability does not affect saving throws.
