### ISSUE TITLE
Duplicate conditions on tokens when Monk's Little Details is installed

### ISSUE THREAD

**Issue by macdhollister** [DFreds/dfreds-convenient-effects#149]
**Describe the bug**
Some conditions are duplicated in the conditions menu on tokens when [Monk's Little Details](https://github.com/ironmonk88/monks-little-details) is installed. There is currently [an open issue](https://github.com/ironmonk88/monks-little-details/issues/127) on that project for the same issue, but I thought it would be good to have one on this side as well. 

**To Reproduce**
1. Activate Monk's Little Details
2. Activate this module
3. Right click on a token and open the "Assign Status Conditions" icon
4. Multiple conditions are duplicated including "blinded", "charmed", "Exhaustion 1-5", "Incapacitated" and others

**Expected behavior**
There should be a single icon per status condition.

**Screenshots**
<img width="593" alt="image" src="https://user-images.githubusercontent.com/19469633/169732166-5f2f0758-b315-468a-b651-dbd8c1f8b512.png">

**Additional context**
Uninstalling either module fixes the issue.

**Comment by DFreds** [comment]
Conditions can only be modified by one module. It's a current limitation in Foundry that I've requested they fix. I'm guessing you have this checked in Monks? 
![image](https://user-images.githubusercontent.com/11878569/170178870-6493ac04-1eed-4084-b19a-69fc661702fc.png)

**Comment by macdhollister** [comment]
I did have it checked but unfortunately unchecking it did not fix the issue.

**Comment by DFreds** [comment]
Then I would guess you must have another module conflicting. Did you refresh your game after disabling the Monks checkbox? The status effects are loaded when the game starts, and can't be updated dynamically. 

In any case, I run both Monk's Little Details and Convenient Effects in my own game without issue. I don't think this is directly a CE issue. It's more of a Foundry thing when manipulating the status effects.

I'm going to close this, but feel free to provide more info about modules you're using and I'll try to help.

**Comment by macdhollister** [comment]
Strange that it doesn't show up for you. Before I made the issue, I had disabled all modules except `DFreds Convenient Effects 2.6.1`, `Monk's Little Details 1.0.49` along with the dependencies `libWrapper 1.12.4.0` and `socketlib 1.0.10`.

**Comment by DFreds** [comment]
Maybe try resetting the status effects? In the CE app, there is a little circular arrow you can click to reset them.

**Comment by macdhollister** [comment]
Fixed it! So there was a combination of issues here, which is why disabling any one module or changing any one setting didn't fix the issue.

After looking into it a little bit more, disabling "Add DnD statuses" _did_ remove some of the duplicates. I also went into the settings for CE and changed "Modify Status Effects" from "Add" to "None". This combination got rid of _most_ of the duplicates. The remainder of them actually did turn out to be caused by a 3rd module; Combat Utility Belt (from its "Enhanced Conditions"). This one is unfortunately a little trickier as it doesn't look like there are any settings to _not_ have it change the effects, and additionally has some with slightly variant names (like "Deafened" rather than "Deaf"). So I'll just have to live with those ones.

Thanks for answering my questions, I really appreciate it!

**Comment by thatlonelybugbear** [comment]
You can turn off Enhanced Conditions in Combat Utility Belt and keep using it for the rest of its functionality.

I mean you would probably use DFreds CE primarily anyways 🤷

**Comment by DFreds** [comment]
Ah, okay, glad you figured it out. As I said, conditions aren't really supported via Foundry to modify... you have to hack it. Hopefully that changes soon. But as @thatlonelybugbear said, CUB's enhanced conditions can be disabled while using everything else from CUB.
