### ISSUE TITLE
Localisation support

### ISSUE THREAD

**Issue by BrotherSharper** [DFreds/dfreds-convenient-effects#15]
Hey there, you have done an amazing job at this module!
I'd like to provide Japanese localisation, do you have any plans to make this module compatible with other languages?

(Some effects like rage check for "Barbarian" in English, and is a bit inconvenient in Japanese)

**Comment by DFreds** [comment]
Yes, I plan to do this soon. Thanks for volunteering to help! I will let you know when I get the initial support in the module.

**Comment by HonzoNebro** [comment]
Yes please! I'd love to write a spanish localization for this amazing module

**Comment by p4535992** [comment]
Hey @DFreds i like to see Internationalization on this module.
**I just wanted to know if you have already started doing something or if I can start from scratch with a new pull request.**
it's something so simple that I should do it too XD

**Comment by DFreds** [comment]
I have not started on this yet. Of note, you cannot localize any of the effect names without breaking the integration with midi-qol. I was thinking of adding an 'id' field to each effect that would be used to apply the effect, but that would require more collaboration with tposney. 

If you want to start though, feel free. I'd appreciate it immensely. You could localize any UI elements or effect descriptions.

**Comment by DFreds** [comment]
Also, if you do start it @p4535992, make the pull request early so I can provide early feedback. Maybe just localize a few elements so I can give any feedback before you do it more times.

**Comment by Padhiver** [comment]
Hello !
Is there any news about translation support ? I am also keen to translate this great tool into French. o/

**Comment by Padhiver** [comment]
Sorry for the late reply, I hadn't seen the message notification. :nerd: 
I've translated the json, but in case Convenient Effect would support translations one day, can I make a pull request or should I keep it aside?

**Comment by lucaspicerni** [comment]
I would like to mention that I am available to provide localization for Brazilian Portuguese!
