### ISSUE TITLE
[Bug] Shield (armor item) applies Shield (magic effect) on targeted token

### ISSUE THREAD

**Issue by Shuggaloaf** [DFreds/dfreds-convenient-effects#150]
**Describe the bug**
Although a rare case I'm sure, if a user has a token targeted and clicks to "roll" a shield armor item, DFCE applies the Shield magical effect to the target. 

**To Reproduce**
Target a token
Click to roll an armor shield

**Expected behavior**
I understand this happens because of the name, and that a workaround is to rename our shields, but ideally this would check for IF item type = "armor" and do nothing.

**Comment by DFreds** [comment]
Are you using midi? CE doesn't do anything with rolling items from the character sheet... Midi does and applies effects from this.

**Comment by Shuggaloaf** [comment]
I am using Midi. I was up in the air about which module's repo to post this issue but the console showed your mod's info so I went with that. ;) will post over there.
