### ISSUE TITLE
No valid manifest file

### ISSUE THREAD

**Issue by simon-fred** [DFreds/dfreds-convenient-effects#151]
**Describe the bug**
When trying to install the module I'm met with the message: "No valid manifest file for ... "

**To Reproduce**
1. Go to 'https://foundryvtt.com/packages/dfreds-convenient-effects'
2. Right click on latest 'Manifest URL' (https://github.com/DFreds/dfreds-convenient-effects/releases/download/v2.6.1/module.json) and copy link.
3. Paste Manifest URL in Install Module and click install.
4. See error.

**Expected behavior**
Expected the module to install. I have also tried other methods of installing (except from downloading the module and manually installing on the server).

**Additional context**
Currently on Foundry version 9 - Build 242

**Comment by DFreds** [comment]
Hmm... Not able to reproduce this. Might have just been a hiccup in github? I would try again, or just use the module browser to install it.
