### ISSUE TITLE
[BUG] Module conflict with DAE

### ISSUE THREAD

**Issue by p4535992** [DFreds/dfreds-convenient-effects#152]
**Describe the bug**

So i add/update a active effect on a token after i retrieve the effect from the list of custom effect of the module.
The first "call" for editing the custom effect is ok , but the second "call" give me a undefined dae flag and a error with the DAE module.

**NOT SURE IF IS A PROBLEM OF THIS MODULE OR DAE**

**To Reproduce**
1. Go to the panel of active effect choose a custom active effect and edit
2. Set a dae effect , for example a "special duration"
3. Do you stuff add/update the active effect on a token
4. Close the panel
5. Re-open the panel
6. Retrieve the same effect and try to edit again, NOW i got a error (screenshot below)
7. Refresh the page with F5
8. NOw i can re-edit the effect

**Expected behavior**

No exception

**Screenshots**

![img0](https://i.imgur.com/kYPR7Ko.png)
![img1](https://i.imgur.com/0IKDK3U.png)
![img2](https://i.imgur.com/xrs3F8r.png)
![img3](https://i.imgur.com/qrMDl5J.png)
![img4](https://i.imgur.com/aRsa4Ti.png)

**Additional context**

I verify this during the testing of the conditional visibility module.

**Comment by DFreds** [comment]
I think I need to double check that DAE didn't change how its flags work. If I didn't need them, I don't set them and that used to be okay. Thanks for bringing it up though.

**Comment by DFreds** [comment]
Is this perhaps an old effect? I can't get it to happen with any new effects... And CV seems to be working fine.

**Comment by p4535992** [comment]
i can't replicate anymore..., maybe DAE is been updated ? 
i'll close the ticket, and i will re-open if i can replicate again,
