### ISSUE TITLE
Effects that include ATL reset token settings

### ISSUE THREAD

**Issue by jorgecomas** [DFreds/dfreds-convenient-effects#153]
**Describe the bug**
Applying an effect that includes active token lighting effects like "Torch" will reset token settings like orientation, size, and others.

**To Reproduce**
1. Drop a token on the canvas.
2. Edit token settings.
3. Apply an effect with ATL like "Torch."
4. See that token settings have reverted to default.

**Expected behavior**
In general, effects should not change unrelated token settings

**Screenshots**
See video.

**Additional context**
The bug is reproducible in a barebones world.

https://user-images.githubusercontent.com/45846011/173259586-ca356841-af08-4b77-b1a5-67ab4c55d17c.mp4

Thanks for this and all your other modules!!

**Comment by DFreds** [comment]
Right.... So that's probably an ATL bug. I just use their flags.
