### ISSUE TITLE
Seperate Controls Permission into Add and Remove to Save Space

### ISSUE THREAD

**Issue by kiligir** [DFreds/dfreds-convenient-effects#157]
I and my players use your Effects Panel mod to delete/disable active effects, and as such have no need for the "Remove Convenient Effects" trash can button under token controls. The "Controls Permission" hides both add and remove, and we definitely still want the add option. Could you separate the "Controls Permission" into "Add Permission" and "Remove Permission"? With 170+ mods installed, the token controls space is at a premium...

**Comment by DFreds** [comment]
Good idea! I can do that

**Comment by DFreds** [comment]
Added in v2.7.0
