### ISSUE TITLE
Effect Stacking with DAE 

### ISSUE THREAD

**Issue by maddox522** [DFreds/dfreds-convenient-effects#158]
When casting spells such as bless and bane etc. in DND 5e the effect gets doubled with DAE. For example bless will apply twice on a tokens rolls. 

The Modify Status Effects setting doesn't seem to change this no matter what is selected.

Any help on this issue?

**Comment by DFreds** [comment]
I think I need more information than this. 

How are you attempting to apply the effect? 
What are your current Convenient Effects settings?
What version of everything?

**Comment by maddox522** [comment]
I figured it out! On Midi QOL there's a setting Apply Convenient Effects, the option apply CE and Item effects causes duplicated Blesses to form, but when set to just apply CE it fixes it.

**Comment by DFreds** [comment]
Ah, okay. I suspected something like that, but didn't have enough info to know. Glad you fixed it!
