### ISSUE TITLE
Can no longer drag condition effects to items

### ISSUE THREAD

**Issue by Ondath** [DFreds/dfreds-convenient-effects#159]
**Bug Description**
Previous versions of the module allowed conditions from the Add Convenient Effect list to be added to items via drag-and-drop. Since 2.7.0, this function no longer works (presumably due to changes with how the module interacts with drag-and-drop to the hotbar).

**To Reproduce**
1. Create a custom item that will apply an effect to a target
2. Open the custom item's Effects tab
3. Click on 'Add Convenient Effects' on the left-hand menu.
4. Click and drag a condition effect to the custom item's Effects tab
6. See error

**Expected behavior**
The dragged condition effect should have been added to the item with the item's duration reproduced (this functionality works in 2.6.3).

**Screenshots**
![image](https://user-images.githubusercontent.com/109798782/180423952-a29187e2-13a5-43d3-b92d-5742a6b0c136.png)

**Comment by DFreds** [comment]
The previous version had a bug when dragging them to the macro bar that created the dnd5e version of a macro which was fixed. This is a side effect. I'll see if I can find a work around

**Comment by horusofoz** [comment]
Having updated to latest 2.7.1, I've found I can no longer drag items onto the hot bar. Disabling DCE module fixes issue.

**Comment by DFreds** [comment]
Yeah, 2.7.2 fixes this. My fault
