### ISSUE TITLE
Minor Bug in Bullseye Lantern effect

### ISSUE THREAD

**Issue by Fridan99** [DFreds/dfreds-convenient-effects#160]
CE version 2.7.2

**Describe the bug**
The Bullseye Lantern has a minor bug in the DAE effect.

ATL.light.bright **60** instead of 30
ATL.light.dim **120** instead of 60

**Acording to PHB pg 152,** 

_A bullseye lantern casts bright light in a 60-foot cone and dim light for an additional 60 feet. Once lit, it burns for 6 hours on a flask (1 pint) of oil._
(That's a total of 120ft of light "60ft bright light and another 60ft of dim light, which for practical purposes in the dim light configuration should be set to 120). 

**Screenshot (a custom copy directly from the original CE)**

![Bullseye Lantern](https://user-images.githubusercontent.com/86131373/181866615-d0cbbb91-f008-4e2c-9415-d47914ed14b4.jpg)

**Comment by DFreds** [comment]
Nice, good catch. I'll fix it

**Comment by DFreds** [comment]
Fixed in v2.7.3
