### ISSUE TITLE
Ability to hide effect application based on roll mode

### ISSUE THREAD

**Issue by The-BirdGod** [DFreds/dfreds-convenient-effects#162]
**Is your feature request related to a problem? Please describe.**
I would like to hide effects from off-screen so my players aren't tipped off when something drops on an enemy that they aren't fighting at the moment.

**Describe the solution you'd like**
Effect application outputs to chat based on the selected roll mode (Public/Private/Blind)

**Describe alternatives you've considered**
Not sure what alternatives could be done for this, but I'm all ears.

**Additional context**
None, great module!

**Comment by DFreds** [comment]
Seems easy enough. Good suggestion!

**Comment by The-BirdGod** [comment]
Looks like it's already in the module and I didn't see the option (unless this was added since I posted)!
My fault (or thank you!)

![image](https://user-images.githubusercontent.com/110910890/184492879-738b1610-aa37-468f-84fd-b3dc435fc7d8.png)

**Comment by DFreds** [comment]
That's been there, but it might be nice to control it via the normal chat commands. Still a good suggestion!
