### ISSUE TITLE
[Feature Request] Generic Exhaustion Condition

### ISSUE THREAD

**Issue by GhostwheelX** [DFreds/dfreds-convenient-effects#164]
Might it be possible to add a generic Exhaustion condition? Right now it's easy to apply a specific level of exhaustion, but I think it could be useful to have a general exhaustion level condition which increments the level of exhaustion already applied to the target.

**Comment by DFreds** [comment]
Hey, thanks for the suggestion. Anytime exhaustion is added, all other exhaustions are first removed. This suggestion would only be a minor upgrade on that workflow and only for certain use cases, so I don't think I'm going to do it. Thanks for the idea though!

**Comment by GhostwheelX** [comment]
How would that work with something like the Sickening Radiance which increments the level of exhaustion by one? Is there a way to automate that with Convenient Effects?

**Comment by DFreds** [comment]
Never really considered that. There is no way to automate that without a macro. There would also be no way to automate that without a macro even if there was a way to increment exhaustion... It just might be easier.
