### ISSUE TITLE
Icons missing for effects in v10/dnd5e 2.0+

### ISSUE THREAD

**Issue by strongpauly** [DFreds/dfreds-convenient-effects#167]
**Describe the bug**
dnd5e icons referenced by this module have been moved into core foundry and removed in dnd5e version [2.0.1](https://github.com/foundryvtt/dnd5e/releases/tag/release-2.0.1).  

**To Reproduce**
1. Install module in v10
2. Open window

**Expected behavior**
All icons should be present

**Comment by strongpauly** [comment]
Should be simple enough to map to the new locations, I don't mind having a go.  Can create a PR soon.

**Comment by DFreds** [comment]
This is fixed in my v10 branch that will go out later today
