### ISSUE TITLE
[Feature request] Drag and drop to the hotbar, and Help Action (In Combat)

### ISSUE THREAD

**Issue by Fridan99** [DFreds/dfreds-convenient-effects#171]
**Is your feature request related to a problem? Please describe.**
NO.

**Describe the solution you'd like**
**Suggestion 1**. I think it would be useful to be able to drag and drop the ECs to the hotbar. Some of them tend to be of daily use, and that would speed up the application of the most used ones. For example, I currently have a custom Help Action, and it would be faster if it could be done from the hotbar. There are probably other effects that would be useful to have in the hotbar. 

**Suggestion 2**. I noticed that you don't have in the base CE the Help Action, that maybe should be in the Other field (like dodge, ready, etc...)
 
**Help (In Combat)**
Special duration: Is Attacked: Expires if the character is attacked
flags.midi-qol.grants.advantage.attack.all    add    1

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by DFreds** [comment]
Hi, you can already drag and drop effects from the CE app to the hotbar.

Also, the Help action seems a little more generic than that, as it can be used outside of combat as well for other checks. In any case, you can create your own custom effect that should meet your needs for it.
