### ISSUE TITLE
[Strangeness] Module doesn't appear after installation

### ISSUE THREAD

**Issue by JohanFalt** [DFreds/dfreds-convenient-effects#172]
I install DFreds Convenient Effects (v3.0.1) through Foundry (V10) Add-on Modules

Only have libWrapper (v1.12.10.0) and socketlib (v1.0.11) as other modules.
Starts World with my custom System I have made. Only libWrapper and sockelib activated as modules in the world.

As I go to activate DFreds Convenient Effects it is not listed as an installed module only the other two are.

The extra buttons are not visible according to the manual so it is clearly not active.

So my question is - are there a requirment in a system in some way or is there another way I can search for what is wrong?
F12 doesn't state anything.

**Comment by DFreds** [comment]
This is currently only supported for dnd5e. Hopefully not the case soon
