### ISSUE TITLE
Module not working on latest V10 Build 288

### ISSUE THREAD

**Issue by Angelixus** [DFreds/dfreds-convenient-effects#176]
**Describe the bug**
I'm on V10 build 288, the module is updated to V10 but just until 10.286. Whenever I try to use an effect on a token using the module UI, an error occurs, it tries to read the property `actor` from the `token` but such property is null (this line of code is at line 30 of `foundry-helpers.js`).

I don't know if this is because of build 288 that changed the property or it is a bug from the module.

**Comment by bsan89** [comment]
I can confirm. Causing the game to freeze whenever convenient effect is being use. v10 build 288

**Comment by DFreds** [comment]
That's not ideal. I'll check it out

**Comment by DFreds** [comment]
I can't seem to reproduce this. Can you provide more detailed steps you're taking and also make sure that only CE and libWrapper are enabled? It appears to hit this code and work as expected in my tests. It's basically impossible for token to be null when you do this map over the ones you are controlling: `canvas.tokens.controlled.map((token) => token.actor.uuid);`

Maybe it's a screwed up actor? Foundry sometimes has issues with actors created in older version of Foundry. Try it with a new on if that is the case

**Comment by Angelixus** [comment]
@DFreds thanks for the response, it now seems to be working under the same circunstancias it failed me before, I don't really know why but it is working as expected, I close the issue
