### ISSUE TITLE
applying GWM and Rage in this order does concatenate damage

### ISSUE THREAD

**Issue by itteerde** [DFreds/dfreds-convenient-effects#177]
**Describe the bug**
Applying GWM and Rage in this order does concatenate instead of summing up the damage.

**To Reproduce**
1. Select a Barbarian Actor Token
2. Go to DFreds Convenient Effects
2. Click on GWM
3. Click on Rage
4. Attack
5. read damage

**Expected behavior**
sum damage as does happen if you click Rage and then GWM instead of GWM and then Rage. Think the GWM definition is wrong as it alone has a suspicious ++10 in it.

![Screenshot 2022-10-17 161650](https://user-images.githubusercontent.com/8367477/196202544-69b25221-5890-4a23-b5ea-1ac3c254c02e.png)

**Comment by DFreds** [comment]
You mean you don't want your barbarian doing 100+ damage? Huh. But seriously, good find. I'll fix it

**Comment by DFreds** [comment]
Fixed in the next release
