### ISSUE TITLE
Dropping an effect into any text editor creates a broken link.

### ISSUE THREAD

**Issue by oWave** [DFreds/dfreds-convenient-effects#178]
**Describe the bug**
Dropping a convenient effect into any text (journal page, item description, etc.) creates a broken document link: `@UUID[ActiveEffect.]{undefined}`. Saving that text causes that text to appear blank and can no longer be edited (and the item can no longer be rolled).
Here's the error that appears in the console when attempting to edit a text containing a broken link:
```
TypeError: An error occurred while rendering ItemSheet5e 59. can't access property "instance", CONFIG[documentName].collection is undefined
[Detected 1 package: system:dnd5e]
    _parseUuid foundry.js:4151
    fromUuid foundry.js:4081
    _createContentLink foundry.js:56860
    _enrichContentLinks foundry.js:56636
    _replaceTextContent foundry.js:56787
    _enrichContentLinks foundry.js:56636
    enrich foundry.js:56609
    enrichHTML foundry.js:56614
    getData item-sheet.mjs:79
    _render foundry.js:5067
    _render foundry.js:5780
    render foundry.js:5026
    render foundry.js:6352
    render foundry.js:13275
    _onUpdate foundry.js:13377
    callback foundry.js:12766
    documents foundry.js:12747
    _handleUpdateEmbeddedDocuments foundry.js:12747
    _updateEmbeddedDocuments foundry.js:12625
    update commons.js:6770
    updateDocuments commons.js:6128
    update commons.js:6225
    _updateObject foundry.js:6505
    _onSubmit foundry.js:5874
    _onSubmit item-sheet.mjs:644
    saveEditor foundry.js:6021
    onSave item-sheet.mjs:368
    _handleSave prosemirror.js:16315
    _onAction prosemirror.js:16288
    onclick prosemirror.js:15841
    activateListeners prosemirror.js:15841
    activateListeners prosemirror.js:15841
    render prosemirror.js:15830
    update prosemirror.js:15857
    updatePluginViews prosemirror.js:11553
    updateStateInner prosemirror.js:11502
    updateState prosemirror.js:11437
    dispatch prosemirror.js:11732
    _onDrop prosemirror.js:18234
    promise callback*_onDrop prosemirror.js:18229
    drop prosemirror.js:9936
    someProp prosemirror.js:11570
    drop prosemirror.js:9936
    event prosemirror.js:9323
    initInput prosemirror.js:9320
foundry.js:747:30
```

**To Reproduce**
1. Create an item or journal page
2. Drag a convenient effect into the text editor

**Expected behavior**
A proper link to the effect should appear in the text.
I wanted to see if dropping that link onto a token when it appears in the chat would work, but I can create a feature request if that isn't the intended behavior (yet).

**Additional context**
Versions:
* Foundry V10 Build 288
* DnD5e 2.0.3
* libWrapper 1.12.10.0
* socketlib 1.0.12
* Convenient Effects 3.0.2

**Comment by DFreds** [comment]
This isn't really a fixable thing at the moment. Foundry doesn't support ActiveEffects living as their own entity. They have to be attached to an Item or an Actor. When they aren't (like in the CE app), it causes issues when you drag and drop it onto the journal since there is no origin of the ActiveEffect.
