### ISSUE TITLE
Longstrider applies to all speeds

### ISSUE THREAD

**Issue by krysztalzg** [DFreds/dfreds-convenient-effects#18]
**Describe the bug**
Longstrider effect should be applied to all speeds, not only walking speed.

**Comment by DFreds** [comment]
This seems like it is up for interpretation, but I interpreted longstrider to only add a bonus to movements you have. For instance, why would longstrider suddenly give you +10 fly speed? That doesn't make any sense to me. However, if you already have +30 fly speed, then yes, now you have +40.

Based on my interpretation, this is working correctly.
