### ISSUE TITLE
Rage Attack Bonus isn't working

### ISSUE THREAD

**Issue by Beardface123** [DFreds/dfreds-convenient-effects#180]
When applying rage, I'm not getting the appropriate damage bonus for strength based attacks.  Here is the configuration for the rage bonus.
![unknown](https://user-images.githubusercontent.com/19542977/198886539-373d6ee8-c230-48ab-84b5-f27692af46a8.png)

Here is the resulting attack from a lvl 9 barbarian (I would expect to see +3, not +0)
![unknown](https://user-images.githubusercontent.com/19542977/198886586-378495dd-adf4-4b31-9019-b953b8e70225.png)

If this is a simple attribute change or adjustment please let me know.  Thanks for all you do, this module is great!

**Comment by thatlonelybugbear** [comment]
Check you rage scale in the Barbarian class advancement. 

There was an issue some time ago with DnD Beyond imports having a wrong identifier.

**Comment by Beardface123** [comment]
Got it.  Instead of `@scale.barbarian.rage-damage` it was supposed to be `@scale.barbarian.rage`

This is fixed, thank you
