### ISSUE TITLE
Effects added in v9 migrated worlds have expire time always added as rounds, not as seconds

### ISSUE THREAD

**Issue by STBaf** [DFreds/dfreds-convenient-effects#181]
Description:
If you have a v9 migrated world every effect out of the Dfreds convenient effects is added with a expire type of rounds, not with seconds. For example: If you attach "Bless" to a actor, which has a expiry of 3600 seconds, it is added with 600 rounds (guessing every D&D5 round is 6 seconds, the timespan is right, but it es counted as rounds, not as seconds). The problem with this is, that, if it is added as rounds and not in seconds, the Effect is not counted done if you are not in combat and, in the best, expire, but does not get deleted by other modules like TimesUp. You need to have a very close eye on every effect if it is already expired while, in v9, when the time has come, it was automatically removed by additional modules like TimesUp.
This seem not to happen on worlds that are generated in v10 freshly. If you do the same in a fresh v10 world then it is added with seconds, not with rounds, as it is intended.

1. Take v9 DnD5e world
2. Migrate to v10.288
3. Enabled Dfreds-Convenient-Effect in the migrated world (+ needed dependencies, for sure)
4. Add Effect to actor by DCE with a second-based expire, see that it is added as rounds.
5. Go back to administration
6. create fresh DnD5e world
7. enable DCE here again
8. add scene/add actor as needed
9. repeat step 4 in the v10, adding a second base effect to actor, see it is added as seconds correctly

Expected behavior:
In v9 migrated worlds effects with second based expiry should be added with second based expiry, too, like in v10 newly created worlds since, if based on rounds, follow-up mechanics like auto-remove through TimesUp gets broken if you are not in a combat situation.

Screenshots:
Demo video is here: https://www.stbaf.de/foundry/dfredce.mp4

Additional:
A non-migrated v9 version and a already migrated v10 version of a test world was provided to DFred through Discord DM.

**Comment by STBaf** [comment]
Just as question (no pressure): Any guessed when the problem might be addressed ? so for my personal "when I times update to v10" planning ?

**Comment by STBaf** [comment]
Did a litter further search on my own in your code and found the reason for this behaviour: The following line of code in the getDuration function make a difference between combats and non combats (adding the effect as seconds or rounds) https://github.com/DFreds/dfreds-convenient-effects/blob/main/scripts/effects/effect.js#L102

After taking another look at the world I had seen that there were 4 combats existing after the migration in the world which, just to mention, not there in v9. I think there maybe some data in v9 which was ignored and now brought back up after migration.
In the end I just deleted to appeared 4 combats and after hat the Convenient Effects module started to behave normal and added effects as seconds to end instead of rounds. This is the same behaviour as in v9, then.
Seems thats more a "combats may appear after migration" problem then a problem with this module, so I think we should close this issue.

**Comment by DFreds** [comment]
Thanks for the update!
