### ISSUE TITLE
Bardic Inspiration effects not transferring

### ISSUE THREAD

**Issue by FreshnessDND** [DFreds/dfreds-convenient-effects#182]
Bardic Inspiration will work when using CE Panel to transfer effect to actor.

It will not work when using Bardic Inspiration feature from actor menu to transfer onto another actor.

The menu pops up as normal allowing selection. It then goes through proper workflow to place the effect on the targeted actor (Midi). Unfortunately, none of the effects actually transferred just the icon and ID.

This is an issue with nested effects as they all have the same problem. Others that are not nested work just fine.

Could be an issue with Midi, so I can forward this.

10.288
2.0.3

**Comment by DFreds** [comment]
I think this is likely a midi bug. Recommend forwarding it to that module's repo

**Comment by DFreds** [comment]
Fixed in next release
