### ISSUE TITLE
Request: Compatablility with Multi Token Status module

### ISSUE THREAD

**Issue by pesky-wobbit** [DFreds/dfreds-convenient-effects#183]
**Is your feature request related to a problem? Please describe.**
Compatibility with Multi Token Status so I can update the status for several tokens at once.

**Describe the solution you'd like**
Chain the wrapper for 'TokenHUD.prototype._onToggleEffect'? I'm basing this suggestion on the attached error below.

**Describe alternatives you've considered**
Author of Multi Token Status can do something?

**Additional context**
Here is a pic of the error
![Screenshot 2022-11-09 094051-status-conflict](https://user-images.githubusercontent.com/477446/200860970-bb62c287-a344-44f8-8074-46f47a7f294f.jpg)

**Comment by DFreds** [comment]
This isn't something I can reasonably do and have everything work. I already chain the wrapper if you toggle a non-CE, but if I chain while toggling a CE it causes the effect to be applied several times.
