### ISSUE TITLE
Spells not applying the active effect automatically

### ISSUE THREAD

**Issue by YenBenGrey** [DFreds/dfreds-convenient-effects#184]
**Describe the bug**
Anyone know anything about a problem with Dfreds or Midi? When I am casting a spell the active effect isn't being auto applied to the token. e.g. Mage Armour, no icon on the token and no increase in AC.

Yet when I apply direct from DFreds CE it is being applied. 
All the correct settings are set in DFreds and Midi. (In fact I haven't changed any settings and it was working perfectly well yesterday) 

Nothing in console and FTC isn't revealing anything.

**Comment by YenBenGrey** [comment]
I made a mistake

**Comment by BeeJayJayn** [comment]
I'm currently encountering the same behaviour, would you mind sharing your mistake and solution? @YenBenGrey

**Comment by YenBenGrey** [comment]
> I'm currently encountering the same behaviour, would you mind sharing your mistake and solution? @YenBenGrey

Crikey this is a few weeks ago. I’ll struggle to remember. I’ll have a look later and respond.

**Comment by DFreds** [comment]
I assume it either some midi setting that is missing or the spell itself has the "Do not apply CE" checkbox set in its details. It could also be a midi issue, but I doubt it.

@BeeJayJayn Can you send a screenshot of your workflow settings in midi? And maybe of the item itself?

**Comment by YenBenGrey** [comment]
Genuinely cannot remember what I did wrong. It was definitely user error (me) rather than a technical error. If I remember I’ll be back.
