### ISSUE TITLE
Add the Invisible Condition to the Invisibility and Greater Invisibility Spell effects

### ISSUE THREAD

**Issue by YenBenGrey** [DFreds/dfreds-convenient-effects#185]
Is it possible to add the CE Invisible to the Invisibility and Greater Invisibility Effects so that when the spell is cast the recipient actually becomes invisible please? As per the effect.
In V10 when the effect is applied the token actually becomes invisible to other tokens.

That would be great :-)

**Comment by DFreds** [comment]
Fixed in the next version
