### ISSUE TITLE
Request: Capability to EDIT default effects and folders

### ISSUE THREAD

**Issue by DMedianoche** [DFreds/dfreds-convenient-effects#188]
I would appreciate to have the possibility to modify the DEFAULT effects (like Shield of Fate) without having to manually modify the .json data from the core files. Also to create NEW folders and reorganize the effects as needed.

As stated before, this can be done manually and can be backed up when updating the module and restored later.

**Comment by DFreds** [comment]
You can duplicate default effects by right clicking them. As long as you keep the same name, the custom effect will always be chosen over the default effect.

Creating folders is an enhancement that I would like to do, but haven't gotten to yet.

**Comment by FuriousMeatballs** [comment]
I know this is almost a year old but I'd like to ask for the same thing. I don't like how my custom folder is cluttered with duplicate conditions

**Comment by BlackBadger777** [comment]
I'd like to second this. The ability to add folders in the custom section would be a real game-changer in the way I could use this module. Right now, I'm keeping my custom effects to a bare minimum to avoid clutter in the one folder they can be stored in. This led to me re-creating effects I had already done in the past when I needed them again. Being able to store effects in folders would add huge qol to my workflow.

**Comment by DFreds** [comment]
See #73 which will be worked on. Otherwise, no editing of default effects will be implemented for now
