### ISSUE TITLE
Update ATE changes for v10

### ISSUE THREAD

**Issue by kaelad02** [DFreds/dfreds-convenient-effects#189]
We need to update some of the ATE effects based on changes from v10. The official release of a v10-compatible version of ATE is out on the repo, https://github.com/kandashi/Active-Token-Lighting/releases/tag/0.5.0 . The Foundry listing will be updated soon.

At the bare minimum, we need to account for some simple key changes:
- `ATL.sightAngle` => `ATL.sight.angle`
- `ATL.vision` => `ATL.sight.enabled`

We can also use v10's new Vision Modes and Detection Modes. For example, the Darkvision spell can now enable the vision mode with `ATL.sight.visionMode | Override | darkvision`. I don't see any existing conditions that could use the detection modes, but if there was a blindsight it could be done with `ATL.detectionModes.seeAll.range | Upgrade | 10`.

I'm willing to make a PR for it, to help out.

### Upgrading dimSight

I started looking into making the code changes but there is one thing tripping me up. It's an easy change to update the `_createAtlEffectKey` function for the simple key changes but there's two that aren't as easy: `ATL.dimSight` and `ATL.brightSight`. The upgrade for those ones are more complicated since they are merged into `ATL.sight.range` and they set `ATL.sight.brightness`. You can see that here:

https://github.com/kandashi/Active-Token-Lighting/blob/0.5.0/src/updateManager.js#L297-L310

Darkvision is the only one that uses either of those old keys. Since we'd also want to add the vision mode change here I'm guessing it's fine to also tweak it to set both `ATL.sight.range` and `ATL.sight.brightness`. What do you think?

**Comment by DFreds** [comment]
That should all be fine. If you want to make the PR, feel free. I'll review it/leave comments if need be. Otherwise, I can probably get to it within the next day or so

**Comment by DFreds** [comment]
Also, thanks for bringing all this up in such a detailed way. Makes it easier!

**Comment by kaelad02** [comment]
I submitted #191 for this
