### ISSUE TITLE
[Feature Request] Hide specific effects from players

### ISSUE THREAD

**Issue by GhostwheelX** [DFreds/dfreds-convenient-effects#190]
Might it be possible to add a toggle that hides specific effects, especially custom ones, from players?

**Comment by DFreds** [comment]
Do you mean hide on top of their token or hide in their character sheet? Passive effects are automatically hidden on the token, but nothing in CE is considered a passive effect. Either way (unless I'm misunderstanding), hiding an effect would take some unrelated code that I think falls out of the scope of this module. Might make for a good separate module though

**Comment by GhostwheelX** [comment]
I meant hide from the list of convenient effects available to choose from when you open the Convenient Effects menu on the toolbar on the left of the Foundry canvas.

**Comment by DFreds** [comment]
Oh, interesting. Yeah, I could probably do that

**Comment by LukasPrism** [comment]
Just came here to ask this... we have some custom ones that would be great as GM-only (eg for resizing tokens). Could even weed out some players shouldn't be touching (eg Dead condition) so the GM has them in the HUD but players don't. Perhaps add a right-click option in the panel for 'GM only'?

**Comment by DFreds** [comment]
Added in v7.0.0
