### ISSUE TITLE
Invisible effect should utilize Foundry v10's Invisibility vs Sight modes

### ISSUE THREAD

**Issue by GambetTV** [DFreds/dfreds-convenient-effects#192]
In your module settings I like to have "Modify Status Effects" set to Replace, so that I don't have a bunch of duplicates. Unfortunately in v10 Foundry made the Invisible status effect actually turn the token invisible to tokens that don't have some of the Detection Modes activated, such as See Invisibility. Your Invisible status seems to just add the icon to their token, with advantage/disadvantage added to their effects. It would be great if you could incorporate the two together.

**Comment by DFreds** [comment]
It does do this. I'm confused what you mean? This is with status effects set to replace in Foundry v10.

Left is GM, right is player

![image](https://user-images.githubusercontent.com/11878569/203453467-3fc15af5-4e45-482f-a91d-bc4c7bec6174.png)

Token vision needs to be enabled on the scene, and both tokens have vision enabled and mode set to basic vision.

**Comment by GambetTV** [comment]
That's odd. May have been a temporary bug on my end? I tried it several times earlier and it didn't work, but now it seems to. Sorry!
