### ISSUE TITLE
Merge Custom Effect list on import instead of Replacing it

### ISSUE THREAD

**Issue by That-Italian-Guy** [DFreds/dfreds-convenient-effects#194]
**Issue**: if I have two worlds, each with its own list of Custom Effects, I can't easily import the effects from world A into B or viceversa without overwriting the existing custom effects.

**Expected Behavior**: if I export the custom effect list from world A and I import it into world B, I would like the two list to be merged together instead.

**Describe alternatives you've considered**
[#136](https://github.com/DFreds/dfreds-convenient-effects/issues/136) could also alleviate the issue, althoug it would still be painful if the list of effects to be imported is large.

**Comment by DFreds** [comment]
Hm, I thought it should be doing this already. It's possible something has broken here. Can you export both of your custom effect JSONs and attach them here?
