### ISSUE TITLE
Rage Damage coming out as 0

### ISSUE THREAD

**Issue by Avitale34** [DFreds/dfreds-convenient-effects#197]
Hello I have a barbarian in one of my games who does not seem to be getting the damage bonus from the rage effect. I looked at the effect and included a pic below showing it has @scale damage formula in there but don't know why it would be coming out as 0.

![image](https://user-images.githubusercontent.com/65961637/207127981-76980102-7e6a-481f-99bd-1d26fd7dd770.png)
![image](https://user-images.githubusercontent.com/65961637/207128032-779c8cba-d814-478a-82b6-985a8940ac81.png)

**Comment by DFreds** [comment]
Is it set correctly on the barbarian class? I think this can happen if the barbarian existed in an older version of the dnd5e system before this was added. Here is what a new barbarian looks like:

![image](https://user-images.githubusercontent.com/11878569/207472254-edae4372-a1f3-47db-9f38-31f9739f8b97.png)
