### ISSUE TITLE
False Life is doing things it shouldn't

### ISSUE THREAD

**Issue by MotoMoto1234** [DFreds/dfreds-convenient-effects#198]
**Describe the bug**
Active effects should not modify temp hp or actual hp.  This spell in dfreds CE is on the surface a basic blank active effect that simply puts an image buff icon on the token.  However, something in the background in the module is having it also apply temp hp, and then having it take the temp hp away when the dfreds CE is removed.  It never upcasts, and if the item that is rolled is set to upcast, the dfreds CE overrides it back down to level 1.  My suggestion is to remove it from the list.  False life only needs a buff icon, the temp heal is done in the item.  

**To Reproduce**
1. toggle dfreds CE for False life on and off and observe temp hp field.  

**Expected behavior**
I would just remove it from the premade list entirely, theres no real way to pull its spell effect off in an active effect unless it was a macro synthetically applying temp hp, see something like heroism in Midi srd for an idea.  

**Screenshots**

**Additional context**
The addtional reason why this methid is especially bad, is because the rules on temp hp is that the higher value takes precedent.  If you give a monster 50 temp hp, and then toggle on and off dfreds CE version of false life, it erases/overwrites the 50 temp hp.

**Comment by DFreds** [comment]
Yeah, this is probably the correct solution. There are a few things that affect actors in some way by changing their HP or temp HP, but I could probably remove all of them so nothing weird or unexpected happens.

**Comment by DFreds** [comment]
Removed in v3.2.0
