### ISSUE TITLE
Expanding the arguments for effects toggle macro

### ISSUE THREAD

**Issue by thatlonelybugbear** [DFreds/dfreds-convenient-effects#20]
**Is your feature request related to a problem? Please describe.**
Using name argument is useful, but when targeting unlinked tokens the effect will be toggled on all tokens with the same name on the canvas.

**Describe the solution you'd like**
Make use of something like `tokenId` for targeting specific tokens only via macros.

This will also make it easier to add and remove convenient effects, when using a combination of Midi-QOL, DAE, Item Macro and DFreds Convenient Effects.

A small example for a Haste spell with a convenient effect.

Create a DAE on the spell to execute a `macro.itemMacro`

Item Macro
```javascript
const lastArg = args[args.length - 1];
let tactor;
if (lastArg.tokenId) tactor = canvas.tokens.get(lastArg.tokenId).actor;
else tactor = game.actors.get(lastArg.actorId);

const target = canvas.tokens.get(lastArg.tokenId);
const targetId = target.data._id;

const ef1 = game.dfreds.effects._haste.name

if (args[0] === "on") { 
game.dfreds.effectHandler.toggleEffect(`${ef1}`,`${targetId}`);
} 

if (args[0] === "off") {
game.dfreds.effectHandler.toggleEffect(`${ef1}`, ${targetId}`);
}

**Comment by DFreds** [comment]
Fixed in v1.6.1 as far as I understand how your use case works. You can now pass in token IDs instead of names and it should apply to them. Please reopen if it doesn't meet your needs
