### ISSUE TITLE
Adding Exhaustion to the character sheet

### ISSUE THREAD

**Issue by LukasPrism** [DFreds/dfreds-convenient-effects#203]
Hiya

Just logging this here per your request. Popping this in the AE will also keep the character sheet in sync with the CE:

<img width="823" alt="Screenshot 2022-12-30 at 5 28 22 PM" src="https://user-images.githubusercontent.com/104886594/210034622-0e95aeee-7006-41af-af62-2015a51fb2d9.png">

Love your work! Cheers

**Comment by DFreds** [comment]
Added in v3.1.1
