### ISSUE TITLE
Compatibility with modules other than Midi-QOL

### ISSUE THREAD

**Issue by teroparvinen** [DFreds/dfreds-convenient-effects#204]
Some users of WIRE (https://foundryvtt.com/packages/wire) have asked me about better CE support. I have also had some support requests that have been about confusion between WIRE spells and the spells listed in CE. I recommend CE for use with WIRE because it is both flexible and user friendly in how it allows users to control available conditions and it works 90% of the time because WIRE tries to support Midi flags where it can.

I'd like to provide support for WIRE specifically, and that could be either through alternative WIRE data delivered as part of CE or WIRE being able to override things provided by default by CE. Would one of these be more suitable?

As mentioned, it is mostly confusing to WIRE users that CE contains spells and class abilities as the intent with WIRE is to get them through dedicated compendia. So it would be nice to be able to customize the list of folders as well as the conditions themselves.

If WIRE could be made to provide the lists, would it be possible to include APIs in CE to do the following?

- Customise the folders available in CE
- Provide a custom list of conditions/effects listed in each folder

**Comment by DFreds** [comment]
Related to #73 and #107
