### ISSUE TITLE
Invisible condition is not removed when Invisibility is removed

### ISSUE THREAD

**Issue by mrjlaforest** [DFreds/dfreds-convenient-effects#205]
**Describe the bug**
Invisible condition is not removed when Invisibility is removed.  

**To Reproduce**
1. Have character cast invisibility on self. Invisibility and invisible are both applied correctly.
2. Target an enemy and attack.  Invisibility effect drops, but conditions "Invisible" and "Concentrating" are not removed.  

Alternately - casting invisibility on another creature has same issue.  Not sure if removing "Invisible" from other creature and "Concentrating" from original caster is a complication.  At minimum, removing "Invisible" status would be enough.

**Comment by DFreds** [comment]
Fixed in v3.1.1
