### ISSUE TITLE
Rage does not apply correct Resistances to Bear Totem

### ISSUE THREAD

**Issue by gravagehulk** [DFreds/dfreds-convenient-effects#208]
I swear this used to work, but it doesn't appear to now.

I saw the closed issue where you stated that it looks for "Totem Spirit: Bear". I have created a feature for that manually and tried different combinations of caps/lower case, spacing, etc. Nothing seems to work. No matter what I do, applying the Rage condition to a Totem Bear barbarian only applies the standard resistances. 

Foundry version: 10, build 291
DnD5e 2.1.2
Dfreds 3.1.1

I did create a manual rage effect with all of the resistances, so I know I can work around this. I was just wondering if there was a reason that the automatic detection wasn't working. Thanks.

**Comment by DFreds** [comment]
The barbarian also needs to belong to the path of the totem warrior. It checks for both.

![image](https://user-images.githubusercontent.com/11878569/214215710-beca2064-28ef-4914-a475-1b22b672d021.png)
