### ISSUE TITLE
5e Condition Issues

### ISSUE THREAD

**Issue by GhostwheelX** [DFreds/dfreds-convenient-effects#21]
Things I noticed that can be fixed:

- Dodging: Does not grant advantage on Dexterity saves
- Paralyzed: Does not auto-crit on melee spell attacks.
- Prone: Does not apply disadvantage on all attacks made by the prone creature.
- Unconscious: Should also apply the paralyzed and prone conditions while active.

Also not an error, but in regards to movement-related effects, it might be easier to have `data.attributes.movement.all` have an effect of `*0.5` (for Exhaustion 2, for example) instead of doing each movement style individually.

**Comment by GhostwheelX** [comment]
Could you also please add Blade Ward to the list of spells? Thanks :-)

**Comment by DFreds** [comment]
These should all be addressed in v1.6.1. Blade Ward will be added in the next release

**Comment by DFreds** [comment]
Turns out blade ward is not part of the SRD, and therefore cannot be added to this module. Bummer. But I am slowly adding the ability to create your own effects, and then you could replicate it. So sorry, blade ward won't be in the next release!
