### ISSUE TITLE
Effect Description box for other active effects

### ISSUE THREAD

**Issue by FurtherV** [DFreds/dfreds-convenient-effects#211]
A way to specify effect descriptions for active effects applied by item / on items would be nice.
Currently it is only possible to edit the effect description for the effects present in the CE menu.

Adding this feature would also enhance your effect panel module, since then one can view custom descriptions for all
effects in FoundryVTT.

**Comment by DFreds** [comment]
Yeah, great idea! Will add

**Comment by DFreds** [comment]
Will be added in the next release
