### ISSUE TITLE
Bardic Inspiration - stopped working.

### ISSUE THREAD

**Issue by Altrix1** [DFreds/dfreds-convenient-effects#212]
"Bardic Inspiration" stopped working.

Caused by Midi-QOL update?

<img width="362" alt="image" src="https://user-images.githubusercontent.com/86872105/217329782-3a1d6f00-d920-4418-9fbf-0d43ec0c8964.png">

<img width="296" alt="image" src="https://user-images.githubusercontent.com/86872105/217330196-627df353-5989-4376-8456-6b624f3b7584.png">

**Comment by Altrix1** [comment]
the latest Midi-QOL update - fixes it

**Comment by DFreds** [comment]
Ah, okay. Glad it's fixed!
