### ISSUE TITLE
Request: Custom Enriched Text for CE functions from chat/journals

### ISSUE THREAD

**Issue by MaxPat931** [DFreds/dfreds-convenient-effects#214]
**Is your feature request related to a problem? Please describe.**
Adding the option to apply a CE effect from a chat card or a journal would further empower lower-automation workflows to quickly apply or toggle CE effects from an item or location's description

**Describe the solution you'd like**
Create a custom enricher to enable Applying/Toggling a CE effect from chat or a journal, such as `@applyCE[effect-name]` or `[[/toggleCE effect-name]]`

![image](https://user-images.githubusercontent.com/86370342/220011902-5b061f91-9e6f-42c8-97fa-e5b5612b5103.png)

**Describe alternatives you've considered**
Manual application, or creating actor actions to use for Effect transferal

**Additional context**
I just think it would be nice

**Comment by DFreds** [comment]
That's a cool idea. No clue how to do that at the moment but I'll research it

**Comment by MaxPat931** [comment]
Kaelad's Inline Roll Commands adds a few custom enrichers so that's where I would recommend looking, I wish I could give some more actual help for you though

**Comment by DFreds** [comment]
This will go out in the next release. Thanks for the suggestion! You can find docs on it on the wiki, but it essentially looks like this:

```
@toggleEffect[Bane]{Toggle Bane on Selected Actor}

@toggleEffect[Bardic Inspiration]

@toggleEffect[Non-existent Effect]{Toggle effect that doesn't exist}

@toggleEffect[Non-existent Effect]
```
![image](https://user-images.githubusercontent.com/11878569/220830069-24606de1-2754-470a-9846-5b9d1e7a0b93.png)

**Comment by MaxPat931** [comment]
Awesome! Thank you!
