### ISSUE TITLE
CE-Midi integration not showing up as an option on item sheets anymore

### ISSUE THREAD

**Issue by ctbritt** [DFreds/dfreds-convenient-effects#217]
**Describe the bug**
The option to use CE instead of an AE I no longer available on item sheet

**To Reproduce**
Open Item sheet with CE and Midi enabled. Midi should have some aspect of checkbox on the item sheet, but it's absent now. 

**Expected behavior**
Checkbox to govern whether CE is enabled or not appears. 

**Screenshots**
Here are my midi settings, which haven't changed: 
<img width="786" alt="CleanShot 2023-02-24 at 18 07 13@2x" src="https://user-images.githubusercontent.com/4516034/221317831-13765fae-c694-4f6a-9db6-15e23e2ba154.png">

And here's what I see on a spell that has an effect associated with it. (Invisibility spell, in this case)
![CleanShot 2023-02-24 at 18 08 45@2x](https://user-images.githubusercontent.com/4516034/221318369-6dc1acc6-c692-4ebf-a3c3-b752aa6a2d6f.png)

**Additional context**
Midi CE flag is still on the item but it's not showing up visually: 
![CleanShot 2023-02-24 at 18 10 39](https://user-images.githubusercontent.com/4516034/221318729-8fde4a9d-cc3c-4af2-8592-545decded136.png)

**Comment by DFreds** [comment]
I'll reach out to the dev of midi, as I don't directly handle this. Some of my internal changes may have caused this though

**Comment by ctbritt** [comment]
This seems fixed in the newest version of Midi

**Comment by tposney** [comment]
There was a change to CE that I was unaware of - should be resolved now.
