### ISSUE TITLE
CE Fails to Load

### ISSUE THREAD

**Issue by cgplayer2000** [DFreds/dfreds-convenient-effects#218]
CE doesn't come up with the current version 4.01.  I've had to go back to 3.1.1 in order to have CE come up with I push on the CE 'jazz hands' button.  

I've confirmed with FTC that the offending module is CE.  I unloaded all modules but CE and required modules, and ran FTC.  FTC indicated it was one of the ones I ran.  I also ran FTC with the modules listed in this error message, and it still confirmed that CE was what caused the error.  

Expected behavior:  I click on the CE button and can use it to change conditions and attendant effects on my tokens.

![image](https://user-images.githubusercontent.com/10798879/221324430-1fa50624-dbfb-4003-86f7-6915a029ae48.png)

**Comment by DFreds** [comment]
Bah! Thanks, fixed in 4.0.2.
