### ISSUE TITLE
[BUG] Unexpected error when downloading file

### ISSUE THREAD

**Issue by maxobremer** [DFreds/dfreds-convenient-effects#219]
**Describe the bug**
There seems to be an error when updating to the latest version of this module. A screenshot is provided below.

**To Reproduce**
1. try to update the module
2. get an error message, check with f12

**Expected behavior**
I expect it to download normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/86924581/221363977-b98c5c9b-5995-4a0f-b3c6-34e60f52ac12.png)

**Additional context**
I update my modules at least weekly, so was on a recent version before trying to update

**Comment by DFreds** [comment]
I don't believe this is related to the module, but to Github itself. I would try again later and see if it persists
