### ISSUE TITLE
Reckless attack and attacking with advantage issue

### ISSUE THREAD

**Issue by thatlonelybugbear** [DFreds/dfreds-convenient-effects#22]
Reckless attack effect: `flags.midi-qol.advantage.attack.mwak` is not taken into consideration when paired with `Change Mode:add`

`Override` or `Custom` work.

Maybe also needs to be `flags.midi-qol.advantage.attack.str` but still not RAW

**Comment by thatlonelybugbear** [comment]
Might need to change some things based on: https://discord.com/channels/170995199584108546/722566083499786352/867946836869132407

> tposney — Today at 02:50
flags.midi-qol...... need to be set via custom or override with custom preferred. Core foundry behaviour (as of 0.8.something) ignores ADD if the target value is undefined. Flags are undefined until set. So add does not work. I have chosen not to override the core apply effect code so it's not likely to change.

**Comment by DFreds** [comment]
Easy enough fix. Thanks for the update

**Comment by DFreds** [comment]
Fixed in v1.6.2
