### ISSUE TITLE
[BUG] (older) custom effects not recognised as convenient effects for the remove effect button

### ISSUE THREAD

**Issue by maxobremer** [DFreds/dfreds-convenient-effects#220]
**Describe the bug**
When a token has a custom convenient effect applied to them, the remove convenient effect button does not recognise them as a convenient effect to be removed.

**To Reproduce**
1. Apply a custom convenient effect
2. Try to remove said effect
3.  Click on 'Remove convenient effect'

**Expected behavior**
I expect the effect to be removed or have the option to select it as one of the effects to be removed, yet this does not happen.

**Screenshots**
![image](https://user-images.githubusercontent.com/86924581/221364463-54a4d29b-d461-427d-b8b2-1897e6cf068a.png)

**Additional context**
It seems to only effect custom effects that already existed before the last update.

**Comment by DFreds** [comment]
Ah, yes. This is because I changed the flag of what is considered a convenient effect. I'll add some backwards compatibility for older custom effects. Thanks for raising the issue!

**Comment by DFreds** [comment]
Fixed in v4.0.3.
