### ISSUE TITLE
[BUG] Lighting effects applied using Active Token Lighting break randomized wildcard tokens

### ISSUE THREAD

**Issue by guldelox** [DFreds/dfreds-convenient-effects#221]
**Describe the bug**
When applying a Convenient Effect that applies lighting via Active Token Lighting to a token that uses Randomize Wildcard Images, it breaks the token image.

**To Reproduce**
1. Using Convenient Effects, apply an effect that includes any lighting effect to a randomized wildcard token.
2. Observe that the token image path is broken

**Expected behavior**
Applying active lighting effects should not break the token image.

**Screenshots**
![ConvenientEffects_Errors](https://user-images.githubusercontent.com/67302749/221383719-d9bc4855-d8d9-49f6-92ce-78e332a485c8.gif)

**Additional context**
Tokens that have non-randomized image paths are not affected by this error. Only tokens whose image path includes a wildcard (i.e., tokens/Creatures/Humanoid/Berserker_Medium_Humanoid_*) are affected. I make extensive use of Forgotten Adventures tokens, which include many color variations for each creature token.

**Comment by guldelox** [comment]
This bug still occurs when all other modules but Convenient Effects and ATL are disabled.

**Comment by DFreds** [comment]
This might be an ATL bug only. Can you try adding an effect to an actor that has ATL effects when CE is disabled?

**Comment by guldelox** [comment]
Yep it does appear to be an ATL bug. Manually creating an effect with lighting causes the same thing, even when Convenient Effects is disabled. Ok! I will submit this bug to ATL then :)
