### ISSUE TITLE
BUG Force Show field no longer populates on versions past 3.1.1

### ISSUE THREAD

**Issue by MotoMoto1234** [DFreds/dfreds-convenient-effects#222]
**Describe the bug**
You need to return the feature that adds "Convenient Effect: Yada Yada" to the force show field also known as status ID field.  This is breaking badly for anyone with massive midi setups and midi can't fix this part.  It is making us all have to re-edit 100+ CE's so they become temp passive ae's again.  DAE's special durations do not count to make things temporary passive we relied on this feature of yours.  Make it a toggle if you have to but please add it back in.  Either that or give us a macro that auto populates all ce's with it.  

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by DFreds** [comment]
Thanks for reporting this.
