### ISSUE TITLE
Issues with createNewCustomEffectsWith, parameter is undefined

### ISSUE THREAD

**Issue by SirGarhi** [DFreds/dfreds-convenient-effects#223]
**Describe the bug**
When trying to programmatically create a custom effect, the passed parameter gets eaten by the interface and becomes undefined.

**To Reproduce**
1. Write a macro to define some effectData and call game.dfreds.effectInterface.createNewCustomEffectsWith(effectData);
2. Execute the macro
3. See error

**Expected behavior**
A custom effect is created

**Screenshots**

**Additional context**

**Comment by DFreds** [comment]
Thanks for the report, I'll check it out

**Comment by DFreds** [comment]
Can you give me your exact example you're working with?

**Comment by SirGarhi** [comment]
ok, this was a case of me misreading how the interface works. Disregard.

/facepalm
