### ISSUE TITLE
Specify display order of conditions in token UI

### ISSUE THREAD

**Issue by emwhalen** [DFreds/dfreds-convenient-effects#225]
Currently, conditions are ordered in the token overlay menu according to the chronological order in which they were toggled as available for that menu. I prefer my conditions to be ordered alphabetically, and correcting the order accordingly can be tedious if, for example, I add "Airborne" as a new custom condition and need to then toggle off all conditions and then toggle them back on in the correct order just to have "Airborne" be first in the list rather than last.

A desirable outcome might be a system by which I can arbitrarily specify the display order of conditions in the token overlay menu.

Many thanks for your time and consideration and for your hard work on this excellent module.

**Comment by emwhalen** [comment]
I don't really have a specific vision of implementation. CUB has a method of ordering conditions arbitrarily, but it might be excessive as a model for DCE. Alphabetical is all I personally hope for anyway.

Thanks again.

**Comment by DFreds** [comment]
Gotcha. I think alphabetical sorting could be done with a setting or something... but actively allowing you to choose the order would be difficult. You could maybe add a priority field into each active effect config sheet, but it seems like overkill and still not very usable.

I'll think about it, but let me know if you have other ideas.

**Comment by emwhalen** [comment]
Ok, I'll do that. In any case, feel free to consider this a low priority. It's just polish if anything.
