### ISSUE TITLE
Bug when importing Monters to World using Plutonium while DFred Convenient Effects is installed.

### ISSUE THREAD

**Issue by RusselH3X** [DFreds/dfreds-convenient-effects#226]
**I installed your module and when I then tried to import some monsters from Plutonium to my World the error in the attached image keeps coming and prevents the monster to be imported successfuly**

**To Reproduce**
1. Open any 'D&D 5E world with Plutonium, MidiQOL and DFreds Convenient Effects Installed'
2. Click on 'The Plutonium Importer on the Actors Section'
3. Try to 'import any monster to any folder'

**Expected behavior**
I expected the monster to be imported cleanly

**Screenshots**
![Screenshot_2](https://user-images.githubusercontent.com/99290939/222916997-6cfa8d37-759c-4193-84a4-09b47185c452.jpg)

**Additional context**
![Screenshot_3](https://user-images.githubusercontent.com/99290939/222917001-b03ec0e2-1e7e-42f5-af91-6330ad2b13fa.jpg)

**Comment by DFreds** [comment]
I can't support anything related to that module. Looks like they need to update it though
