### ISSUE TITLE
Custom Effects Added to Favorites Not Visible

### ISSUE THREAD

**Issue by smturg** [DFreds/dfreds-convenient-effects#229]
**Describe the bug**
Adding any Custom Effects to "Favorites" via the right-click menu with the "Convenient Effects" box does not work. Custom Effect disappears from "Custom" folder and does not appear in "Favorites" folder.

**To Reproduce**
1. Go to Convenient Effects within Foundry
2. Click on Custom Effects Folder
4. Right-Click and Custom Effect
5. Add to Favorites
6. Item disappears from Custom Effects, doesn't appear in Favorites.

**Expected behavior**
The effect should appear in Favorites, and does not.

**Screenshots**
Not able to create a screenshot that shows this particular error; unable to produce a video clip at this time, unfortunately.

**Additional context**
Pre-made (non-Custom) effects *do* appear in Favorites when following the process above.
Additionally, effects linked in the macro bar still do "work" - so they're still present somewhere. They're just not visible anywhere.

Thanks in advance for any guidance!

**Comment by DFreds** [comment]
Ah, thanks for the report. I'll fix this!

**Comment by smturg** [comment]
No problem; happy to help. Love the module.

Cheers!

**Comment by DFreds** [comment]
Fixed in v4.1.1
