### ISSUE TITLE
Any Chance we could change icon images to use our own assets?

### ISSUE THREAD

**Issue by subatoiWolf** [DFreds/dfreds-convenient-effects#23]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by DFreds** [comment]
There is no planned support for this. You can always dive into the effect-defintions.js file and change the icons yourself. These will be overridden on an update though.

When creating your own effects is released, you'll be able to pick any images you want.
