### ISSUE TITLE
"Reset Status Effects to Defaults" button not working

### ISSUE THREAD

**Issue by rbl047** [DFreds/dfreds-convenient-effects#230]
**Bug description**
When I click "Reset Status Effects to Defaults" button, it does not work.

**To Reproduce**
1. Open Convenient Effects window, using "hand with stars" UI icon.
2. Click on rounded "anti-clockwise" arrow.

**Expected behavior**
To see only the original effects from the module, without any custom ones.

**Screenshots**
![ce-bug-reset-button](https://user-images.githubusercontent.com/46825122/224582717-b704edc5-2c55-43f3-b6cc-13bbfdb2bfe6.png)

**Comment by DFreds** [comment]
That's not the intended behavior. You can manually delete them if you won't want by right clicking them. Reset status effects resets the Token HUD status effects back to the default ones for the DnD5e system (i.e. blinded, charmed, paralyzed, etc.)

**Comment by DFreds** [comment]
https://github.com/DFreds/dfreds-convenient-effects/wiki/User-Guide#adding-and-removing-status-effects

**Comment by rbl047** [comment]
> intended behavior. You can manually delete them if you won't want by right clicking them. Reset status effects resets the Token HUD status effects back to the default ones for the DnD5e system (i.e. blinded, charmed, paralyzed, etc.)

Thanks for the clarification, DFresds! But a problem remains. The button "Import" has some sort of bug. When I import the json file not all the effects are replaced corretly. Could you please take a look? Thanks!
