### ISSUE TITLE
A button to reset Convenient Effects to its original settings

### ISSUE THREAD

**Issue by rbl047** [DFreds/dfreds-convenient-effects#231]
**Is your feature request related to a problem? Please describe.**
When I create a custom effect and export the JSON file, everything works as expected. However, if I make any changes inside the effect, such as changing an attribute key, and then try to revert that change by importing the JSON file, the effect does not change at all. Therefore, I need to delete the custom effect and import the JSON file containing the latest custom effect. It's okay to do this for a single custom effect, but when I need to change a lot of custom effects, the only way to update all of them is to delete all of them and import the JSON file, which takes too much time. Even after deleting the module and reinstalling it, the issue still persists.

**Describe the solution you'd like**
I believe a simple solution would be to include a "reset button" that reverts the custom effect to its original setup. That way, when I import the JSON file, every custom effect would be ready to use without having to delete and reimport them.

**Describe alternatives you've considered**
An alternative approach would be to ensure that the "import JSON" function performs the necessary updates correctly, without requiring additional steps such as deleting and reimporting the custom effects.

**Additional context**
Here is a video that shows the problem.
https://youtu.be/FABtsyMsvE4

**Comment by DFreds** [comment]
Interesting. Yeah, that could be added

**Comment by rbl047** [comment]
> Interesting. Yeah, that could be added

Hi, DFreds! Is there a way to do it manually inside the module folder? Thanks!

**Comment by DFreds** [comment]
Hi! Sorry, was on a bit of a hiatus. You could do this manually by finding the "DFreds Custom Convenient" item in your items.db and deleting it, then relaunching Foundry and the world. You could also do `game.items.get(game.settings.get('dfreds-convenient-effects', 'customEffectsItemId'))` in the console to get the item itself. From there, I think you could call `delete` on it. So `game.items.get(game.settings.get('dfreds-convenient-effects', 'customEffectsItemId')).delete()` I believe would work.

 But I will work on adding this now that I'm back.

**Comment by DFreds** [comment]
No longer relevant as of v7
