### ISSUE TITLE
addEffectWith() doesn't apply the value of the [tint] property.

### ISSUE THREAD

**Issue by lightsout0828** [DFreds/dfreds-convenient-effects#232]
After cloning an existing created effect with a "tint" property. When using the call "game.dfreds.effectInterface.addEffectWith({ effectData, uuid });", it does not set the tint on the added effect.

But the tint is correctly getting applied when using the normal: game.dfreds.effectInterface.addEffect({ effectName: myEffect, uuid: myUuid });

You can reproduce by setting a effect with a tint color, log it to confirm it has a tint set before attempting to be added. And afterwards it does not have the tint applied.
`const effectData = deepClone({ ...game.dfreds.effectInterface.findEffectByName('Blue') });
console.log(effectData);
game.dfreds.effectInterface.addEffectWith({ effectData, uuid });`

**Comment by DFreds** [comment]
Thanks for the report, let me look into it

**Comment by DFreds** [comment]
Fixed in next release
