### ISSUE TITLE
Nested effects and Dynamic effects not applied correctly？

### ISSUE THREAD

**Issue by juli4321JULI1234** [DFreds/dfreds-convenient-effects#233]
When apply Nested effects or Dynamic effects on a creature, it will work when I use it from the convenient-effects UI, but it will not work when I use it from the same name feature.

ex：Cast Enlarge/Reduce spell will apllied to "Enlarge/Reduce effect”.

**Comment by DFreds** [comment]
Is this with the midi integration?

**Comment by Dijmo** [comment]
Yes - when I tested it I was using the setting for Convenient Effects: 'Apply CE, if absent apply Item effects'. When I click the feature from the character sheet, it only applies the top level effect, but not the nested effects.

**Comment by DFreds** [comment]
What version of midi do you have installed?

**Comment by Dijmo** [comment]
10.0.35 - Just updated yesterday hoping that would fix it

**Comment by DFreds** [comment]
Fixed on my end in 4.2.0
