### ISSUE TITLE
Integration with times-up

### ISSUE THREAD

**Issue by Krigsmaskine** [DFreds/dfreds-convenient-effects#235]
**Is your feature request related to a problem? Please describe.**
Some of the effects' durations are a smidge off due to system limitations. The perfect example is Reckless Attack, where the "everyone has advantage towards you" is supposed to last until the start of your next turn. It is currently set to 6 seconds/1 round. DND5E treats this effectively as "start of next round", which means (depending on x combatants), you lose many rounds of being brutalized.

**Describe the solution you'd like**
times-up has special expiry durations, such as at the start of your next turn, that is achieved by setting flags on the effects, I'd like it if Convenient Effects would add these flags for the sake of the correct expiry? I would suggest to check if the module is enabled and only add these flags if so, but I actually don't think it'd harm if they were always present.

**Describe alternatives you've considered**
For now, I've just created the effects custom separately and use times-up in the custom effects. 

**Additional context**
Here's a pic of what I'd consider the right settings with times-up enabled
![image](https://user-images.githubusercontent.com/39592771/228005313-2e516673-044e-4a57-9b10-8a369b2106bc.png)

**Comment by DFreds** [comment]
Fixed. I used to have this, not sure how I lost it. Oh well, thanks for reporting it
