### ISSUE TITLE
Trusted player usage

### ISSUE THREAD

**Issue by Grebog** [DFreds/dfreds-convenient-effects#24]
**Is your feature request related to a problem? No

**Describe the solution you'd like**
I was hoping to allow permission for my trusted players to be able to use the convenient effects module. This way, when they cat a spell like bless,I can just make sure they hit the correct number of players, while they apply it to the tokens they are targeting with the spell.

So maybe in the module settings have a trust level and then DMs can decide how open or locked down they want convenient effects. And I am only suggesting an on/off based on the roles, for example GM (default), assistant, trusted player, player, everyone. 

**Describe alternatives you've considered**
I searched and could not find any setting to change who could use convenient effects on my game. Only other option I have is give players macros for their spells, but I would rather everyone use the same method rather than some use macros and i as dm use convenient effects, since getting the exact same token effect icon likely will not match and add confusion.

**Comment by DFreds** [comment]
That's a good idea. Thank you for the suggestion

**Comment by DFreds** [comment]
Added in v1.7.0
