### ISSUE TITLE
Add option to show chat effect description to send to affected player(s)

### ISSUE THREAD

**Issue by Krigsmaskine** [DFreds/dfreds-convenient-effects#240]
**Is your feature request related to a problem? Please describe.**
There's a lot of conditions and they can be hard to remember, instead of needing to either navigate into the actor sheet or use another module to peek at them, can affected token owners perhaps get the application/removal message of effects somehow?

**Describe the solution you'd like**
Another option in the settings to allow for owners of tokens affected by conditions to receive the apply/remove message, it gives a nice neat summary.

**Describe alternatives you've considered**
We used to use combat utility belt that dumped a public chat message when applying/removing and provided a summary for when the players' turn start, spitting out all effects affecting their that actor in chat, but I feel like that's a bit out of scope for CE? 😄 

**Additional context**

**Comment by DFreds** [comment]
Sounds good, added in the next minor version (likely 4.2.0). It's a new checkbox setting that will include the owner of the actor in any chat messages that are sent for effects. Note that it is still constrained by the normal role permission in the settings.

![image](https://user-images.githubusercontent.com/11878569/230161887-a32b569a-040e-4e35-95f2-e8483aaf1a7f.png)
