### ISSUE TITLE
+1 (or Other) Bonus to Flanking Issue

### ISSUE THREAD

**Issue by WThunderspirit** [DFreds/dfreds-convenient-effects#241]
**Describe the bug**
Not applying correct bonus during flanking

**To Reproduce**
1. Make a Duplicate Copy of "Flanked" CE
2. Change flags.midi-qol.grants advantage.mwak {custom, 1} to flags.midi-qol.grants.attack.bonus.mwak {add, +1[flanking]} &
change flags.midi-qol.grants advantage.msak {custom, 1} to flags.midi-qol.grants.attack.bonus.msak {add, +1[flanking]}
3. Save, reproduce a flanking condition on VTT
4. The bonus is not applied automatically

**Expected behavior**
Expected to see and have calculated a +1 bonus instead of advantage by flanking attackers.  Made custom changes to flanking as well, but IDK if that condition ever showed up on the attackers normally (you can add it manually).  The Flanked condition always did give advantage before, even though I don't desire this - I wanted +1 to attack.

**Screenshots**
![image](https://user-images.githubusercontent.com/107325064/229383142-8c8cf0ed-8f43-4d98-b18c-af27f0fdd60e.png)

**Additional context**
Wish there was a default - in D&D 5e, to change between advantage (+4.5 to 5 bonus), +2 (MCDM & XP to Level 3's preferred method), and +1 (Taking20 & my own preferred method) that could be picked up by CE.  Since that doesn't seem like something Atropos might do, I wish CE would make that something we could change from the Module Settings rather than having to use the Custom Duplicate Method, as I'm not sure if the Hooks work on changes, based on the behavior I'm seeing.  That isn't saying much, as I've had many problems of late as more and more is changing in D&D 5e and Foundry Core program.

**Comment by DFreds** [comment]
The "grants attack bonus" not applying seems like a midi bug. I'd recommend opening something on that repo.

Otherwise, you could probably just use the flanking condition and add 1 to the attack bonus.

Example for custom "Flanking" (i.e. the person attacking gets the bonus)
![image](https://user-images.githubusercontent.com/11878569/230165718-09722d05-4180-4a3d-970d-d48793616e13.png)

You can actually use midi to apply "Flanking" instead of "Flanked" and define what it does like in this screenshot.
![image](https://user-images.githubusercontent.com/11878569/230163668-019825ea-e379-4b66-a60b-2fcbd5fe9280.png)

CE provides any custom effects as a priority over built-in ones, so it will choose your duplicated Flanking condition  that adds the +1.

**Comment by thatlonelybugbear** [comment]
Do not use Add for the custom MidiQOl flags like the ones with grants.

These needs Custom change mode

**Comment by DFreds** [comment]
Good to know, thanks @thatlonelybugbear!

**Comment by WThunderspirit** [comment]
Actually - I had the "CE Flanked + No Conga Line" option already selected, but that seems to be where the issue lies.

I thought that setting should prevent the XoX with o being flanked
from turning into XoxO with o and x being flanked, but apparently it shuts it all down.

When I use the Convenient Effect Flanking Only, XoX is working with the +1 as intended, however, it also allows XoxO double flanking/ Conga Line (In my ruling, only the outermost two would be able to flank, so X and O, but o and x would receive no benefit since they are, themselves, flanked, cancelling any bonus or advantage of position).

Not sure if this is something that can be configured correctly in CE or to foreward over to Tim Posney to fix.

@thatlonelybugbear - you did catch me on that one, only because I was mid corrections and didn't double check what I screenshot ... lol.  But yeah I know any Custom is either 'On/ True/ 1' or 'Off/ False/ 0'.  (I've never used the On/ Off Booleans to see if they would work, but True/ False and 1/0 do.  I put them in to facilitate modality, not sure if those are correct in-so-far as programming language for DAE)
