### ISSUE TITLE
Allow the remove effect button to also remove non convenient effects

### ISSUE THREAD

**Issue by maxobremer** [DFreds/dfreds-convenient-effects#243]
**Is your feature request related to a problem? Please describe.**
I often make effects that are only for a specific item or ability without making them convenient effects, since they are a one time thing or clutter up the menu as there are no folders, and if I quickly want to remove them from a token then convenient effects doesn't recognise it. 

**Describe the solution you'd like**
It would be nice if an effect has the following "convenient effect:" in its description that the remove convenient effect button then also picks it up

**Describe alternatives you've considered**
Just manually opening the character sheet and removing the effect there

**Additional context**

**Comment by DFreds** [comment]
Seems reasonable to me. When it only detects convenient effects, it also means that only temporary effects will populate the dialog. I assume you'd still want that behavior? I think it would be annoying if it also populated with the passive effects.

**Comment by maxobremer** [comment]
If its a passive I just wouldnt add the convenient effect: tag unless it's a passive effect that can either be suppressed or lasts until dispelled. So I do see a use case for it also working on passive effects, though it is niche

**Comment by DFreds** [comment]
Hm, yeah. I was thinking of just allowing the remove button to remove any temporary effect, whether or not it is has a tag in the description. Then it just turns into a helper to avoid having to go into the actor's effects tab and wouldn't require any special work on the users' end to add a tag.

**Comment by DFreds** [comment]
Done, in next release

**Comment by thatlonelybugbear** [comment]
What I have done locally, is also to make the template for the effects removal dialog, to have all effects unchecked by default to make sure that no "mistakes" can happen, especially if you open it up to non DFreds CE.

Can do a selection and a button to delete and another to disable.

Depends on how you want to implement it of course!

![image](https://github.com/DFreds/dfreds-convenient-effects/assets/7237090/01aecc61-a262-4d47-a320-b055bc6f2da9)

**Comment by DFreds** [comment]
That's a great call. Feel free to make the PR for it
