### ISSUE TITLE
[BUG] Unable to download module in v11 Stable

### ISSUE THREAD

**Issue by kaldigo** [DFreds/dfreds-convenient-effects#246]
**Describe the bug**
When I try to install the mod using either the search or the manifest url I get an error.

**To Reproduce**
1. Launch Foundry VTT v11.299
2. Go to "Add-On Module" tab
3. Type "Tokenmagic" in the search
4. Click "Install" on "DFreds Convenient Effects"
5. See the error message

**Screenshots**
![image](https://github.com/DFreds/dfreds-convenient-effects/assets/6437691/99c3cc53-b1d2-4252-933a-e9ff93ec7557)
The first error is when I try to install using the manifest url. The secound is when I just click install.

**Comment by DFreds** [comment]
Right, it isn't supported for v11 yet. Work is ongoing to migrate it, but it broke a lot of things. Thanks for being patient!
