### ISSUE TITLE
ETA on V11 Support

### ISSUE THREAD

**Issue by EvldoaTV** [DFreds/dfreds-convenient-effects#247]
Just wondering if you have an ETA on V11 support?

**Comment by DFreds** [comment]
Not exactly. A lot of things broke, and it's been rather annoying figuring out why. There are also some potential bugs in Foundry that are causing the breaking. So be patient, but hopeful by next week

**Comment by EvldoaTV** [comment]
Thanks for the reply,  I will check back periodically
