### ISSUE TITLE
V11 can not create new Effects

### ISSUE THREAD

**Issue by DesertEagle50** [DFreds/dfreds-convenient-effects#251]
**Describe the bug**
creating a new effect gives an error. 
"Cannot set property statusId of #<Object> which has only a getter"

**To Reproduce**
1. Go to CE
2. Click on "create effect"
3. change the title. hit "submit changes"

**Expected behavior**
Should create a new CE.

**Comment by DFreds** [comment]
I'm not actually seeing this occur. Is there any more info in the console?

Is the world one that migrated from v10? It could be that it can't update the underlying CE item, which I might be able to resolve. Maybe try on a brand new world to see if that narrows it down. I would also appreciate if you could send me the world as a zip or something.

**Comment by DesertEagle50** [comment]
Yes a migrated world. I'll try with a new blank world. I'll see if I can upload the world. I'll 7zip it.

**Comment by DFreds** [comment]
Perfect, I appreciate that.

**Comment by DFreds** [comment]
Okay, that's what I figured. It seems like it might be an issue with Dynamic Active Effects (DAE) anyway based on that console log.

I am unsure why it's doing it... but if creating an effect still works and allows you to customize it and use it, then the error can probably be ignored. DAE will have to update to avoid using statusId, which was removed in v11.
