### ISSUE TITLE
v11 Effect Text is not showing in

### ISSUE THREAD

**Issue by The-BirdGod** [DFreds/dfreds-convenient-effects#252]
**Describe the bug**
Name description of effects is not showing.

**To Reproduce**
1. Right click token
2. Open effects tab

**Expected behavior**
Text next to each condition added by Convenient Effects.

**Screenshots**

![Untitled](https://github.com/DFreds/dfreds-convenient-effects/assets/110910890/e0f9d2b1-09d4-42ca-bad1-deb063063dfc)

**Additional context**
Even with only Dfred's on, hovering over the CE will not provide name.
.

**Comment by The-BirdGod** [comment]
I saw the comment in the other bug report about trying in a new world;

**Comment by The-BirdGod** [comment]
Accidentally closed issue.

Saw the other bug thread and tried to reproduce in new world, can confirm it's still happening in a fresh world. 
![image](https://github.com/DFreds/dfreds-convenient-effects/assets/110910890/c7b2174d-075b-47a9-be52-9d081c3ab066)

**Comment by DFreds** [comment]
Yeah, Foundry replaced all Effect.label properties with Effect.name.... except when it comes to status effects. Going to release this tonight, so  should be v5.0.1

**Comment by The-BirdGod** [comment]
Awesome, thanks for the update!
