### ISSUE TITLE
dnd5e Rage Damage calls changed/non-existent scale value in dnd5e 2.2.1

### ISSUE THREAD

**Issue by Aeristoka** [DFreds/dfreds-convenient-effects#255]
**Describe the bug**
It appears that the scale value for Rage has changed:

+ @scale.barbarian.rage-damage -> + @scale.barbarian.rage

**To Reproduce**
1. Apply "Rage" from dfreds effects onto a barbarian character
2. Roll a weapon attack
3. Observe no Rage damage
![image](https://github.com/DFreds/dfreds-convenient-effects/assets/7988297/29775793-ef59-44f8-99f4-3fd11a3ae808)
5. Change effect as detailed above
6. Roll weapon attack
7. Observe Rage Damage applied
![image](https://github.com/DFreds/dfreds-convenient-effects/assets/7988297/d0925a9b-355e-4a78-a2f4-d5efb3ae4ba8)

**Comment by DFreds** [comment]
Thanks for the report, fixed in next release

**Comment by Aeristoka** [comment]
> Thanks for the report, fixed in next release

Thanks for all these amazing, convenient effects!
