### ISSUE TITLE
Error with "Reaction" condition

### ISSUE THREAD

**Issue by Eidamir** [DFreds/dfreds-convenient-effects#256]
**Describe the bug**
When a "reaction" convinient effect is on, on a token of a non-player token actor, prompts "... lacks permission to update actor ..."

**To Reproduce**
Apply "reaction" convinient effect
Attack as a "player/trusted player" actor
Fail to do so.
**Expected behavior**
Expect it to work, because id does with other effects, but apparently not with reaction one.

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://media.discordapp.net/attachments/499669805599555636/1119801976767660093/image.png?width=1440&height=59)

**Additional context**
its just weird that a blank "Marker type" effect does disrupt the game.

**Comment by DFreds** [comment]
Is this with midi installed and reaction automation enabled?

**Comment by Eidamir** [comment]
Yeah

пт, 30 июн. 2023 г., 17:08 DFreds ***@***.***>:

**Comment by DFreds** [comment]
I see. Then I believe it is a midi issue, and should be opened in that repo for best results
