### ISSUE TITLE
Vision/Detection Modes Incompatibility

### ISSUE THREAD

**Issue by lacktheknack** [DFreds/dfreds-convenient-effects#259]
Bug: CE isn't working with Vision/Detection Modes 5E again.

Reproduction: When CE is active, using custom OR original effects such as Flying or Inaudible no longer blocks relevant detection (such as hearing or tremorsense) implemented in V/DM5E.

When CE is turned off, the original provided effects work as expected.  A few days ago, both original and custom effects correctly named worked as expected even with CE turned on.

Posting this here due to history of CE causing issues with the two.

Foundry: 302
DND5E: 2.2.1
CE: 5.0.2
Vision/Detection Modes 5e: 1.4.0

**Comment by dev7355608** [comment]
It works as expected for me. Could you provide step-by-step reproduction instructions?

**Comment by lacktheknack** [comment]
With CE on: Create a CE called "Inaudible" and make it a status effect, then log out and back in.  You now have two Invisible status effects and two Inaudibles (assuming you're using CE's "Add" functionality).

Place two tokens.  Make one invisible and inaudible using any combination of the status effects you like.  Now switch to the other token, who can detect the invisible one through Hearing if it's close enough.  Also tested with a Flying token (both VDM and CE variants) against a token with Tremorsense - the token was detected.

Turn off CE and restart the server.  Now there's only the provided status effects, and they block the detection.

**Comment by dev7355608** [comment]
All custom CE status effects seem to apply the status `Convenient Effect: New Effect`. This must be the bug here.

**Comment by DFreds** [comment]
Good find, will fix

**Comment by DFreds** [comment]
Fixed the issue with the status ID not being updated to the new name and will go out in the release. Let me know if this doesn't fix the issue

**Comment by LukasPrism** [comment]
I don't want to start a whole new issue for this but just wanted to alert that the new statuses aren't falling into alphabetical order, despite the settings in CE:

<img width="639" alt="Screenshot_2023-07-05_at_4 32 27_PM" src="https://github.com/DFreds/dfreds-convenient-effects/assets/104886594/d3736d9f-625d-4489-bddf-64c4e4bff2c7">

Many thanks!

**Comment by dev7355608** [comment]
Vision 5e adds its status effects back after CE removes them. That's why they are not in alphabetical order. They would be if the status effects were CE effects. That would also allow the user to remove those status effects from the HUD if they don't want them. I could create a custom CE effects for Vision 5e's status effects, but the user is able to edit those and so might accidently break things. Maybe CE could add API for defining additional effects that show up in the list of conditions?

**Comment by LukasPrism** [comment]
You’re right about users perhaps breaking things but it would also allow some more flexibility, for example if a user wanted to add a TMFX fly effect to the flying status (I had to do that with TVA). 
You could perhaps make it a setting to enable this (off by default). That’s how Stealthy handles it, so users can customise how the Hidden or Spot statuses affect the tokens, or add rider effects.

**Comment by Krigsmaskine** [comment]
@dev7355608 It seems like the statusEffects are defined by DFred's startup based on the module DFred's setting statusEffectNames. If you set this setting to include the name of a DFred's custom effect, it will start showing up in statusEffects next reload. I've only tested with GUI made custom effects, but there seems to be functions for creating custom ones [here
](https://github.com/DFreds/dfreds-convenient-effects/blob/main/scripts/effect-interface.js)
