### ISSUE TITLE
Toggling a core status effect unhighlights all active status effects

### ISSUE THREAD

**Issue by dev7355608** [DFreds/dfreds-convenient-effects#260]
**Describe the bug**

Toggling a status effect that is not one of Convenient Effects' makes all status effects in the status effects panel of the Token HUD render as if they are not active even if they are.

**To Reproduce**

1. Change *Modify Status Effects* to *Add*.
2. Place a token.
3. Toggle Convenient Effects status effects.
4. Toggle core status effects.

**Expected behavior**

Status effects that are applied to the token are highlighted.

**Screenshots**

![convienteffectsbug](https://github.com/DFreds/dfreds-convenient-effects/assets/31905376/b8187a68-a029-41dd-8630-54fea59f0cc9)

**Comment by DFreds** [comment]
Fixed in next version
