### ISSUE TITLE
Add core status IDs to Convinient Effects

### ISSUE THREAD

**Issue by theripper93** [DFreds/dfreds-convenient-effects#261]
**Is your feature request related to a problem? Please describe.**
When using Convinient Effects , special actions that might occur when those effects are added don't trigger with some effects. Since as of v11 effects can have multiple statuses, add the core status id to CEs.
For example instead of having just "Convinient Effects: Prone" as the effect statuses, have that AND "prone"

**Comment by DFreds** [comment]
Added in next version. Let me know if I missed any
