### ISSUE TITLE
Using macro.ce in DAE it adds rage then takes rage away instantly

### ISSUE THREAD

**Issue by YenBenGrey** [DFreds/dfreds-convenient-effects#262]
**Describe the bug**
I have macro.ce to instruct rage to be added to an actor due to other things happening on the effect. 
When trigger the rage, CE rage appears then instantly disappears. 

**Expected behavior**
For Rage to stay on the actor for the duration. 
<img width="521" alt="Screenshot 2023-06-28 at 19 46 11" src="https://github.com/DFreds/dfreds-convenient-effects/assets/98095856/ff1812c7-fcb6-49ad-affd-d077c3970efc">

**Screenshots**

**Additional context**
I am using a macro put together to work with wild surge rage. 
I am using v11 302
It is working in v10

**Comment by DFreds** [comment]
Fixed in Discord, but likely DAE issue
