### ISSUE TITLE
Add a button to item cards to quickly apply effects

### ISSUE THREAD

**Issue by kaelad02** [DFreds/dfreds-convenient-effects#263]
**Is your feature request related to a problem? Please describe.**
I run games that are medium-level automation, I'd say. I don't use Midi but I do use active effects and a couple of other combat automation modules. Sometimes a player will use a feature/spell that has a Convenient Effect that we'd like to apply. While we can open the CE app, search for the name, then click on it to apply the effect, there's got to be a quicker way.

**Describe the solution you'd like**
In a world script, I added the ability to add an "Add Convenient Effect" button to the item cards if their name matched a CE. If you click the button, it does the same thing as clicking on the CE in the app by calling `game.dfreds.effectInterface.toggleEffect`. Here's a screenshot of one using Guidance:

![image](https://github.com/DFreds/dfreds-convenient-effects/assets/19502084/21e1c370-0725-4713-87e6-f5464dc5b669)

**Describe alternatives you've considered**
Like the first section mentioned, I could open the CE app from the Token Controls and do it that way, but it would be faster having a button on the item card.

**Additional context**
I have code already and would be willing to submit a PR for it. Could even hide it behind a setting so it doesn't conflict with things like Midi.

**Comment by DFreds** [comment]
This is a fantastic idea. Please submit the PR, with an appropriate setting to enable/disable this

**Comment by kaelad02** [comment]
I submitted a PR, #266, but I'm getting an error b/c of how some code is initialized that I could use some help with.

**Comment by DFreds** [comment]
Going out in 5.1.0
