### ISSUE TITLE
Field Effect Description is missing.

### ISSUE THREAD

**Issue by discodotgg** [DFreds/dfreds-convenient-effects#267]
**Describe the bug**
When editting an effect, the field Description is absent.

**To Reproduce**
1. Go to any effect editing window.
2. Field Description is missing.

**Expected behavior**
There should be the field there to add a custom description to the effect.

**Screenshots**
![image](https://github.com/DFreds/dfreds-convenient-effects/assets/131381550/dc4b255a-26f0-46e7-b348-b9abbcab7adc)

**Additional context**
All required modules are installed.

**Comment by DFreds** [comment]
Are you using the DAE active effect config sheet? I don't know if it added support for it yet, but base foundry added its own description field (which I used to inject). So I just use that. DAE might not

**Comment by discodotgg** [comment]
I see. I was indeed using the DAE config sheet. With the base foundry sheet, I can change the description of the effects. That's good enough for me. Thank you.

**Comment by thatlonelybugbear** [comment]
New DAE v11.0.0 does rectify this
