### ISSUE TITLE
Error when autoremoving guiding bolt effect

### ISSUE THREAD

**Issue by Avitale34** [DFreds/dfreds-convenient-effects#27]
Using Midi Qol to apply convenient effects with a guiding bolt from a spell caster and having an issue with removing Guiding Bolt on the next hit. It rolls with advantage for the next attack but when it tries to remove the effect it throws this error in the console.

Uncaught (in promise) Error: The key VETtRTedJVA7bl8s does not exist in the EmbeddedCollection Collection
    at Map.get (/opt/foundryvtt/common/utils/collection.mjs:106)
    at ServerDatabaseBackend._deleteEmbeddedDocuments (/opt/foundryvtt/dist/database/backend/server-backend.mjs:1)
    at ServerDatabaseBackend.delete (/opt/foundryvtt/common/abstract/backend.mjs:214)
    at async Socket.handleEvent (/opt/foundryvtt/dist/server/sockets.mjs:1)

**Comment by DFreds** [comment]
Interesting, thanks for pointing that out. I'll look into it

**Comment by DFreds** [comment]
Hm, having trouble duplicating this behavior. It appears to work fine for me. Are you on the lastest midi-qol, DAE, and convenient effects? If so, can you lay out a more precise example of what is happening? For instance, is it a player casting Guiding Bolt and another player hitting the actor with advantage? The more detail you can provide (or even steps to reproduce), the easier it'll be for me.

Thanks!

**Comment by Avitale34** [comment]
Hmm I am using the latest versions of both, I tracked it down to a module interfering now to find which one haha

**Comment by Avitale34** [comment]
I seem to have been able to track it down to Combat Numbers, not sure if you are able to reproduce with that module installed.

**Comment by DFreds** [comment]
That's bizarre. So what this really means is that it is likely a conflict between DAE's removal of effects on "1Attack" and whatever combat numbers is doing. As such, I think this is not an issue with Convenient Effects. I recommend reaching out to either of the developers for those modules.

**Comment by Avitale34** [comment]
Okay I posted in the Issues of DAE
