### ISSUE TITLE
[Request] Further integration with Vision 5e

### ISSUE THREAD

**Issue by M0nk3yy** [DFreds/dfreds-convenient-effects#271]
I noticed the V5e status effects are not ordered alphabetically as they are added separately to the CE effects as mentioned here https://github.com/DFreds/dfreds-convenient-effects/issues/259#issuecomment-1627394535 by Eber. I am not sure what the best path to good integration for this but I think it is a good suggestion.

I would be open to adding them manually in CE (if I can still get the benefits of V5e), but as Eber mentioned, maybe having them added as original CEs or similar would be best? I'm not sure.

The main ones that don't lineup with the already existing CE's are Diseased, Flying, and Inaudible.

![image](https://github.com/DFreds/dfreds-convenient-effects/assets/66137312/af3e9444-827e-48c3-bcbe-aad781f33132)

**Comment by LukasPrism** [comment]
Burrowing is out of order too. Odd that it's jumped to first in line.

**Comment by dev7355608** [comment]
I hacked V5e's conditions into CE's.

https://github.com/dev7355608/vision-5e/blob/26073493d8175f7b73ccce2e8dda4098113fd036/scripts/compatibility.mjs#L99-L184

https://github.com/dev7355608/vision-5e/releases/tag/v1.7.0

**Comment by DFreds** [comment]
Nice, thanks @dev7355608
