### ISSUE TITLE
Convenient effects doesn't always play nice with Multi Token Status 

### ISSUE THREAD

**Issue by Opius134** [DFreds/dfreds-convenient-effects#277]
**Description:**
A module conflict with Multi Token Status (https://github.com/cs96and/FoundryVTT-multistatus).
When Multi Token Status is enabled, activating the Invisible status through token controls applies the invisible dynamic effect but not the visual effect on the token. Tokens given the invisible status via token controls can still be seen by all players. 

Tokens made invisible by the convenient effects window are affected as expected. 

**To Reproduce:**
1. Activate both Convenient Effects and Multi Token Status 
2. Right click a token, click on statuses, activate the Invisible effect
3. The icon for invisible appears on the token, the active effects apply to the character sheet, but the token remains visible to all players.

**Expected Behavior:**
Upon assigning the status from the token's status menu, the token should fade and become invisible to other players. 

**Screenshots:**
![image](https://github.com/DFreds/dfreds-convenient-effects/assets/100728089/f6ac55dd-3f10-4c49-8fa2-e945bc2429a2)
![image](https://github.com/DFreds/dfreds-convenient-effects/assets/100728089/077f32c5-1fc6-45cd-acac-e67bcff859ae)
![image](https://github.com/DFreds/dfreds-convenient-effects/assets/100728089/f0fba9e7-6959-4c1d-bbfa-3cf96de8e5b4)
With Multi Token Status enabled

![image](https://github.com/DFreds/dfreds-convenient-effects/assets/100728089/5b03b872-244c-4fde-9938-37dc6ed53127)
![image](https://github.com/DFreds/dfreds-convenient-effects/assets/100728089/9899b928-d8bb-40b0-b8a7-35dd6dcd3551)
With Multi Token Status Disabled

![image](https://github.com/DFreds/dfreds-convenient-effects/assets/100728089/327793e2-0892-489a-83e2-66d0167ed807)
![image](https://github.com/DFreds/dfreds-convenient-effects/assets/100728089/7069f252-deb9-4147-a526-6532fc9d861f)
![image](https://github.com/DFreds/dfreds-convenient-effects/assets/100728089/f00a078c-fb7a-44a9-bb70-50e14db7e97c)
The workaround

**Additional Context:**
The console window doesn't output any error codes. It seems like it's a visual bug only, but it does affect game for the invisibility use case. 

I'm not sure what other data could be useful here, but let me know and I'll provide what I can. Thanks for your time!

**Comment by DFreds** [comment]
It's likely because we both override `TokenHUD.prototype._onToggleEffect`. If you open up the libWrapper settings menu, you should be able to prioritize one over the other or see what the conflicts are. Ultimately, I'm not sure there is much I can do here as I have to override this function.

![image](https://github.com/DFreds/dfreds-convenient-effects/assets/11878569/cc13cdd2-b4e0-442e-8f02-23ed17c623af)

I'll wait for your findings before closing this

**Comment by Opius134** [comment]
With Convenient effects prioritized, we lose multi token status' functionality and get this warning. 
![image](https://github.com/DFreds/dfreds-convenient-effects/assets/100728089/588a7506-c459-434f-a811-f665a723cb27)
With Multi Token Status prioritized, we lose the visual effects of invisibility and get this warning.
![image](https://github.com/DFreds/dfreds-convenient-effects/assets/100728089/55fb74ae-35ec-4463-b31c-1d1d359ae32f)
Functionally, it's not quite the same as disabling the mods. If it's unfixable, that's not a huge loss. The big workaround is just to select statuses from the convenient effects window instead of the token menu, which works for me. 

Even if it can't be fixed, I'd like to thank you for looking into it. I appreciate the time!

**Comment by DFreds** [comment]
So, Foundry STILL hasn't implemented a way for two modules to manipulate the status effects despite some feature requests. It isn't a supported API, so every module that does is patching it to do something, and they'll override each other. This can be revisited if and when Foundry adds this, or if a library is created which could somehow do this
