### ISSUE TITLE
[Request] Total Cover CE

### ISSUE THREAD

**Issue by txm3278** [DFreds/dfreds-convenient-effects#278]
DFred's CE already has Cover (Half) and Cover (Three-Quarters). A Cover (Total) would be really nice for modules like [Alternative Token Visibility's](https://github.com/caewok/fvtt-token-visibility) cover calculator.

Cover (Total) could just have the active effect: flags.midi-qol.grants.attack.fail.all
![image](https://github.com/DFreds/dfreds-convenient-effects/assets/25332081/175931bf-a4d8-4623-a6dd-1ab3604058cb)

**Comment by DFreds** [comment]
Great idea! Added and it'll be out in the next release

**Comment by thatlonelybugbear** [comment]
@caewok this might be of interest to you as well ;)

**Comment by caewok** [comment]
Thanks! I am in the process of updating Alt. Token Vision. Once you release your next update, I will update ATV accordingly to use DCE's total cover.
