### ISSUE TITLE
Torch not auto-triggering

### ISSUE THREAD

**Issue by jocolamarco** [DFreds/dfreds-convenient-effects#28]
**Describe the bug**
The torch doesn't trigger the effect when active.
FVTT 0.8.8
DND5e 1.4.1
Module 1.8.1

**To Reproduce**
1. Import Torch from dnd5e SRD compendium
2. Edit details and change target to Self
3. Equip and roll it
4. No effect triggered

**Expected behavior**
Torch doesn't trigger effect

**Screenshots**
My Torch configuration:
![image](https://user-images.githubusercontent.com/45291719/128896636-662a9b9f-20ee-42c9-b7aa-45a0aebbfc3f.png)

**Additional context**

**Comment by DFreds** [comment]
The auto application of the effect only works if you have the midi-qol setting "Apply Convenient Effects" enabled. Otherwise, it won't do any auto application of any effects. Let me know if that was the issue

**Comment by DFreds** [comment]
Discussed via Discord. This occurs because it has a melee attack by default from the SRD. Disabling the action type fixes the issue
