### ISSUE TITLE
Old effects' descriptions not migrated to new editors' description field

### ISSUE THREAD

**Issue by Krigsmaskine** [DFreds/dfreds-convenient-effects#285]
**Describe the bug**
If you have a description on an effect from before DFred's switched editor, the description will not be shown in the editor after the update, but is still present somewhere, as chat output will output the old message. 

**Screenshots**
![image](https://github.com/DFreds/dfreds-convenient-effects/assets/39592771/89366cb5-bc0b-4be3-b5ba-2698845656e2)

**Comment by thatlonelybugbear** [comment]
So I guess for that there needs to be a migration, which will check if that description is empty or not, check the flags to get the older description if available, copy the description in the new field and unset older Flags 🤔

**Comment by DFreds** [comment]
After v7.0.0, everything uses the built-in description field
