### ISSUE TITLE
Light spell emit no light

### ISSUE THREAD

**Issue by Darshyne** [DFreds/dfreds-convenient-effects#29]
**Describe the bug**
Light spell emit no light (maybe ATL bug)

Other lights (torch etc. work nice)

**consolle error**
VM10571:1 Uncaught (in promise) SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at duplicate (helpers.mjs:111)
    at Function.applyEffects (activeLighting.js:448)

**Comment by DFreds** [comment]
Nope, I broke that accidentally. Thanks for pointing it out. A fix will go out later today

**Comment by DFreds** [comment]
Fixed in v1.8.3
