### ISSUE TITLE
Blanks Status Effect Text

### ISSUE THREAD

**Issue by kajishun** [DFreds/dfreds-convenient-effects#292]
**Describe the bug**
When this module is enabled, the Assign Status Effects text disappears. I used Find the Culprit to verify this issue. This module is the culprit.

**To Reproduce**
1. Right-Click a token.
2. Click assign status effect.
3. Hover any status effect.
4. No status effects have hovered text while this mod is enabled.

**Expected behavior**
To not remove status effect text. Or to add an option to the game settings to remove status effect text.

**Screenshots**
Added.

**Additional context**
None.

![Screenshot 2023-08-26 223321](https://github.com/DFreds/dfreds-convenient-effects/assets/60208624/cb90d828-dc03-451d-94bf-a38f026b2b72)

![Screenshot 2023-08-26 223805](https://github.com/DFreds/dfreds-convenient-effects/assets/60208624/552e64cb-03f3-4f73-867f-f14ccd471c51)

**Comment by DFreds** [comment]
I'm not actually seeing this error. Are you using anything else that is modifying status effects?

**Comment by kajishun** [comment]
I think I figured it out. I changed Modify Status Effects to None and now the mouseover text works. I coulda sworn I had tried this before submitting the issue. Thank you for this awesome FVTT mod! Closing issue.
