### ISSUE TITLE
DFred's Convenient Effects + Active Token Effects + Token Magic- Inconsistent between worlds

### ISSUE THREAD

**Issue by Shareenx** [DFreds/dfreds-convenient-effects#294]
I am out of ideas on what to try.

**Describe the bug**
On one world (same server)- DFred's Convenient Effects + Active Token Effects + Token Magic toggles both status icons and token effects, different world the active effects do not work 

**To Reproduce**
I have no clue. 
For me:
Verify "Integrate with Token Magic" is on for both worlds. 
Activate DFred's Convenient Effects + Active Token Effects + Token Magic on one world- toggle status w/ DFred's- status icon and Token Effect turn on and off- love it.
Go to another world on the same server- toggle- only status icon toggles
No errors in console. 

**Expected behavior**
Both worlds to act the same

**Screenshots**

**Additional context**
Foundry v11.308
D&D 5e 2.3.1
All modules updated
socketlib & libwrapper also enables

Tried with brand new character- npc or pc. Same issue
I reinstalled DFred's and Token Magic. Did not help
Used Forien's Copy Environment to make sure all module variables were the same- exported from working world, imported to non working world.
Tried asking on Foundry VTT's Module Troubleshooting channel- no one had any ideas. 

I can manually run a Token Magic Macro on both worlds and get the Token Effects to happen.
The Character sheet shows the effect under Temporary Effects, enabling it or disabling it from the character sheet just toggles the status icon, no active effect.  No console errors there, either. 

Console says 
Foundry VTT | Created ActiveEffect with id [yf8W7bGdxI0ZRUiO] in parent Actor [VHAsB9z4tO4Kqdhr]
logger.js:8 dfreds-convenient-effects | Added effect Bardic Inspiration to TestPC - VHAsB9z4tO4Kqdhr

**Comment by DFreds** [comment]
Has this remained an issue?

**Comment by Shareenx** [comment]
Yes =D

But I am totally willing to retest when everything is updated to handle the
D&D 3.0 update

**Comment by DFreds** [comment]
Okay. I'll keep this closed. CE works with 3.0, but if you're waiting on other things I understand
