### ISSUE TITLE
statuses.unshift is not a function.

### ISSUE THREAD

**Issue by thatlonelybugbear** [DFreds/dfreds-convenient-effects#295]
When trying to use the `Invisibility` CE (not Invisible) this error is triggered (shown in attachement).

@tposney mentioned this first. Small change in `effect-helpers.js:55` adding 
```js
statuses = Array.from(statuses);
statuses.unshift(this.getId(name));
```
seems to fix.

![image](https://github.com/DFreds/dfreds-convenient-effects/assets/7237090/953abd27-f203-431b-9863-2495cb416cf5)

**Comment by DFreds** [comment]
Fixed in next release
