### ISSUE TITLE
Remove effect button is gone?

### ISSUE THREAD

**Issue by maxobremer** [DFreds/dfreds-convenient-effects#296]
**Describe the bug**
the button to remove effects is gone. Don't see an option in the settings to get it back.

**To Reproduce**
1. update to the latest version of dfred convenient effect
2. load into a world with only this module, libwrapper and socketlib
3. no delete effect button

**Expected behavior**
I expected the button to be in its usual space.

**Screenshots**

**Additional context**
tested on:
-Foundry 11 build 308
-DnD5e 2.3.1
-Dfreds Convenient Effects 6.0.0

**Comment by thatlonelybugbear** [comment]
I guess you are not using the Tooltips in the Core options?

Select a token and use Shift + Left mouse click

![image](https://github.com/DFreds/dfreds-convenient-effects/assets/7237090/54be796c-c826-4ba3-a152-c731b93a2cb4)
![image](https://github.com/DFreds/dfreds-convenient-effects/assets/7237090/f2e20f4b-cbb4-468d-9a3c-7c7a10b1a8d9)

**Comment by thatlonelybugbear** [comment]
https://github.com/DFreds/dfreds-convenient-effects/releases/tag/v6.0.0
mentions the recent change.
