### ISSUE TITLE
Fairie Fire not apply advantage

### ISSUE THREAD

**Issue by Avitale34** [DFreds/dfreds-convenient-effects#3]
Love this mod! I tried to use the Fairie Fire debuff and it was not applying the advantage for some reason. The flag looked right so I'm not sure why :(

**Comment by DFreds** [comment]
Oops, you are totally right. It is giving advantage on attacks to those who are affected by it, rather than granting advantage to those who attack it. Will fix very shortly

**Comment by DFreds** [comment]
Fixed in release 1.0.2
