### ISSUE TITLE
Stuck loading scenes from my updated v10 world

### ISSUE THREAD

**Issue by NdranC** [DFreds/dfreds-convenient-effects#302]
**Describe the bug**
I'm unable to load any scenes after updating from v10 to v11 with this mod enabled. They load up to 95% and never progress past. This was tested by disabling every mod except this mod and it's pre-requisites. Creating a new empty scene and trying to load into it still presents the same bug. Disabling this mod fixes the issue instantly.

**To Reproduce**
This ONLY seems to happen on my old v10 world. If I create a new world the issue does not happen.

**Additional context**
Paste bin with the console log
https://pastebin.com/jy0G7QG7

Foundry v11 b313
DnD5e 2.3.1
Dfreds Convenient Effects 6.0

**Comment by NdranC** [comment]
It seems like this might be a bug with firefox and convenient-effects combined. I tried in chromium and I don't have this issue.

drawImage() fails silently when drawing an SVG image without @width or @height
https://bugzilla.mozilla.org/show_bug.cgi?id=700533

I'm not entirely sure why this happens on my current world but not on a new world and how to fix it. But hopefully this might be a lead.

**Comment by DFreds** [comment]
Firefox has had issues with images before. I think it's relatively simple to add the width and height, but can anyone confirm if this is still an issue?

**Comment by NdranC** [comment]
Because of this issue I made a new world and continued my campaign there.  I don't know why butt this issue wasn't happening on a new world even with the same mods/assets.

Out of curiosity I loaded my old world and it seems to be loading fine on a quick test. /shrug

**Comment by DFreds** [comment]
Well, alright then. Maybe Foundry fixed something or who knows 🤷

**Comment by lucky-trill** [comment]
As someone who experienced the same issue just now, I'm just going to put this solution out there for posterities sake:

All I had to do was Reset Status Effects to Default using the button in the CE dialog and then repopulate the status effects I like to regularly use from my favorites. Fixed it right up, no new world or mysterious update waiting required.
