### ISSUE TITLE
[FR] Add different display types for CE list

### ISSUE THREAD

**Issue by kszczepanskidev** [DFreds/dfreds-convenient-effects#305]
**Is your feature request related to a problem? Please describe.**
Most of the effects provided by CE are just short name of condition or spell and an icon, in the current list one row takes a lot of vertical space and sometimes finding something you want without typing in search is not convenient enough.

**Describe the solution you'd like**
Add config for more list display types, for example:
- compact list where icon will be much smaller and row height set so it's enough to just fit the effect name,
- grid with just icons or with small text below icon (3-4 columns).

**Additional context**
My current solution to the problem is to use module for additional macro bars and put all needed CE there, but would be nice if it wasn't needed to have these CE visible and ready to use at most of the times.

**Comment by DFreds** [comment]
"is not convenient enough"

Triggered. 😆 I'll look into it. The main point of the current UI was to match as closely as possible to default Foundry lists. No promises here

**Comment by DFreds** [comment]
Won't do. I like that it looks like foundry

**Comment by kszczepanskidev** [comment]
That's fair, I ended up installing module for multiple macro hotbars and just dragged all relevant effects there 👍🏻
