### ISSUE TITLE
Custom Nested Effects do not follow HTML Formatting

### ISSUE THREAD

**Issue by Vaalenc** [DFreds/dfreds-convenient-effects#306]
**Describe the bug**
When creating custom effects, if those custom effects are utilized within a nested object, the formatting of HTML disappears. 

**To Reproduce**
1. Duplicate or create a new effect.
2. Insert description of said effect.
3. Utilize new effect in a nested object.

**Expected behavior**
Formatting should remain , similar to nesting premade effects.

**Screenshots**
![image](https://github.com/DFreds/dfreds-convenient-effects/assets/150857326/acc11cd4-3ddf-4102-a6dd-ec6418369619)

-custom effects do not contain formatting. 

![image](https://github.com/DFreds/dfreds-convenient-effects/assets/150857326/0817da85-69a4-4e56-89cc-38a7fee31962)

-premade blur effect has no issues with formatting.

If I could get any insight into the issue, I'd be very appreciative!

**Comment by DFreds** [comment]
No longer an issue as of v7
