### ISSUE TITLE
Remove effect button doesn't appear

### ISSUE THREAD

**Issue by Glandulf** [DFreds/dfreds-convenient-effects#307]
**Describe the bug**
The "Remove effect" button doesn't appear in my Foundry. I have to click on a token and maj+click DFreds' CE button to be able to remove the effects.

**To Reproduce**
1. Install the module
2. Open a world
3. Go to a scene
4. Open the "token control" panel

**Expected behavior**
I expected the "Remove Effect" button.

**Screenshots**
![DFred's Bug](https://github.com/DFreds/dfreds-convenient-effects/assets/18220235/f2809a42-bee4-41aa-b482-5d04d3d0c210)

**Additional context**
I have plenty of modules installed, some of them adding buttons to the Token Control panel (including Token Attacher and Sequencer) which might conflict with DFred's CE.

**Comment by thatlonelybugbear** [comment]
Use `SHIFT + left mouse click`

![image](https://github.com/DFreds/dfreds-convenient-effects/assets/7237090/43f962fe-67b0-4223-a290-7b5eb8a26ccf)

**Comment by Glandulf** [comment]
Sorry, that's what I meant by maj+click (maj is french for shift) !
As there was a "Remove Effect" button on every video I watched and on the wiki, I assumed mine had a problem, but it has been removed and replaced by the shift+click function, isn't it ? I'll close the issue then, my bad !

**Comment by thatlonelybugbear** [comment]
No worries, it has been a recent addition on [v6.0.0](https://github.com/DFreds/dfreds-convenient-effects/releases/tag/v6.0.0)
