### ISSUE TITLE
applying unconscious while prone applies multiple instances of prone condition

### ISSUE THREAD

**Issue by hwangeug** [DFreds/dfreds-convenient-effects#308]
**Describe the bug**
If a token already has the Prone condition before applying the Unconscious condition (say, due to yo-yo healing), the token will have two Instances of the Prone condition afterwards.

**To Reproduce**
1. Apply Unconscious using the Convenient Effects panel.
2. Unapply Unconscious.
3. Apply Unconscious again.
4. The token will have two instances of Prone.  If they become conscious, their movement will be quartered, and the user has to click multiple times to remove the Prone conditions.

**Expected behavior**
Multiple instances of Prone should not stack.

**Screenshots**

![image](https://github.com/DFreds/dfreds-convenient-effects/assets/11950803/51b0b2e9-b622-40b2-b628-86ed0edd5cf5)

**Comment by DFreds** [comment]
Good find, will investigate

**Comment by gludington** [comment]
Filed https://github.com/DFreds/dfreds-convenient-effects/pull/323

**Comment by DFreds** [comment]
It no longer does this as of v7
