### ISSUE TITLE
[Bug] Unable to use "Wounrded" condition in MidiQOL

### ISSUE THREAD

**Issue by Gensokian** [DFreds/dfreds-convenient-effects#310]
**Describe the bug**
This might just be me who is incapable of RTFM but I am unable to select any (even custom created) wounded conditions into MidiQOLs custom wounded thingie. (Unless this is a MidiQOL issue)

**To Reproduce**
1. Install MidiQOL + DFCE
2. Go to MidiQOL Settings
3. Go to "Mechanics" tab
4. See that there is no "Wounded" condition inside the dropdown.

**Expected behavior**
Being able to select the "Wounded" condition in MidiQOL

**Screenshots**
![image](https://github.com/DFreds/dfreds-convenient-effects/assets/9213561/99f1a0c6-7ea2-421e-aa56-9c793aab3d58)

**Additional context**
I have additionally tried to not use the "Replace" functionality as for this maybe borking up things. (Spoiler: It didn't)

**Comment by thatlonelybugbear** [comment]
It is an issue with MidiQOL *needing* the Wounded condition of DFreds CE, to be a `statusEffect`.

To resolve, go to the Wounded condition in the DFreds CE App (as shown in your screenshot), right click on it, and click on `Toggle Status Effect`.
Then reload Foundry and the Wounded (CE) will be shown in the relevant MidiQOL drop down.

(there is a mention on that in the MidiQOL relevant changelogs IIRC)

**Comment by DFreds** [comment]
Thanks @thatlonelybugbear. That is correct. Sorry for being late on this. I changed it so that Wounded is a default status condition going forward, but you would either need to reset the status effects or do what bugbear said.
