### ISSUE TITLE
Support for New dnd integration v3.0

### ISSUE THREAD

**Issue by EvldoaTV** [DFreds/dfreds-convenient-effects#315]
Mod no longer functions citing max version 2.4.1 dnd 5e system new Ver 3.0 not supported eta on possible update love your mod

**Comment by DFreds** [comment]
Frankly, the update broke a large amount of features. Currently evaluating if CE makes sense in its current form for dnd5e, especially considering it looks like they'll be adding their own automation. No ETA though

**Comment by EvldoaTV** [comment]
Yeh After watching the live stream today it seems that most of what CE did will now be integrated 
But Thanks for your reply and for your hard work on an awesome mod, which I am still using for now not updating to 3.0 yet

**Comment by DFreds** [comment]
This is now working in dnd 3.0.0 and greater as of v6.0.2
