### ISSUE TITLE
[Bug] D&D5E 3.0.2, Convenient Effects breaks charsheet method for setting Exhaustion

### ISSUE THREAD

**Issue by apoapostolov** [DFreds/dfreds-convenient-effects#316]
5E 3.0.2, latest Convenient Effects.

The Charsheet method of increasing and decreasing exhaustion breaks and cannot be increased above 0.

**Comment by DFreds** [comment]
Thanks for the report, I'll check it out.

**Comment by SagaTympana** [comment]
Looks like at least part of the problem here is in actor.mjs, line 3161. If the CE status are set to replace the default ones, this line fails to return anything because it's looking for a status with an id of `exhaustion`, which will no longer exist because Convenient Effects has yeeted it.

**Comment by Nolat** [comment]
Is there any update on this fix ?

**Comment by rjbprime** [comment]
Still broken on FoundryVTT 11.315, DND5e 3.1.2, and CE 6.0.3.

**Comment by DFreds** [comment]
No longer integrated with status effects as of v7.0.0
