### ISSUE TITLE
[Feature Request] Option to put the effect directory to a sidebar directory

### ISSUE THREAD

**Issue by p4535992** [DFreds/dfreds-convenient-effects#317]
### Is your feature request related to a problem? Please describe.

I would like to be able to move the effect directory from the button on the right to a sidebar on the left

### Describe the solution you'd like

Here a image of the result:

![](https://i.imgur.com/bkHIk8m.png)

### Additional context

i have poorly tried to do this, but it require more code than expected... 
https://github.com/p4535992/dfreds-convenient-effects/commit/02785d5cacef116e44816ff14705c8638b6c67bc

**Comment by DFreds** [comment]
Hm... I was actually considering making this a whole separate module. Maybe one that could just integrate with CE. But it's cool how easy this is... I'll consider adding it, but for now will close this out for now.
