### ISSUE TITLE
[Bug]Concentration spells not working

### ISSUE THREAD

**Issue by EvldoaTV** [DFreds/dfreds-convenient-effects#321]
getting this error with a number of spells like witch bolt, entangle and fairie fire since latest 5e update'
the roll isnt completing in the chat cards

acttive-effect.mjs:426 Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'id')
[Detected 1 package: system:dnd5e]
at ActiveEffect5e.createConcentrationEffectData (active-effect.mjs:426:31)
at Actor5e.beginConcentrating (actor.mjs:1112:33)
at Item5e.use (item.mjs:1028:39)

disabled all other mods and found that CAE was the cause

**Comment by DFreds** [comment]
I need more info here... Specifically, how you were applying the spell and/or concentration. Via midi?

**Comment by EvldoaTV** [comment]
> I need more info here... Specifically, how you were applying the spell and/or concentration. Via midi?

All other mods are disabled and only Dfreds is active, so the dnd5e system and dfreds are handling concentration.
casting spell from character sheet which causes the above error, the spell doesn't produce a chat card, template or anything 

I am using the new dnd5e, everything was working find until the most recent update to the 5e system from foundry

**Comment by DFreds** [comment]
Gotcha, thanks for clarifying. A fix is in the works

**Comment by EvldoaTV** [comment]
thank you for the reply look forward to a fix absolutely love your mod

**Comment by lovethebomb** [comment]
Thank you for working on this @DFreds !

For a quick fix meanwhile the bug is in the works:
- In the Module Settings, switch `Modify Status Effects` to `None` or `Add`. 

You can still apply the effect with the `Convenient Effects` toolbar

The issue only happens because `Replace` does not take into account the (new 3.x.x?) dnd system changes related to Concentration warnings before casting spells.

**Comment by Lector** [comment]
I am having the same issue.
Thanks for fixing this in advance.
Im already looking forward for the next update :)

**Comment by Silcet** [comment]
If you have a commit or a branch for testing I'd be glad to help in that regard. I have an instance I usually use to test upgrades before upgrading things in the FVTT server where we play our campaign, so it can be easily used for testing this fix.

Thanks for the workaround also @lovethebomb ❤️ 💣

**Comment by AAUCrisp** [comment]
How is this issue so late by now?
I'm sad that I have to dissable DFreds Convenient Effects :( 
It's a nice module.

Is there a fix on the horizon?

**Comment by DFreds** [comment]
As of v7, CE doesn't do anything with status effect IDs anymore. There is still a Concentration condition that midi should be able to use
