### ISSUE TITLE
Feature Request: Create Custom Skill/Actions

### ISSUE THREAD

**Issue by kaiomazziero** [DFreds/dfreds-convenient-effects#322]
### Is your feature request related to a problem? Please describe.
I began to play pf2e on foundry recently, and I was told on Discord that the only way to create a Custom Skill was to create a Esoteric Lore and modify it with rule elemento so that would match the Lore. 
I think that is quite dificult to do that, is counterproductive and maybe we could use the hability to Create Custom Skills and Actions on the system itself

It's a little frustrating because there is a lot of people that use PF2e to Homebrew, and this would be a huge QOL!

### Describe the solution you'd like

Hability to Create Custom Skills and they add automactly to the character sheet so we don't have to use a workaround to do it!

### Describe alternatives you've considered

We could have the possibility to create custom skills/actions on this windows, since there is already the options to add some homebrew.

![image](https://github.com/DFreds/dfreds-convenient-effects/assets/47760399/16f53e27-b97f-44d7-b23f-d899d4d404dd)

Thank you for creating everything for us, you guys are awesome!

**Comment by DFreds** [comment]
Not sure this belongs to this module or if there was some confusion here
