### ISSUE TITLE
DND5E 2.4.1 Effect removed before combat

### ISSUE THREAD

**Issue by vinnie2k** [DFreds/dfreds-convenient-effects#324]
### Describe the Bug

When I set a custom effect on a PC, attacking removes the effect automatically.

### Context

No errors on the console
Foundry version  = 11.315
System = DND5E 2.4.1
Browser = Microsoft Edge
Hosting service = Molten

### To Reproduce

Create custom effect called "Flanking" which sets flags.midi-qol.advantage.attack.mwak to 1
Create macro: "game.dfreds.effectInterface.toggleEffect("Flanking")"
Use macro on PC (effect applied successfully)
Target NPC
Select PC attack (effect removed before roll)

### Expected Behavior

I expect the attack to take the effect into account.

**Comment by thatlonelybugbear** [comment]
I imagine this has siomething to do with MidiQOL actually checking for Flanking.

What is your relevant setting set to, under MidiQOL settings > Workflow settings > Rules for Check Flanking?

![image](https://github.com/DFreds/dfreds-convenient-effects/assets/7237090/3fe90b3d-36d1-4cd7-ac75-1c666c185bb6)
