### ISSUE TITLE
[Feature Request] Macro to render the CE panel.

### ISSUE THREAD

**Issue by mflaherty97** [DFreds/dfreds-convenient-effects#325]
I'd like to just be able to press a hotkey and open up the DFCE panel rather than having to navigate to the sidebar. 
Is this possible?

**Comment by DFreds** [comment]
I could probably add a keybinding for this. Any suggestions?

**Comment by DFreds** [comment]
Doing it via a macro is probably not possible without exposing the app in the object... Maybe I could do that too

**Comment by DFreds** [comment]
I ended up doing a keybinding that toggles the app open or closed, but set to unbound initially. This will be out in the next release

**Comment by mflaherty97** [comment]
Default should be be P. Purely vibes based choice.
