### ISSUE TITLE
[BUG] macro.CE can't reference the effects of DCE

### ISSUE THREAD

**Issue by Memorize-Remix** [DFreds/dfreds-convenient-effects#331]
### Describe the Bug

When I use the macro.CE tag in the effect, I can't find the effect that DCE already has.

### Context
![Snipaste_2024-08-15_16-58-37](https://github.com/user-attachments/assets/539b3e56-1863-4b4a-aa1c-2d134d240a53)

- Foundry version (12.330)
- System and version (D&D 5e 3.3.1)
- Module version (7.1)
- 
### Expected Behavior

As in previous versions, the effects created by DCE can be referenced here for easy recall.

**Comment by thatlonelybugbear** [comment]
That is a DAE bug and should be resolved with DAE 11.4.48 release
