### ISSUE TITLE
Concentration not working at all

### ISSUE THREAD

**Issue by Trinistar** [DFreds/dfreds-convenient-effects#332]
### Describe the Bug

with d&d5e concentration tracking disabled, concentration is not being tracked at all. other conditions like invisible are working.

### Context

- Foundry version 12.330
- System and version D&D 5e 3.3.1
- Module version newest
- Browser chrome
- using with Midi qol

**Comment by DFreds** [comment]
It's a midi issue. I would raise the issue there
