### ISSUE TITLE
Error on client side when deleting effects

### ISSUE THREAD

**Issue by boss-loot** [DFreds/dfreds-convenient-effects#335]
### Describe the Bug

When deleting an effect that have also a nested effect (for example **Stunned**) an error appear on the client side stating that the ActiveEffect id does not exists!

### Context

- Screenshots and demonstrating the problem if applicable.
- Any errors in the console; access it by pressing F12
- Whether you ran [Find the Culprit](https://foundryvtt.com/packages/find-the-culprit/) and if it was caused by an interaction with another module
- Foundry version: 12.331
- System and version: DnD 3.3.1
- Module version (include all modules involved)
  - dfreds: 7.0.1
  - midi: 11.6.2
  - dae: 11.3.51
  - Effect Macro: 12.1.1
- Browser and hosting service: Chrome

### To Reproduce

So to reproduce start the Foundry app and then connect at least a player from a browser. Then, as GM, select a creature (not the connected player) and using the dfreds interface add **Stunned** to the creature. When deleting the effect using the dfreds interface the error will appear on the client side stating that the effect (Incapacitated) does not exists.

### Expected Behavior

Error on client screen and console.

![image](https://github.com/user-attachments/assets/c2a86f43-3f4a-4d6f-9209-2b9a7a9bf723)

**Comment by DFreds** [comment]
Thanks for the report. I'll investigate!

**Comment by DFreds** [comment]
Fixed in the next version
