### ISSUE TITLE
[possible bug]

### ISSUE THREAD

**Issue by jtgeraldes** [DFreds/dfreds-convenient-effects#338]
### Describe the Bug

Midi QoL quick rolls are not working after the new version update

### Context

- Foundry V12 / DnD 3.3.1 / MidiQoL

**Comment by jtgeraldes** [comment]
Just a quick add to the behaviour, the quick rolls are completed when no no target is selected, but when there is a target it does not show anything. (MidiQoL starts to behave normally when CE module is deactivated and issue only started to appear after yesterday update to 7.1.0 version)

**Comment by thatlonelybugbear** [comment]
Are you on posney's discord server (the midi-qol discrord)?

If yes, can you create a troubleshooter post in that discord?

If not, can you try to remove all older CEs from any actors you have on the scene and then try again?

**Comment by jtgeraldes** [comment]
I've tried to reproduce the steps. removed all CEs on the active scene and the behavior repeated. Created a new scene, with new actors without CEs on and the behavior also repeated (regardless if the scene is active or not).
For test, also deleted all the Custom CEs I've created from the the menu.
A curious thing, digging a bit deeper. is that the error only happens when targeting other tokens, anything that is self targeted (including weapon attacks on self) works fine

**Comment by jtgeraldes** [comment]
[update] Did more tests today, enabling specific modules, the issue appears to be a conflict on the target resolution when both CE and Alternative Token Cover are enabled - Disable only one of them (no matter which one), fixes the issue with MidiQoL.
Modules Versions:
Midi QOL - 11.5.4
Alterative Token Cover - 0.9.2
DAE - 11.3.52.1
CE - 7.1.0
Foundry v12.331
DnD 5e - 3.3.1

**Comment by jtgeraldes** [comment]
Hi, just an update, Midi 11.6.x does not reproduce the issue anymore.
