### ISSUE TITLE
Probably a bug with applying effects

### ISSUE THREAD

**Issue by NickRimer03** [DFreds/dfreds-convenient-effects#339]
Previously I used V11, and it was very convenient to use macro panel and drag here most commonly used effects from the whole list. I used buttons 0-9 to add and remove effects from tokens.

Pressing button caused an effect to be created on a token. Pressing it again caused an effect to be deleted from a token.

But after I updated to V12 it never works. If I try to apply an effect this token never has, there is a warning message, as an example:
_Your controlled actor 'Commoner' does not have an Active Effect with name 'Invisible'._

The script in macro is: dnd5e.documents.macro.toggleEffect("Invisible")

How it possible to return previous behavior?

Everything works fine if you previously put such an effect manually on a token. But it takes a lot of time if we speak about common effects I have to use quickly.

**Comment by DFreds** [comment]
This is a known "bug", and there isn't really anything I can do. It's because the dnd5e system also creates a macro when you drag an ActiveEffect onto the macro bar. In reality, two macros are being created; my macro and the dnd5e macro. The dnd5e macro is taking priority in the slot when dragging it in. You'll find both macros if you open the macro directory.

**Comment by NickRimer03** [comment]
@DFreds Thank you for the answer.

I'm sorry, but can you tell me exactly when I should look for the correct macro code? I'm not sure that I understand correctly where this directory is located and what kind of files or/and data I have to look for.

**Comment by DFreds** [comment]
Next to the hotbar is a little folder icon. Click that and you'll see all macros created for the world

**Comment by Spawn3601** [comment]
It is most def an issue with the way it currently creates macros I have found a work around.

As an example I'll use the Torch code

dnd5e.documents.macro.toggleEffect("Torch") - This is the Macro that is created when it is drag and dropped instead use this as a template for V12

game.dfreds.effectInterface.toggleEffect({ effectId: "ce-torch" })

Replace torch with whatever effect you want to use IE "ce-true-strike", "ce-charmed". This seems to have done the trick
