### ISSUE TITLE
Uncaught Exception when closing a dialog. For example Bardic inspiration

### ISSUE THREAD

**Issue by watermelonwolverine** [DFreds/dfreds-convenient-effects#34]
When clicking on any effect that shows a selection dialog (like Bardic Inspiration) and then clicking the close button instead of the "Select Effect" button an uncaught exception in logged in the console:

Uncaught (in promise) Error: The Dialog prompt was closed without being accepted.
    at Object.close (foundry.js:20563)
    at Dialog.close (foundry.js:20461)
    at Object.onclick (foundry.js:2272)
    at HTMLAnchorElement.<anonymous> (foundry.js:2183)
    at HTMLAnchorElement.dispatch (jquery.min.js:2)
    at HTMLAnchorElement.v.handle (jquery.min.js:2)

  | close | @ | foundry.js:20461
  | onclick | @ | foundry.js:2272
  | (anonymous) | @ | foundry.js:2183
  | dispatch | @ | jquery.min.js:2
  | v.handle | @ | jquery.min.js:2
  | async function (async) |   |  
  | onEffectClick | @ | convenient-effects-controller.js:179
  | dispatch | @ | jquery.min.js:2
  | v.handle | @ | jquery.min.js:2

**Comment by DFreds** [comment]
Thanks for bringing this to my attention. It should cause no issues despite doing this, but I will look into fixing it so an error isn't shown.

**Comment by DFreds** [comment]
Fixed in v1.8.5
