### ISSUE TITLE
Restore "Toggle as Status Effect" Functionality

### ISSUE THREAD

**Issue by valqueerie** [DFreds/dfreds-convenient-effects#341]
### Is your feature request related to a problem? Please describe.
There is no problem or bug. Rather, this was a feature included in previous versions of the module (along with a few other settings, such as allowing players to create their own effects, toggling settings for chat cards, etc). 

### Describe the solution you'd like
I would love for the "Toggle as Status Effect" functionality to be restored, as — in conjunction with Token Action HUD — it greatly streamlined my workflow during combat. 

### Describe alternatives you've considered
I have used the keyboard shortcut to bring up the Convenient Effects window. 

### Additional context
![image](https://github.com/user-attachments/assets/32b993b0-aab0-4038-8f2f-95e156b698b9)
![image](https://github.com/user-attachments/assets/8c9bc152-e1fe-4ea3-b069-d49c44394d91)

Thank you for all of the work that you do!

**Comment by DFreds** [comment]
Won't do. Foundry makes this very difficult to do and maintain
