### ISSUE TITLE
When the the shield spell effect is deleted an error message is shown.

### ISSUE THREAD

**Issue by watermelonwolverine** [DFreds/dfreds-convenient-effects#35]
Showcase:
https://user-images.githubusercontent.com/29666253/129347904-5a982b7f-84aa-4c0b-8769-132ab1056cab.mp4

Only encountered this problem with the shield spell effect which led me to believe the cause of the problem might be here.

Active modules:
![Activate Modules](https://user-images.githubusercontent.com/29666253/129347267-5e8a85ee-4835-40b9-86b2-3e499296d6f9.PNG)

**Comment by DFreds** [comment]
Interesting... Thanks for the nice video. Are you on the latest times-up/DAE/midi or whatever other modules you use?

**Comment by DFreds** [comment]
After investigating, I don't believe this is an inherent issue from Convenient Effects. I investigated and posted a bug report here: https://gitlab.com/tposney/times-up/-/issues/11
