### ISSUE TITLE
Add a "restore to defaults" button

### ISSUE THREAD

**Issue by BrotherSharper** [DFreds/dfreds-convenient-effects#351]
### Is your feature request related to a problem? Please describe.
When I was creating a new world and importing settings, convenient effects somehow ended up being lost in the process. I now have a world with no default convenient effects. I was able to export and import the folders in the new world, but that got me thinking about a "restore to defaults" button.

### Describe the solution you'd like
A button in the settings menu that when clicked, removes all existing convenient effects data from the world and sets it to the default state as if the module was freshly installed.

**Comment by DFreds** [comment]
This button already exists in the backup app. Open the app, click view backups, then click the refresh button

**Comment by DFreds** [comment]
https://github.com/DFreds/dfreds-convenient-effects/wiki/User-Guide#restoring-backups
