### ISSUE TITLE
Flanking effect not applying bonus

### ISSUE THREAD

**Issue by Klausweb61** [DFreds/dfreds-convenient-effects#353]
I recently tried to implement a change to flanking and changed the Flanking effect from granting advantage to providing +2 to melee attack rolls. The effect applies normally (integrated through midi-qol) but doesn't provide the attack bonus.

My Foundry Version is 12.331 and I am using DND 5e Version 3.3.1

The formula used for the attack role bonuses:
flags.midi-qol.grants.attack.bonus.mwak  Add  +2
flags.midi-qol.grants.attack.bonus.msak  Add  +2

The midi-qol setting for flanking is
Check Flanking:       Convenient Effect Flanking Only

However the attack bonus does not get applied even with different weapons or actors.
Is there any possible change i can make to the formula to add the attack role bonuses?
Thanks in advance for the help

**Comment by DFreds** [comment]
This is a bug in midi, not in CE.
