### ISSUE TITLE
Add effects for Spiritual Weapon and Command

### ISSUE THREAD

**Issue by watermelonwolverine** [DFreds/dfreds-convenient-effects#37]
I don't know how out of scope these requests are. Spiritual Weapon would be especially great.

**Comment by DFreds** [comment]
Command is easy enough and I can add that. Spirit Guardians is a little bit different, because it's essentially an aura that does damage and effects movement speed.. I'd recommend you use Active Auras if you want a good implementation of that.

**Comment by watermelonwolverine** [comment]
I meant Spiritual Weapon (not spirit guardian). I'm too lazy to keep track of how long it still lasts so a simple 10 turn timer would already be great.

**Comment by DFreds** [comment]
Oh, no idea how I read that wrong. Okay. That is probably doable

**Comment by DFreds** [comment]
Added in v1.8.6
