### ISSUE TITLE
Enable to work with SW5e system

### ISSUE THREAD

**Issue by gravagehulk** [DFreds/dfreds-convenient-effects#38]
Star Wars 5e is a system that uses the DnD5e rule system. Many modules that work with 5e also work with SW5e by default, but it seems like they sometimes have to be enabled in the code. The system uses a lot of the same effects as 5e (minus the spells, obviously). MidiQoL works in the system, for example.

Is there any way you can enable Dfreds to work with it in one of your next updates? It would be super useful even to just use the effects that apply (prone, blind, etc) understanding that there will be a bunch of effects that don't apply (5e spells, etc)?

Thanks.

https://github.com/unrealkakeman89/sw5e

**Comment by DFreds** [comment]
Sure. I love the SW5e system... ran a campaign it in myself. This support will probably be "as is" though. The current PR (#33) will probably make it easier for system specific effects.

**Comment by DFreds** [comment]
Added in v1.8.6
