### ISSUE TITLE
Add support for Tasha’s Hideous Laughter

### ISSUE THREAD

**Issue by Oshcakes** [DFreds/dfreds-convenient-effects#39]
This seems like a pretty common spell, at least at my tables.

_A creature of your choice that you can see within range perceives everything as hilariously funny and falls into fits of laughter if this spell affects it. The target must succeed on a Wisdom saving throw or fall prone, becoming incapacitated and unable to stand up for the duration. A creature with an Intelligence score of 4 or less isn’t affected.

At the end of each of its turns, and each time it takes damage, the target can make another Wisdom saving throw. The target has advantage on the saving throw if it’s triggered by damage. On a success, the spell ends._

**Comment by DFreds** [comment]
Added in v1.8.6
