### ISSUE TITLE
Firefox:  Fails to add certain status effect images to the token - Uncaught (in promise) Error

### ISSUE THREAD

**Issue by git-kor-av** [DFreds/dfreds-convenient-effects#40]
Foundry 0.8.8
DFred's Convenient Effects 1.8.6
Firefox 91.0 (64-bit) on Windows 10

When attempting to add "Cover (Half)", "Cover (Three-Quarters)", "Dodge", "Reaction", or "Ready" to the token via DFred's Convenient Effects, the status effect does not appear.  

**Important:**
- It only happens with the listed effects, all other effects work without fail.  
- It also seems to work fine on the Windows Edge browser, so it's safe to assume that it works for Chrome as well.
- If you do not remove this status effect (meaning the one that doesn't appear) and then log out, it actually causes a critical failure using Firefox when you attempt to load any map with this token on it.  The error appears as a red banner on the top:  "Canvas drawing failed for the TokenLayer"

The developer console shows the following error (included part of the screen to show the application and lack of status effect):
![Screenshot 2021-08-16 152331](https://user-images.githubusercontent.com/32276185/129619313-31dbc4d6-1d98-4418-8e04-8f37f579ea11.png)

**Comment by git-kor-av** [comment]
In the case of the 3rd bullet point above involving the "Canvas drawing failed for the TokenLayer", the following error can be seen:
![Screenshot 2021-08-16 154109](https://user-images.githubusercontent.com/32276185/129620317-3f426694-79ed-4a82-a457-eeef634cf01e.png)

The only solution to fix this problem is to use Edge/Chrome, remove the "missing effect" and then you can login with Firefox again.

**Comment by DFreds** [comment]
Fixed in v1.8.7. Sorry about that... It had to do with the way the icons were exported from game-icons.net. 🤷
