### ISSUE TITLE
Anyway to add Twilight Cleric - Twilight Sanctuary?

### ISSUE THREAD

**Issue by valdier1** [DFreds/dfreds-convenient-effects#42]
I would like to see an effect that applies a 30' dim light radius on the cleric itself

Then apply an effect to all allies within 30'. The effect adds 1d6+ Cleric Level temp hp's at the end of the round. If there is a fear condition on the character it can prompt to remove the fear condition rather than add temp hp's.

**Comment by DFreds** [comment]
Unfortunately I can't do this as it is not part of the DnD 5e SRD. Adding it would break the licensing
