### ISSUE TITLE
Custom Effects can't be created

### ISSUE THREAD

**Issue by MSAbaddon** [DFreds/dfreds-convenient-effects#43]
Hi there,
I just tried to create some custom effects. Unfortunately, as soon as I modify an existing custom effect or even do a page reload the previously created effects vanish from the menu.

**Comment by DFreds** [comment]
Hi, can you give more detailed step by step instructions on how to reproduce this? I'm not seeing any issues.

**Comment by DFreds** [comment]
Also, if it isn't too big of a deal, delete the Custom Convenient Effects item in the items directory. The next time you click Create Effect, it should regenerate it. I'm not sure how that could have gotten messed up though

**Comment by MSAbaddon** [comment]
Ok, did some more testing. It actually does not create any effects permanently. Even if I only click on "Create Effect", give a name and Submit, the effect vanishes as soon as I reload the page. Tested both on Forge and a local installation and also tested with all modules except deactivated except your module, libWrapper and socketlib.

Can you tell me where you store the data for the created custom effects? I'll have a look if those entries are created at all.

**Comment by DFreds** [comment]
They are stored on the Custom Convenient Effects item in your items tab. Of note, if you don't change the name from "New Effect" and don't add any changes, it's considered invalid and I don't show it.

**Comment by MSAbaddon** [comment]
![image](https://user-images.githubusercontent.com/66370966/130337838-fa1b62fb-ccaf-40b6-9a1e-daf8dc1f1c36.png)

After page reload:
![image](https://user-images.githubusercontent.com/66370966/130337852-9fe2e94a-bc2d-437c-bbef-98d9d0cd2139.png)

**Comment by MSAbaddon** [comment]
Maybe this helps. Once the custom effect is defined, updating it makes it invalid, because it's name is on the list of existing effects?
![image](https://user-images.githubusercontent.com/66370966/130337881-18f69fb6-4298-4526-b52c-cc843cf7b69a.png)

**Comment by DFreds** [comment]
Ah okay, I see why now. Thanks, I'll have this fixed soon

**Comment by DFreds** [comment]
Fixed in v1.9.1

**Comment by MSAbaddon** [comment]
Great, thanks :-)
