### ISSUE TITLE
macro.tokenMagic Effects get duplicated 

### ISSUE THREAD

**Issue by Ikabodo** [DFreds/dfreds-convenient-effects#44]
**Describe the bug**
macro.tokenMagic Effects get duplicated in a custom effect each time it is applied. 

**To Reproduce**
1. Create new Custom effect with `macro.tokenMagic `and any effect.
2. Click on a token
3. Apply the effect, then toggle it off again.
4. Edit the Convenient Effect and see that `macro.tokenMagic is now duplicated.

**Expected behavior**
macro.tokenMagic should not duplicate.

**Screenshots**
![image](https://user-images.githubusercontent.com/7766890/130451016-5ed4cc9b-410e-4e36-80fe-9739e7c559e3.png)

**Additional context**
Happens with only Convenient Effects mod, libwrapper, socketlib and token magic active.

**Comment by DFreds** [comment]
Good find, thanks for reporting it. I'll fix it

**Comment by DFreds** [comment]
Fixed in v1.9.2
