### ISSUE TITLE
Eyes of Night - special Darkvision

### ISSUE THREAD

**Issue by gravagehulk** [DFreds/dfreds-convenient-effects#47]
Hello, it's me again. You got Darkvision working and I appreciate that. Is there any way to get "Eyes of Night" added? It's a special version of Darkvision (300 feet!) from a Cleric class in Tasha's and it's a pain to deal with. I currently have a player that has it and he can grant it to the rest of the party. That means updating the tokens temporarily and then restoring later. Your module is perfect for something like that. Here's the full text on Eyes of Night:

Eyes of Night
Starting at 1st level, You can see through the deepest gloom. You have darkvision out to a range of 300 feet. In that radius, you can see in dim light as if it were bright light and in darkness as if it were dim light.

As an action, you can magically share the darkvision of this feature with willing creatures you can see within 10 feet of you, up to a number of creatures equal to your Wisdom modifier (minimum of one creature). The shared darkvision lasts for 1 hour. Once you share it, you can't do so again until you finish a long rest, unless you expend a spell slot of any level to share it again.

**Comment by DFreds** [comment]
That is non-SRD, which means I cannot add it. However, you can add it pretty easily as a custom effect if you're using ATL. It would be something like:

Name as Eyes of Night
Pick an Icon.

Add an effect, something like this
Key                     Mode             Value
ATL.dimVision    UPGRADE     300

Set the duration to 3600 seconds.

**Comment by gravagehulk** [comment]
Ah, thanks, man. Sorry, I totally spaced on the SRD angle. Appreciate the help!
