### ISSUE TITLE
Suggestion for implement the "data.traits.size" like effect

### ISSUE THREAD

**Issue by p4535992** [DFreds/dfreds-convenient-effects#5]
Maybe is not the best idea, but we can use the module [Active-Token-Lighting](https://github.com/kandashi/Active-Token-Lighting)  for the integration of the "data.traits.size" and add these effect for example to the enlarge spell  :

    { key: "ATL.height", mode: CONST.ACTIVE_EFFECT_MODES.MULTIPLY, value: "2", priority: 40},
    { key: "ATL.width", mode: CONST.ACTIVE_EFFECT_MODES.MULTIPLY, value: "2", priority: 40},

**Comment by DFreds** [comment]
I actually had my own idea for that, but I wasn't aware that Active Token Lighting did that as well. I was planning on integrating with that in the future to do things like Light. I'm not sure I'll want to take this part of active token lighting or do my own yet. Either way, good suggestion!

**Comment by p4535992** [comment]
Solved with https://github.com/DFreds/dfreds-convenient-effects/commit/477495c4ae6af91845c19553d5766c6cb68c25b8 i think.
