### ISSUE TITLE
Include special duration for 5e Channel Divinity: Turn Undead

### ISSUE THREAD

**Issue by TrikyEMF** [DFreds/dfreds-convenient-effects#55]
**Is your feature request related to a problem? Please describe.**
The duration of the Channel Divinity: Turn Undead is set to a minute, however by RAW the effect also ends if the creature is damaged.
![image](https://user-images.githubusercontent.com/8931258/131688210-64448162-2aed-473f-bc9b-7eb883330b67.png)

**Describe the solution you'd like**
Include the special duration in the effect:
![image](https://user-images.githubusercontent.com/8931258/131688297-ed59a0a9-0833-4bba-b9ed-3adacadbf993.png)

Thank you!

**Comment by DFreds** [comment]
Added in v1.10.1
