### ISSUE TITLE
Unable to remove effects (5e)

### ISSUE THREAD

**Issue by Quixion** [DFreds/dfreds-convenient-effects#56]
When an applied condition expires or is manually deactivated, the effect remains on the actor and it displays this error
![image](https://user-images.githubusercontent.com/59381562/132134787-ed7edfdb-c823-4fb8-a98c-1bf14cb5f726.png)
The mechanical effects of the condition are removed, but the condition and any lighting or magic effects remain until the application is reloaded. 

This seems to happen with any of the conditions that apply any change to the actor. Conditions that simply display a status icon on the token don't always have this issue.
I've tried deactivating the other installed modules one by one but CE seems to be the only thing that I can disable to remove the problem. I've not tried this in any other systems outside of 5e. Here's the list of my active modules.

> Active Modules:
> ----------
> 5E Custom Currency v1.3.5;
> 5e-Sheet Resources Plus v1.6.11;
> About Time v1.0.4;
> Ace library v1.2.0;
> Active-Auras v0.3.06;
> Active Token Lighting v0.2.17;
> Actor Attribute Lists v0.0.5;
> Advanced Macros v1.9;
> Autocomplete Whisper v0.3.3;
> Automated Animations v0.5.56;
> Better Roll Tables v1.8.3;
> Better Roofs v0.9.9.1;
> Boss Bar v0.7.6;
> Caeora's Maps, Tokens, and Assets v1.0.4;
> Calendar/Weather v3.1.7;
> CodeMirror v5.58.3-fvtt3;
> Combat Booster v1.7.6;
> Combat Focus v1.4.1;
> Combat Numbers v1.1.5;
> Combat Utility Belt v1.6.2;
> Compendium Browser v0.6.0;
> Compendium Folders v2.3.53;
> Condition Automation v3.0.2;
> Copper Dragon's Hoard v0.1.4;
> Custom Pause v1.0.1;
> Custom Token Animations v0.2.51;
> Cycle Token Stack v0.5.4;
> DF Chat Enhancements v3.3.0;
> DFreds Convenient Effects v1.10.1;
> DFreds Droppables v1.2.9;
> Dice So Nice! v4.1.4;
> Dice Tray v1.2.1;
> DnD5e Helpers v3.0.1;
> Drag Ruler v1.8.1;
> Dynamic Active Effects SRD v6.0.01;
> Dynamic effects using Active Effects v0.8.48;
> Enhanced Terrain Layer v1.0.32;
> Fantasy Plants Compendium v1.0.0;
> Find the culprit v1.4.0;
> Forien's Unidentified Items v0.2.5;
> Foundry Community Macros v0.46.0;
> Foundry Community Tables v0.17.0;
> Frag Maps - Modern, Cyberpunk and Sci-Fi Maps v1.0.0;
> Fudge v1.1.1;
> FXMaster v1.2.1;
> Game Audio Bundle 1 v2.3;
> Game Audio Bundle 2 v2.4;
> Game Audio Bundle 3 v2.3;
> Game Audio Bundle 4 v2.4;
> Game-icons.net v0.0.12;
> GM Notes v0.4.1;
> Hook Macros v1.3.3;
> Initiative Double Click v1.1;
> Innocenti Open Lock v0.4.3;
> Item Containers v1.8.5;
> Item Macro v1.5.5;
> Jack Kerouac's Animated Spell Effects v0.6.8;
> Jack Kerouac's Animated Spell Effects: Cartoon v0.1.9;
> Jack Kerouac's Animated Tokens v0.2.2;
> JB2A - Patreon Complete Collection v0.2.6;
> Jinker's Animated Art Pack v0.6;
> Less Fog v0.8.5;
> Let Me Roll That For You! v1.17;
> Let's Trade 5e v0.3.0;
> Levels v1.8.9.2;
> lib - Color Settings v2.8.0;
> Library: Chat Commands v1.3.3;
> Library: DF Hotkeys v2.3.5;
> libWrapper v1.10.3.0;
> Loot populater NPC | 5e v0.2.2;
> Loot Sheet NPC 5e v3.1.0;
> Lordu's Custom Dice for Dice So Nice v0.33;
> Louder Whispers v1.2.0;
> Macro Editor v1.0.9;
> Magic Items v2.1.2;
> Math.js v7.5.1-fvtt2;
> Midi QOL v0.8.49;
> Minimal UI v1.0.5;
> Monk's Enhanced Journal v1.0.21;
> Monk's TokenBar v1.0.51;
> Multilevel Tokens v1.5.2;
> Narrator Tools v0.61;
> Nice More Dice v1.0.3;
> Ouija board for Sequencer v0.0.4;
> Perfect Vision v2.9.7;
> Permission Viewer v0.8.10;
> Pings v1.2.12+0.8.6;
> Plutonium v1.37.0;
> Polyglot v1.7.13;
> Quick Encounters v0.8.4;
> Roll From Compendium v1.1.2;
> Scene Backup Tool v1.0.3;
> Select tool everywhere v1.2.0;
> Sequencer v0.6.12;
> Settings Extender v1.1.6+0.8.6;
> Short Rest Recovery for 5E v0.4.2;
> Simple Calendar vv1.3.28;
> Smart Target v0.6.5;
> socketlib v1.0.9;
> SortableJS v1.10.2-fvtt1;
> SoundBoard by Blitz v1.5.2;
> SoundBoard Pack - Blitz Free Pack v1.0.0;
> SoundBoard Pack - Community v1.0.0;
> SoundFx Library v1.0.1;
> Speller - An integrated spell checker vv0.1.4-beta;
> Spells, Items, and Features Toolkit v0.1.28;
> Split Journal v1.1;
> Summoner v0.1.4;
> Switch to Chat v1.1.1;
> Tabbed Chatlog v1.6.3;
> Tabletop RPG Music v1.3.0;
> Template Wall Collision v1.0.3;
> Terrain Ruler v1.4.0;
> The Furnace v2.6.1;
> The Vault of Terror: Enter... If You Dare! v1.0.0;
> Those Who Come Next v0.3.1-alpha;
> Tidy5e Sheet v0.5.14;
> Tidy UI - Game Settings v0.1.25;
> times-up v0.8.12;
> Token Health v0.4.4;
> Tokenizer v3.4.8;
> Token Magic FX v0.5.2.1;
> Token Mold v2.13.1;
> Token Tooltip Alt v3.0.3;
> Token Variant Art v1.11.0;
> Trigger Happy v0.8.8;
> Universal Battlemap Importer v2.2.0;
> Variant Encumbrance+Midi v0.4.4;
> Vehicles and Mechanisms v0.4.0;
> Wall Cutter v1.1.1;
> Wall Height v3.5.3.9;
> Wallter v0.1.5;
> Weather Blocker v0.6.3;

**Comment by DFreds** [comment]
Deactivated how? By toggling the effect via the app or removing the effect directly from a character sheet? I'll try to reproduce this though.

**Comment by Quixion** [comment]
Toggling via app, removing from the sheet directly, and timed effect expiration. I've been getting it via those means. 
It looks like I can get the effects to go away without error about 1/2 the time if I set them via the active effect "Macro dar.CE", but if I have literally anything else on the item, another effect, item macro, healing effect, basically anything, it will give me those errors again

**Comment by DFreds** [comment]
I am not able to reproduce this issue. You have a lot of modules, so it's possible something is conflicting. I see that you have the Find the Culprit module. Can you try using that and see if it narrows it down?

**Comment by Quixion** [comment]
Disabling item macros reduces but doesn't eliminate the issue. I'll keep digging though

**Comment by Quixion** [comment]
I still have no idea _what_ is causing it, but it looks like effects are being applied twice at the same time. One is invisible, which is to say that I don't see any indication of a second effect application outside the fact that it's acting like it's applied twice. I'm still running through permutations of modules.

**Comment by Quixion** [comment]
It's advanced macros/furnace. I think.

**Comment by DFreds** [comment]
Hm, I use advanced macros and automated animations in my own game and haven't had this issue. That would be surprising? It could be a combination of a few modules though...

**Comment by Quixion** [comment]
Yeah I'm wrong. I give up, nothing I disable seems to fix it. Guessing it's something outside of foundry

**Comment by DFreds** [comment]
Is this a brand new world or an old world?

**Comment by DFreds** [comment]
Feel free to respond and I can possibly help. Otherwise, this doesn't appear to be an issue with CE

**Comment by Quixion** [comment]
It's a 7.x world. I've been able to replicate the issue without CE installed now so it's definitely something more fundamental. I'm not sure why it's easier to trigger the issue with CE installed. I'm stepping away from it all for now, my sanity needs a recharge. Thank you for the help though!

**Comment by thatlonelybugbear** [comment]
The error you get @Quixion is one encountered in many situations in Foundry 0.8.x. 

It is triggered by race conditions desyncing server side and client side. Deletion of many active effects at the same time is a trigger.

It is supposed to be fixed in v0.9.x of Foundry, so this means we have to live with that for the time being. When the error occurs a reload should fix it.

Similar issues https://gitlab.com/foundrynet/foundryvtt/-/issues/5312 and https://gitlab.com/foundrynet/foundryvtt/-/issues/5309

**Comment by DFreds** [comment]
@thatlonelybugbear is probably right (thank you).

Unfortunate, but I hope it isn't too game breaking for you. If you could, can you check if it also happens in a brand new world for you? It's also possible some weird migration happened.

**Comment by Quixion** [comment]
Y'all saved me so much mental anguish with this just now 😭 thank you so much for the update

**Comment by Quixion** [comment]
> @thatlonelybugbear is probably right (thank you).
> 
> Unfortunate, but I hope it isn't too game breaking for you. If you could, can you check if it also happens in a brand new world for you? It's also possible some weird migration happened.

Confirmed to happen in a new world without any modules

**Comment by DFreds** [comment]
> > @thatlonelybugbear is probably right (thank you).
> > Unfortunate, but I hope it isn't too game breaking for you. If you could, can you check if it also happens in a brand new world for you? It's also possible some weird migration happened.
> 
> Confirmed to happen in a new world without any modules

Very strange. My only other suggestion would to do a full reinstall of foundry, to ensure that the underlying framework is also updated. You should maybe back up your user data to be safe, but it shouldn't effect it at all.

**Comment by DFreds** [comment]
Did you do the full reinstall of foundry on the computer with issues and still had the problem?

**Comment by Quixion** [comment]
Yeah, but I'm giving it another go. Same computer, different destination install

**Comment by Quixion** [comment]
hmm, well, as long as I have no modules enabled it seems to be ok. Haven't tested any macros or anything more complicated than applying and unapplying a status marker to an actor but that works now so I'll take it until the core update and move from there.
Thanks again!
