### ISSUE TITLE
Icon disappeared from left side menu?

### ISSUE THREAD

**Issue by Heljspe** [DFreds/dfreds-convenient-effects#58]
**Describe the bug**
The icon in the menu to launch the list of effects has disappeared. 

**Screenshot**
![image](https://user-images.githubusercontent.com/68180128/132665103-38af02c3-0ef1-4e62-9eb6-174e73a500e0.png)

**General Info**
Foundry v0.8.9
DnD5e v1.4.3
DFreds Convenient Effects v1.10.2;
libWrapper v1.10.5.0;
socketlib v1.0.9;

**Comment by DFreds** [comment]
You have a lot of buttons over there... Can you check if the console has any errors? You can press F12 to open it, then just reload the game with it open. Usually this will happen if something fails to initialize.

**Comment by NerdyViking** [comment]
Hey DFreds, same issue here. I have all mods disabled and all the same versions as the OP.
![Screenshot 2021-09-10 125051](https://user-images.githubusercontent.com/63491456/132791627-73588099-5ef5-4e71-84cd-ab7e203c5499.png)

**Comment by DFreds** [comment]
@NerdyViking can you check your settings and look at the controls permission? I'm not sure why it would've changed but you can technically disable those modules.

I just made a new world and had no issues. Also, I can't tell from your console output if there were any errors from that screenshot.

![image](https://user-images.githubusercontent.com/11878569/132794496-fa841e42-2c8b-48cd-84ae-46e508bc2699.png)

**Comment by NerdyViking** [comment]
It doesn't even give the options to adjust module settings.
![image](https://user-images.githubusercontent.com/63491456/132794711-d47f17ff-fc88-4abb-a7fd-ac5ede54642a.png)

I've also disabled libwrapper and it still doesn't show up, and it won't let me disable socketlib.

**Comment by DFreds** [comment]
😕  very confusing. Can you scroll to the very top of the console log (load the world with it open) and see if there is any red errors?

**Comment by NerdyViking** [comment]
I figured it out! I had to manually go into the data/modules directory and delete the folder. Then I reinstalled it and it works fine....no idea why as I have never gone in there before haha

**Comment by DFreds** [comment]
That's still very strange. That unfortunately doesn't make me feel any better about it. @Heljspe if you could scroll to the top of your console log when you reload, let me know if you see any red. All of these controls/settings not even appearing is telling me that the module failed to initialize, and there should be something in the log about that.

**Comment by NerdyViking** [comment]
Addendum, I checked the console log and there were no errors on my part. Didn't even try to load the module, let alone fail to load it.

**Comment by DFreds** [comment]
Ah okay, thanks for the clarification. I have no clue what could've happened there. Something got messed up with your data, but I'm confident it shouldn't be because of the module. 🤷 Sounds like you can delete it and reinstall it @Heljspe

**Comment by Heljspe** [comment]
Yea, I'll go check it now. I had the same issue - the settings wouldnt appear in the Module Settings, I did try disabling and re-enabling but that didn't work. I'll go grab a console screen-shot before I try NerdyViking's method. :)

**Comment by Heljspe** [comment]
![image](https://user-images.githubusercontent.com/68180128/132802474-9720fb3d-e8ca-4eae-897d-495c6f6a7c19.png)
![image](https://user-images.githubusercontent.com/68180128/132802586-610cf48d-a9c6-4e78-9c22-1278c87c80c3.png)

I guess that explains why Droppables wasn't working either then. :p Saves me putting a bug post up there.

**Comment by DFreds** [comment]
Oh, crazy. I guess the shim isn't working right? I'll have to update it and see if it fixes it for you. Thanks for the log info.

**Comment by DFreds** [comment]
I updated the shim in v1.10.3. I'm not quite sure this is the error or not, but let me know.

**Comment by Heljspe** [comment]
Yay! 
Both Convenient Effects and Droppables are working now. Ty! :D
