### ISSUE TITLE
Integration with Tidy5e Sheet Auto Exaustion

### ISSUE THREAD

**Issue by dirusulixes** [DFreds/dfreds-convenient-effects#60]
**Is your feature request related to a problem? Please describe.**
Tidy5e Sheet offers the possibility to leverage CUB instead of its own internally coded AE for exustion. I'd like an option to exist also to use CE if present.

**Describe the solution you'd like**
a PR mostly focused on [this](https://github.com/sdenec/tidy5e-sheet/blob/b4e066a59f99342bf355125f72039c6418a31e6b/src/scripts/tidy5e-sheet.js#L121) and the relative module settings

**Describe alternatives you've considered**
Cross-referencing my feature request against Tidy5e directly [#408](https://github.com/sdenec/tidy5e-sheet/issues/408#issue-980689883 )

**Comment by DFreds** [comment]
Good suggestion. I never used that feature on Tidy and didn't know it integrated with anything. I'll leave this open here until sdenec gets a chance to provide their input.

**Comment by DFreds** [comment]
Stale, no input from Tidy so 🤷
