### ISSUE TITLE
Icon of duplicated custom effects not shown as status effect on the token HUD

### ISSUE THREAD

**Issue by dirusulixes** [DFreds/dfreds-convenient-effects#61]
**Describe the bug**
Duplicated custom effects marked as status effects are applied correctly, but the icon shown on the hud is the one from the default effect.
fvtt 0.8.9
CE 1.11.0 + deps
no other modules active

**To Reproduce**

For example
1. Duplicate Exhaustion 1
2. Change the icon of the custom version
3. Reload fvtt
4. Open the status effects HUD 
5. See that the icon shown for Exhaustion 1 is the one of the default effect
6. Toggle Exhaustion 1 on the token
7. See that the icon on the token is the one from the duplicated custom Exaustion 1 effect

**Expected behavior**
Icons of duplicated custom effects marked as status effects should be shown in all instances

**Screenshots**
![image](https://user-images.githubusercontent.com/5693623/133466108-27cea457-891f-4327-87b7-e1997ffc4b83.png)

**Comment by DFreds** [comment]
Hm, good find. I'll fix it

**Comment by DFreds** [comment]
Fixed in v1.11.1
