### ISSUE TITLE
Guidance not applying +1d4 rolls, have to manually change effect

### ISSUE THREAD

**Issue by whenbearsreign** [DFreds/dfreds-convenient-effects#64]
The flags.midi-qol.optional.guidance.skill effect modifier needs to be manually changed to data.bonuses.abilities.skill in order to get the +1d4 to work properly. This might be due to a [recent change](https://gitlab.com/tposney/dae/-/blob/master/Changelog.md) in DAE.

**Comment by DFreds** [comment]
Okay, thanks for letting me know. I'll look into it

**Comment by DFreds** [comment]
I'm unable to reproduce this issue. When a skill is rolled, a dialog appears with the result and then asks if guidance should be applied.

**Comment by DFreds** [comment]
Feel free to respond with specific steps if it keeps happening for you. Otherwise, it might be some other module interfering with the midi-qol workflow
