### ISSUE TITLE
Allowing Adv/Disadv and modifier input when Bardic Inspiration is enabled

### ISSUE THREAD

**Issue by franckflo** [DFreds/dfreds-convenient-effects#65]
**Is your feature request related to a problem? Please describe.**
When Bardic Inspiration is enabled on a token, rolling an ability or attack bypasses completely the popup asking for modifiers (advantage/disadvantage and manual input for a modifier). 

**Describe the solution you'd like**
I would like the bardic inspiration to still allow that window to popup, then the badic inspiration window would popup after the result is displayed, showing the total result and asking if the player wants to spend the bard inspiration to change the result.

**Describe alternatives you've considered**
Do not bypass the roll adjustment window before the roll. I'm not sure if other Convenient effects work the same way, but it would be nice if the same solution was applied to the others. 

**Additional context**
I use Midi-QOL

**Comment by DFreds** [comment]
This really isn't a Convenient Effects bug. This is a midi-qol bug as the workflow being used is provided by midi. Post something here: https://gitlab.com/tposney/midi-qol/-/issues
