### ISSUE TITLE
Ability to change the images / Token Magic

### ISSUE THREAD

**Issue by w1face** [DFreds/dfreds-convenient-effects#66]
Pretty much as it suggests!  The ability to change what the images look like, and what the Token Magic effects look like.

For example, I don't want the Faerie Fire Token Magic, as I use a different look... but I love the auto advantage, and I'm happy with the Token Magic on other effects.

**Comment by DFreds** [comment]
You can duplicate any effect and change it yourself by right clicking the effect in the list. But I'm also willing to listen to suggestions for different effects. Currently, there is no support for modifying existing effects.

**Comment by w1face** [comment]
Perfect!  Thanks!

**Comment by DFreds** [comment]
Let me know what you choose for the token magic effect. I might change the defaults if I like it more! I'm down for any suggestions like that

**Comment by w1face** [comment]
I Patreon JBs Animations, so use those!
