### ISSUE TITLE
Shield duration incorrect

### ISSUE THREAD

**Issue by Rabulias** [DFreds/dfreds-convenient-effects#71]
**Describe the bug**
Shield is set to last 6 seconds, but per the spell description text it should last until the start of the caster's next turn. I have modified this in a custom copy.

Steps to fix the behavior:
1. Open Shield Active Effect.
2. Click Duration tab.
3. Clear Effect Duration (Seconds) field.
4. Click Special Duration dropdown list.
5. Select "Turn Start: Expires at the start of the character's next turn (in combat)."

Thanks!

**Comment by DFreds** [comment]
I'm not sure I understand. The default duration is 6 seconds because that is the length of a turn. If you apply Shield outside of combat, it lasts 6 seconds and then expires (assuming times-up and dependencies). If you apply Shield during combat, it expires when it reaches that player's next turn. Again, times-up handles that logic of 6 seconds == until next turn.

**Comment by Rabulias** [comment]
I should have been more clear. When I use the default Shield Convenient Effect instead of my custom one, the AC bonus and the TokenMagic FX do not get removed until the _end_ of the caster's turn, when they should be removed at the _start_ of the caster's turn. Do I have something messed up?

**Comment by DFreds** [comment]
I'm assuming something else is messed up. When I run it with the default one, it correctly expires at the start of the turn.

**Comment by Rabulias** [comment]
OK. Apologies for the trouble. I will play around with it more and see if I can isolate where mine is going is wrong. Thanks!

**Comment by GhostwheelX** [comment]
> OK. Apologies for the trouble. I will play around with it more and see if I can isolate where mine is going is wrong. Thanks!

Do you have both the "About Time" and "Times Up" modules installed? That might be the issue.
