### ISSUE TITLE
Aid

### ISSUE THREAD

**Issue by profdresser** [DFreds/dfreds-convenient-effects#75]
**Describe the bug**
Applying the "Aid" effect adds +5 to current HP and adds +5 to _temporary_ Max HP.

**To Reproduce**
1. Open Convenient Effects
2. Select a token
3. Click on "Aid" in the "Spells" folder

**Expected behavior**
I expected +5 to be added to current HP and _general_ Max HP.

**Screenshots**
![Screenshot 2021-10-01 162006](https://user-images.githubusercontent.com/88245061/135687713-859fdb79-43b0-4905-b088-eb003e61fbb6.png)

**Additional context**
N/A

**Comment by profdresser** [comment]
Update: This also occurs with Heroes' Feast.

**Comment by DFreds** [comment]
Yeah, so that's what that is for. Temporary max HP. It should work as intended unless you're seeing something weird
