### ISSUE TITLE
Creation of custom nested effects

### ISSUE THREAD

**Issue by adriangaro** [DFreds/dfreds-convenient-effects#76]
**Is your feature request related to a problem? Please describe.**
I was trying to implement some effects similarly to enlarge/reduce which would have you choose from a sublist. From what I have seen, only predefined effects support that.

**Describe the solution you'd like**
Would be nice to have an easy way to declare nested effects, probably the easiest would be some drag and drop behaviour in convenient effects window over the parent item.

**Describe alternatives you've considered**
I have been able to replicate the effect by programatically setting the `nestedEffects` property on the parent effect, however this is removed on reload/ it is only done locally. One way to make this permanent is to have a local module which does that programatically on `ready` hook which works decently enough, however it is quite the hassle.

**Additional context**
None

**Comment by njharoon** [comment]
So I found a way to do it. Although it does require some work and if you aren't keeping a backup of those changes, it'll get wiped on updates. But easy to add back (assuming you logged the nested effects and all)

**Comment by benbarbour** [comment]
@njharoon How did you do it?

**Comment by njharoon** [comment]
@benbarbour https://www.youtube.com/watch?v=ZV8FXH-hLU8

This is just for informational purposes. So follow the informational video at your own risks

**Comment by the-real-orson** [comment]
> Hm, yeah it's a good idea. A bit harder than it initially sounds. Let me see what I can come up with

I can definitely see how this would be tricky.  I wonder if utilizing the new V10 journal would be a good option.

What if the module created a Journal named 'CE Nested Effects' or some such, and then each page in the journal could be the root name of the effect, for example 'Blindness/Deafness'.  Then additional effects could be drag and dropped onto that page with a conversion process that would copy the effect to your hidden CE Item (or an additional one), replace the UUID with the newly created Item effect, and would act as nested effects of that page title effect.

This way the nested effects could be directly edited by clicking on them in the appropriate page of the Journal.
