### ISSUE TITLE
Question about targets and bane

### ISSUE THREAD

**Issue by Kirin92** [DFreds/dfreds-convenient-effects#77]
Alright. I'm new to all of this and I don't know where to ask. Maybe I'm just dumb.

My problem:
I want to automate the spell Bane, so that the targeted tokens make a charisma saving throw and if they fail, they get the bane effect applied. 
I tried the "Prioritize Targets" option and a macro on use in the spell but doesn't work like I want. 
Time's up and the other modules are also installed and the effect should end after the time runs out or rounds are over.

Is it possible to make that?
Thank you ~

**Comment by DFreds** [comment]
Yeah, it's possible with midi-qol enabled. You should turn that on and the "Apply Convenient Effects" option it its settings.

https://github.com/DFreds/dfreds-convenient-effects/wiki/User-Guide#integrating-with-midi-qol

**Comment by Kirin92** [comment]
:/ unfortunately it does not work. Even if I turn it on, select three targets and insert the macro on use.... the bane icon and effect applies to the caster for some reason.

**Comment by Kirin92** [comment]
yes I read wiki but didn't understand it well. 
But okay. thx for clarification.

**Comment by DFreds** [comment]
If something isn't clear, let me know what you're struggling with. I don't mean to sound unhelpful but I don't know what you're not understanding. Plus, I could help clarify and it might help me make the wiki article better. 

Essentially, all you need to do is enable the midi settings and setup the item to have a saving throw (Bane should already be setup from the dnd5e compendium). Make sure you have midi setup to roll saving throws automatically. Then, target the enemy, cast Bane from the sheet, and you'll see an entry in the chat log saying if they succeeded or failed the saving throw. If they failed, it should apply Bane to them from Convenient Effects.

**Comment by Kirin92** [comment]
xD Omg finally it works... 
The "auto saving throw" was the hint I needed xD 
Thank you!

**Comment by DFreds** [comment]
Good to hear! Midi is complex, so things can be hard to understand. My advice is go through the settings carefully and test them out.
