### ISSUE TITLE
Dragging item on sidebar to favorites tab Create a blank icons and cannot be remove

### ISSUE THREAD

**Issue by golfgkma** [DFreds/dfreds-convenient-effects#8]
Silly me want to add a custom effect and found out , Hey ! I can drag something on sidebar directly to favorites tab . It was a mistake and now I cannot remove these icons  , I'm sorry :'(

![image](https://user-images.githubusercontent.com/40625745/121668983-0e7fca00-cad6-11eb-966d-83dd001f4f77.png)

**Comment by DFreds** [comment]
🤨 That's crazy, never thought to test something like that. Don't be sorry! It's a good bug report. I'll look into it more. In the meantime, you could try uninstalling and reinstalling the module to see if it fixes it.

**Comment by DFreds** [comment]
To be more specific, what exactly did you drag onto the favorites folder?

**Comment by golfgkma** [comment]
>  That's crazy, never thought to test something like that. Don't be sorry! It's a good bug report. I'll look into it more. In the meantime, you could try uninstalling and reinstalling the module to see if it fixes it.

First I've try uninstall & reinstall module it didn't fix this issue ,But it fix when I clear my browser cache 

> To be more specific, what exactly did you drag onto the favorites folder?

I've created an item (Feature) with active effect and drag it into favorites folder , but you can pretty much drag anything from sidebar to it

**Comment by DFreds** [comment]
Thanks for the details. I should be able to fix this relatively easily. Expect it soon!

**Comment by DFreds** [comment]
Fixed in v1.1.3
