### ISSUE TITLE
Shield duration wrong

### ISSUE THREAD

**Issue by Rencos1** [DFreds/dfreds-convenient-effects#80]
**Describe the bug**
Shield effect should be removed at the start of target turn

**To Reproduce**
Cast shield anytime and the effect will be removed at the end of target turn.
**Expected behavior**
Cast shield anytime and the effect will be removed at the beginning of target turn.

get _shield() {
    return new Effect({
      name: 'Shield',
      description: 'Add 5 to AC until next turn',
      icon: 'systems/dnd5e/icons/spells/protect-magenta-1.jpg',
      //seconds: Constants.SECONDS.IN_ONE_ROUND,
      **flags: {
        dae: {
          specialDuration: ['turnStart'],
        },
      },**
      changes: [
        {
          key: 'data.attributes.ac.bonus',
          mode: CONST.ACTIVE_EFFECT_MODES.ADD,
          value: '+5',
        },
      ],
      tokenMagicChanges: [
        {
          key: 'macro.tokenMagic',
          mode: CONST.ACTIVE_EFFECT_MODES.CUSTOM,
          value: 'water-field',
        },
      ],
    });
  }

**Comment by DFreds** [comment]
Thanks! This used to work, so I'm not sure what happened. It'll be addressed in the next update

**Comment by DFreds** [comment]
Fixed in v1.14.1
