### ISSUE TITLE
Make new application of exhaustion level remove any other exhaustion levels

### ISSUE THREAD

**Issue by TaakoMagnusen** [DFreds/dfreds-convenient-effects#83]
**Is your feature request related to a problem? Please describe.**
When an exhaustion level already exists on a token and a new one is applied, the previous one is not cleared, allowing for multiple. exhaustion icons.

**Describe the solution you'd like**
When an of Exhaustion 1-5 is applied to a token, clear any other Exhaustion effects on that token.

**Comment by DFreds** [comment]
Released in v1.14.4
