### ISSUE TITLE
spell in different language

### ISSUE THREAD

**Issue by CaosFR** [DFreds/dfreds-convenient-effects#84]
**Is your feature request related to a problem? Please describe.**
Hi,

I have a request, but, before I would like to know if I understand and use Convenient Effects correctely.
I have the modules Midi-QOL, DEA, Midi-SRD, Token Magic, Active Token Lighting and times up.

When I use a spell like Fire Shield, if the name match in Convenient Effects will add differents effects.
My players says "Ouhaaaaaaaaa", you are the boss, cool :)".

**A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]**

But, I'm french and I translate name and description or use the french compendium (aide-d&d). Nothing match now ! :)
I have try to drag and drop your effect into a spell in the character sheet or in the object tab. Nothing work.

The only way I find is to "Duplicate As Custom" and rename in french. TADA "Ouhaaaaaaaaa" again !
It's a little borring stuff isn't ?

**Describe the solution you'd like**

The possibility to drag and drop your effect into a speel ?

**Describe alternatives you've considered**

May I can translate your module ?

Thanks

**Comment by p4535992** [comment]
I had started something [here](https://github.com/DFreds/dfreds-convenient-effects/pull/52) a while ago, but then I never managed to find the time to go on, free to take the initiative anyway.

**Comment by DFreds** [comment]
I'm not quite sure what you mean here. The french translation of dnd5e doesn't translate any spell names: https://gitlab.com/baktov.sugar/foundryvtt-dnd5e-lang-fr-fr/-/blob/master/dnd5e_fr-FR/fr.json

I would consider supporting it if dnd5e supported it, but until then I won't do it.

**Comment by CaosFR** [comment]
All spell name change; shield of fire become "bouclier de feu", so your module don't work.

**Comment by DFreds** [comment]
Okay, then I'm not sure what is doing that. Are you using the dnd5e french translation module I linked? Because that doesn't have any spells in it... Are you using something else to do it?

**Comment by CaosFR** [comment]
Yes, I use this modules and his babele dependancy. It's add a new compundium called "Sorts (SDR-AideDD) where all spell are a french translate.
