### ISSUE TITLE
custom token magic effect is cummulative on token

### ISSUE THREAD

**Issue by Tupsi** [DFreds/dfreds-convenient-effects#88]
**Describe the bug**
When you create a custom effect with a token magic effect this one is additiv in a way, that each time you enable/disable the effect you get another tokenmagic entry in DAE.

**To Reproduce**
1. Go to your app and create a new effect
2. Add any effect to it
3. Add a token magic effect as 2nd effect.
4. Save
5. Apply effect on token (everything is fine)
6. Disable effect (everything is still fine, effect gets removed)
7. Apply effect again (now you can see two lines of token magic effects, there will be a new one everytime you do disable/enable)

**Expected behavior**
Only the configured effects should be present.

**Screenshots**
![image](https://user-images.githubusercontent.com/3730499/146377815-f01d166a-cf5d-46aa-a1a4-2ca5c71edbec.png)
![image](https://user-images.githubusercontent.com/3730499/146377932-f22caf6f-f115-4fec-b091-904c2b22f782.png)
![image](https://user-images.githubusercontent.com/3730499/146377969-aeebeef5-72a2-4699-b5d8-121d2eefa5d2.png)

(...a few more times disable/enable later...)

![image](https://user-images.githubusercontent.com/3730499/146378092-bb7fb0e7-02a1-4167-99fe-ce00b07f0244.png)

**Additional context**
a reload/F5 fixes this temporarily.

**Comment by DFreds** [comment]
Great find. I was handling custom effects by setting them in memory, which caused an issue when I appended the token magic changes to the custom effects.

Now, custom effects are fetched on demand from the custom effects item, so there shouldn't be any side effects of changing something set in memory.

This is fixed in v1.14.5
