### ISSUE TITLE
Custom Convinient Effects not working?

### ISSUE THREAD

**Issue by JeffreyRijkse** [DFreds/dfreds-convenient-effects#91]
Bug? When creating a custom convenient effect the effect is not applied automatically by midi-qol

1. Create a custom convenient effect or duplicate an existing
2. Create an item with the same name
3. Use the item

No errors show on the console

As a test I duplicated the custom effect hooded lantern and renamed it to hooded ballcap. When using the item named hooded ballcap it doesn't trigger the effect. If I rename the item to hooded lantern, the original effect that exists in the module is triggered as expected leading me to think the "custom effects" folder isn't being seen/used?

**Comment by DFreds** [comment]
Fixed in v2.0.1. Let me know if that doesn't appear to be the case
