### ISSUE TITLE
Drag and Drop of Custom Effects into Hotbar

### ISSUE THREAD

**Issue by Shadowscall** [DFreds/dfreds-convenient-effects#92]
**Describe the bug**
I recently updated to v9.238 of Foundry and then update Convenient effects. My custom effects no longer worked, so I deleted them off the hotbar and rebuilt them. However, when I tried to drag and drop to the hotbar, it did not work. I can drag and drop non-custom effects, but when I drop a custom effect, it just disappears without being put into the hotbar.

**To Reproduce**
1. Create a custom effect
2. Drag the custom effect to an empty space on the hotbar
3. Drop the effect on the hotbar
4. Effect does not go into hotbar

**Expected behavior**
Custom Effect should be dropped into Hotbar similar to non-custom effects

**Comment by DFreds** [comment]
Fixed in v2.0.1
