### ISSUE TITLE
v9 compatibility?

### ISSUE THREAD

**Issue by HarryWraith** [DFreds/dfreds-convenient-effects#94]
**Describe the bug**
Toggling a lighting effect from EQUIPMENT does nothing. The player illumination does not change.

**To Reproduce**
1. Select Token
2. Select hand icon
3. Select EQUIPMENT
4. Select Torch to toggle effect

**Expected behavior**
The player should be illuminated per the item toggled

**Screenshots**

**Additional context**
Have reduced all modules enable to only DFREDS Convenient Effects

**Comment by DFreds** [comment]
Known issue, see #93.
