### ISSUE TITLE
Guidance issue

### ISSUE THREAD

**Issue by rebelDog62** [DFreds/dfreds-convenient-effects#97]
I think Guidance is for ability checks not skill checks. This is from dndbeyond.

"You touch one willing creature. Once before the spell ends, the target can roll a d4 and add the number rolled to one ability check of its choice. It can roll the die before or after making the ability check. The spell then ends."

The picture below shows flags.midi-qol.optional.guidance.skill but shouldn't it be flags.midi-qol.optional.guidance.check? Maybe I'm wrong. 

![image](https://user-images.githubusercontent.com/96832988/147676181-b8c63526-ebd3-4d1b-ad72-4b9a48a5c1d1.png)

**Comment by DFreds** [comment]
Hm I'm pretty sure it also applies to skill checks, since they are also ability checks. Good reference here: https://redd.it/8ehdsx

**Comment by rebelDog62** [comment]
If you just use ".skill" though then it won't work for ability checks. If you are going to keep the .skill then you need to add .check too.

I tried rolling an ability check in Foundry using this Guidance effect and it wouldn't ever add it or give me the choice to add it.

**Comment by DFreds** [comment]
Oh I see. That's a great check. Updated for v1.15.1!

**Comment by rebelDog62** [comment]
Cool, thanks.
