### ISSUE TITLE
Shouldn't Inspiration be optional?

### ISSUE THREAD

**Issue by rebelDog62** [DFreds/dfreds-convenient-effects#98]
Currently Inspiration is set up to be used on the next attack/ability/skill check/save. Shouldn't Inspiration work kind of like Guidance and be optional until used?

Just a thought.

**Comment by DFreds** [comment]
Yeah this is a good idea. I think I just forgot to update it when the optional stuff came out. Although it will prompt each time the player rolls anything

**Comment by DFreds** [comment]
Hm, so looking at the optional stuff more, this isn't possible to do as written for Inspiration. Inspiration is supposed to provide advantage BEFORE you know the outcome of the roll, but the optional stuff in midi only allows for rerolls after you roll the first die. If you want to go that route, the best option is to follow the instructions here: https://gitlab.com/tposney/midi-qol#optional-bonus-effects

**Comment by rebelDog62** [comment]
Ah, I get it. Thanks for the link, but you are probably right. Not really any way of making the choice to use Inspiration before the roll. I'll take a look though.
