### ISSUE TITLE
Light-related effects stopped working recently

### ISSUE THREAD

**Issue by magroader** [DFreds/dfreds-convenient-effects#99]
**Describe the bug**
When I attempt to grant Light spell or a Torch, I get error messages. This is recent.

I am on Foundry version 0.8.9 still, in case that matters.

I don't have those error messages handy but I figured I should report it anyway, with more details to be filled in later.

**To Reproduce**
1. Click token
2. Apply light effect
3. Notice error message, and light doesn't emit from token. Token DOES get the light "effect" icon applied, just no light is produced.

**Expected behavior**
Light should emit from token

**Additional context**
If you need more info I can spend time digging up mods I am using etc., but I'm hoping you're like "Oh yeah that broke with a recent 0.9.x update, oops!" or something.

**Comment by DFreds** [comment]
What version of CE and ATL are you on?

**Comment by magroader** [comment]
I assume CE is Combat Enhancements and ATL is Active Token Effects (previously Active Token Lighting I guess)?

If so, I was on the versions that auto-installed in 0.8.9 as of last night, which were:

- Combat Enhancements 1.0.2
- Active Token Effects 0.3.04

**Comment by DFreds** [comment]
Sorry for not clarifying.... CE is convenient effects. :D

**Comment by magroader** [comment]
Oh! Of course! lol

- DrFred's Convenient Effects 1.15.1

**Comment by DFreds** [comment]
Hm, it should work. I'm not really sure immediately and I can't reproduce it. Since all CE is doing is adding the effects from ATL, it's likely an issue with ATL instead of CE. 

Is there anything in the console log if you hit F12 and apply a torch effect? 
Also, maybe try a test a new world with a new actor? Let me know what those scenarios produce.

**Comment by magroader** [comment]
I think I must have slipped in an update between DAE introducing a bug and then tweaking their module to be only compatible with 0.9.x. I went through the process of upgrading to 0.9 and this is no longer happening.
